/** Local image paths served from /public/images */

export const DESTINATION_IMAGES = {
  everest: "/images/destinations/everest.webp",
  kathmandu: "/images/destinations/kathmandu.jpg",
  pokhara: "/images/destinations/pokhara.jpg",
  chitwan: "/images/destinations/chitwan.jpg",
  annapurna: "/images/destinations/annapurna.jpg",
} as const;

export const HOME_IMAGES = {
  hero: "/images/home/hero.webp",
  trustSection: "/images/home/trust-section.jpg",
} as const;

export const LOCATION_IMAGES = {
  boudha: "/images/locations/boudha.jpg",
  chandragiri: "/images/locations/chandragiri.jpg",
  lukla: "/images/locations/lukla.jpg",
  phakding: "/images/locations/phakding.jpg",
  namche: "/images/locations/namche.jpg",
  tengboche: "/images/locations/tengboche.webp",
  dingboche: "/images/locations/dingboche.webp",
  gokyoLake: "/images/locations/gokyo-lake.jpg",
  machhermo: "/images/locations/machhermo.jpg",
  kalaPatthar: "/images/locations/kala-patthar.webp",
  bandipur: "/images/locations/bandipur.jpeg",
  swayambhunath: "/images/locations/swayambhunath.jpg",
  durbarSquare: "/images/destinations/kathmandu.jpg",
  lumbini: "/images/locations/lumbini.jpg",
  peaceStupaPokhara: "/images/locations/peace-stupa-pokhara.jpg",
  sarangkot: "/images/locations/sarangkot.jpg",
  poonHill: "/images/locations/poon-hill.jpg",
  ghorepani: "/images/locations/ghorepani.jpg",
  ghandruk: "/images/locations/ghandruk.jpeg",
  mardiHimal: "/images/locations/mardi-himal.jpg",
  langtangVillage: "/images/locations/langtang-village.jpg",
  gosaikunda: "/images/locations/gosaikunda.jpg",
  kyanjinGompa: "/images/locations/kyanjin-gompa.jpg",
  syabrubesi: "/images/locations/syabrubesi.jpg",
  upperMustang: "/images/locations/upper-mustang.jpg",
  kagbeni: "/images/locations/kagbeni.jpg",
  muktinath: "/images/locations/muktinath.jpg",
  jomsom: "/images/locations/jomsom.jpg",
  sundarijal: "/images/locations/sundarijal.webp",
  chisapaniKutumsang: "/images/locations/chisapani-kutumsang.jpg",
  tarkeGhyang: "/images/locations/tarke-ghyang.jpg",
  thadepati: "/images/locations/thadepati.jpg",
  paragliding: "/images/locations/paragliding.jpg",
  rafting: "/images/locations/rafting.jpg",
  chitwanSafari: "/images/locations/chitwan-park.jpg",
  chitwanResort: "/images/locations/chitwan-resort.jpg",
  tikhedhunga: "/images/locations/tikhedhunga.jpg",
  australianCamp: "/images/locations/australian-camp.webp",
  mardiHighCamp: "/images/locations/mardi-high-camp.webp",
  lamaHotel: "/images/locations/lama-hotel.webp",
  singGompa: "/images/locations/sing-gompa.jpg",
  gupteshworCave: "/images/locations/gupteshwor-cave.jpg",
  devilsFall: "/images/locations/devils-fall.jpg",
  phewaLake: "/images/locations/phewa-lake.jpg",
  pokhara: "/images/destinations/pokhara.jpg",
  teaHouse: "/images/locations/tea-house.jpg",
} as const;

/** Compact images for day-by-day itinerary blocks */
export const ITINERARY_IMAGES = {
  boudha: "/images/itinerary/boudha.jpg",
  lukla: "/images/itinerary/lukla.jpg",
  phakding: "/images/itinerary/phakding.jpg",
  namche: "/images/itinerary/namche.jpg",
  tengboche: "/images/itinerary/tengboche.webp",
  dingboche: "/images/itinerary/dingboche.webp",
  gokyoLake: "/images/itinerary/gokyo-lake.jpg",
  kalaPatthar: "/images/itinerary/kala-patthar.webp",
  machhermo: "/images/itinerary/machhermo.jpg",
  durbarSquare: "/images/itinerary/durbar-square.jpg",
  swayambhunath: "/images/itinerary/swayambhunath.jpg",
  poonHill: "/images/itinerary/poon-hill.jpg",
  ghandruk: "/images/itinerary/ghandruk.jpeg",
  mardiHimal: "/images/itinerary/mardi-himal.jpg",
  langtangVillage: "/images/itinerary/langtang-village.jpg",
  gosaikunda: "/images/itinerary/gosaikunda.jpg",
  upperMustang: "/images/itinerary/upper-mustang.jpg",
  kagbeni: "/images/itinerary/kagbeni.jpg",
  muktinath: "/images/itinerary/muktinath.jpg",
  lumbini: "/images/itinerary/lumbini.jpg",
  phewaLake: "/images/itinerary/phewa-lake.jpg",
  chitwanSafari: "/images/itinerary/chitwan-safari.jpg",
  sundarijal: "/images/itinerary/sundarijal.webp",
  tarkeGhyang: "/images/itinerary/tarke-ghyang.jpg",
  sarangkot: "/images/itinerary/sarangkot.jpg",
  ghorepani: "/images/itinerary/ghorepani.jpg",
} as const;

export const TRIP_HERO_IMAGES = {
  "everest-base-camp-trek": "/images/trips/everest-base-camp/hero.webp",
  "ebc-trek-with-gokyo-lake-trekking": "/images/trips/ebc-gokyo/hero.jpg",
  "ghorepani-poon-hill": "/images/trips/ghorepani-poon-hill/hero.jpeg",
  "mardi-himal-base-camp-trek": "/images/trips/mardi-himal/hero.jpg",
  "upper-mustang-trek-hidden-kingdom": "/images/trips/upper-mustang/hero.jpg",
  "langtang-valley-with-gosaikunda-trek": "/images/trips/langtang-gosaikunda/hero.jpg",
  "ghandruk-landruk-annapurna-trek-experience": "/images/trips/ghandruk/hero.jpeg",
  "kathmandu-pokhara-chitwan-experience-nepal": "/images/trips/kathmandu-cultural/hero.jpg",
  "highlights-of-nepal-tour": "/images/trips/highlights-nepal/hero.jpeg",
  "nepal-round-trip": "/images/trips/nepal-round-trip/hero.jpg",
  "lumbini-pokhara-tour": "/images/trips/lumbini-pokhara/hero.jpg",
  "chisapani-helambu-trek-itinerary-cost": "/images/trips/chisapani-helambu/hero.webp",
  "annapurna-circuit-trek-classic-trek": "/images/trips/annapurna-circuit/hero.jpg",
  "poon-hill-taster-pokhara-5-days": "/images/trips/poon-hill-taster/hero.jpg",
  "pikey-base-camp-trek-everest-view": "/images/trips/pikey-peak/hero.webp",
  "monk-for-a-month-nepal": "/images/trips/monk-month/hero.jpg",
  "scenic-nepal-7-days": "/images/trips/scenic-nepal/hero.jpg",
  "everest-mountain-flight-1-day": "/images/trips/everest-flight/hero.webp",
  "langtang-valley-trek-with-ganja-la-pass": "/images/trips/langtang-ganja-la/hero.jpg",
  "the-royal-annapurna-trekking": "/images/trips/royal-annapurna/hero.webp",
  "explore-annapurna-base-camp-in-17-days": "/images/trips/annapurna-base-camp/hero.jpg",
  "buddhist-pilgrimage-tour": "/images/trips/buddhist-pilgrimage/hero.jpg",
} as const;

export function tripHeroImage(slug: string): string | undefined {
  return TRIP_HERO_IMAGES[slug as keyof typeof TRIP_HERO_IMAGES];
}
