import type { PublicTrip } from "@/types/trip";
import { ITINERARY_IMAGES, LOCATION_IMAGES, TRIP_HERO_IMAGES } from "@/lib/trip-images";

const MAP_URL = "https://himalayancircuit.com/images/map/Group%20277.png";
const HERO_URL = TRIP_HERO_IMAGES["upper-mustang-trek-hidden-kingdom"];

export const FALLBACK_TRIP_UPPER_MUSTANG_TREK_HIDDEN_KINGDOM: PublicTrip = {
  id: 15,
  slug: "upper-mustang-trek-hidden-kingdom",
  title: "Upper Mustang Trek – Hidden Kingdom",
  summary:
    "Seventeen days into the forbidden kingdom of Lo: flight to Jomsom, Kali Gandaki to Kagbeni, walled Lo Manthang, Drakmar and ancient monasteries, Muktinath, and Tibetan culture in the Annapurna rain shadow.",
  description:
    "The Upper Mustang trek takes you into the old Buddhist kingdom of Mustang—also known as Lo—a desolate, rock-strewn landscape in the Dhaulagiri rain shadow that feels like a pocket of Tibet. The trail follows the historic salt-caravan route up the Kali Gandaki from Jomsom to Kagbeni, where the restricted area begins, then north to walled Lo Manthang. An optional detour via Dhakmar reaches Lo Gekar, among the oldest Tibetan monasteries, said to have been founded in the 8th century by Guru Rinpoche. Foreign access was banned until 1992; today a special permit is required (about USD 500 for ten days). Tea houses along the way share authentic Tibetan culture. Lo Manthang sits near 3,800 m with caves, monasteries, and the colourful three-day Tiji festival each spring. This is a challenging trek—high elevation, exposed terrain, and strong winds—but one of Nepal’s most rewarding cultural journeys.",
  durationDays: 17,
  tripType: "trekking_hiking",
  budgetLevel: "premium",
  comfortLevel: "basic",
  difficultyLevel: "challenging",
  interestTags: [
    "mustang",
    "lo_manthang",
    "restricted_area",
    "tibetan_culture",
    "muktinath",
    "jomsom",
    "kali_gandaki",
    "trekking",
    "tiji_festival",
  ],
  priceFrom: { amount: "4054", currency: "USD" },
  imageUrl: HERO_URL,
  startingRegion: { slug: "kathmandu-valley", name: "Kathmandu Valley" },
  totalDistanceKm: 945,
  altitudeMaxM: 3840,
  altitudeMinM: 822,
  routeGrades: ["Grade C (difficult)"],
  fitnessNotes: ["Aerobic fitness", "Strength", "Stamina"],
  recommendedSeasons: ["Autumn", "Spring"],
  mapImageUrl: MAP_URL,
  galleryImageUrls: [
    HERO_URL,
    LOCATION_IMAGES.upperMustang,
    LOCATION_IMAGES.kagbeni,
    LOCATION_IMAGES.muktinath,
  ],
  sourceReferenceUrl:
    "https://himalayancircuit.com/tour/upper-mustang-trek-hidden-kingdom",
  priceTable: {
    currency: "USD",
    supplementaryChargePercent: 30,
    footnote:
      "Indicative per-person pricing for the services described in this offer. Cost varies with customization. International flights are not included. Upper Mustang restricted-area permit (about USD 500 per person for 10 days) is additional.",
    columns: [
      { key: "2", label: "2 travellers" },
      { key: "4", label: "4 travellers" },
      { key: "8", label: "8 travellers" },
    ],
    rows: [
      {
        label: "Standard",
        prices: { "2": "4270", "4": "4174", "8": "4054" },
      },
      {
        label: "Deluxe",
        prices: { "2": "4603", "4": "4507", "8": "4387" },
      },
    ],
  },
  bookingFeeItems: [
    "T-shirt",
    "Special permit (approx. USD 500 per person)",
    "24/7 support",
    "Fully customize",
  ],
  gearChecklist: [
    "Sleeping bag",
    "Backpack",
    "Hiking boots",
    "Socks",
    "T-shirts",
    "Thermals",
    "Down jacket",
    "Rain jacket",
    "Warm cap & gloves",
    "Sun hat / sunglasses",
    "Lip balm",
    "Personal medicines",
    "First-aid kit",
  ],
  trekkingGradeNotes:
    "Grade C: wind-exposed Kali Gandaki walking, passes near 3,800 m, and long days on dry, rocky terrain. Restricted-area permit required; plan for Tiji festival dates if visiting Lo Manthang in May.",
  faq: [
    {
      question: "When is the Tiji Festival in Lo Manthang?",
      answer:
        "Tiji is a three-day Buddhist celebration in Lo Manthang, typically in late May (e.g. 24–26 May 2025, 14–16 May 2026, 1–3 June 2027). Book early if you want to align your trek with the festival.",
    },
    {
      question: "What kind of food can I expect in Nepal?",
      answer:
        "Tea houses serve hearty dal bhat, noodles, and Tibetan-influenced dishes. In Mustang, meals are simple but filling; carry snacks for long windy days on the river trail.",
    },
  ],
  reviewSnippets: [
    { name: "Christopher", location: "UK", date: "2026-04-20" },
    { name: "David", location: "Australia", date: "2026-04-09" },
    { name: "Mathis & Ida", location: "Germany", date: "2026-04-06" },
    { name: "Paul & Tim", location: "Germany", date: "2026-03-25" },
    { name: "Claudia", location: "Germany", date: "2026-03-18" },
  ],
  services: {
    included: [
      "Airport pickups and transfers by private vehicle as per itinerary",
      "Three-star twin/double room with breakfast in Kathmandu and Pokhara",
      "Teahouse accommodation in twin rooms during the trek",
      "Domestic flights Jomsom–Pokhara and Pokhara–Kathmandu",
      "Private trekking guide",
      "Entrance fees, restricted-zone permit, trekking permits, and TIMS",
      "One porter for every two trekkers",
    ],
    excluded: [
      "Personal, travel, and medical insurance",
      "International flights to and from Nepal",
      "Personal expenses, drinks, laundry, and extra meals",
      "Trekking gear other than sleeping bag, down jacket, and T-shirt where provided",
      "Nepal visa fee",
      "Lunch and dinner in Kathmandu and Pokhara",
      "Upper Mustang special permit fee (approx. USD 500 per person, paid separately)",
    ],
    optional: [
      "Extra nights in Pokhara or Kathmandu",
      "Helicopter or itinerary upgrades",
      "Tiji festival timing and extended stay in Lo Manthang",
    ],
  },
  days: [
    {
      dayNumber: 1,
      title: "Arrive in Kathmandu and transfer to your hotel",
      description: "Welcome to Nepal",
      details:
        "Our team meets you at the airport and transfers you to your hotel. The day is free to explore Kathmandu; in the evening a welcome dinner outlines the trek ahead.",
      destinationName: "Kathmandu",
      distanceKm: 5,
      altitudeMaxM: 1400,
      altitudeMinM: 1400,
      durationHours: 0.5,
      accommodation: "Hotel",
      meals: "Breakfast",
    },
    {
      dayNumber: 2,
      title: "Kathmandu UNESCO sites and trek preparation",
      description: "Heritage and briefing",
      details:
        "Morning sightseeing at major UNESCO-listed sites in the valley. The afternoon is free for trek preparation and last-minute shopping.",
      destinationName: "Kathmandu",
      distanceKm: 4,
      altitudeMaxM: 1400,
      altitudeMinM: 1400,
      durationHours: 4,
      accommodation: "Hotel",
      meals: "Breakfast",
    },
    {
      dayNumber: 3,
      title: "Scenic drive from Kathmandu to Pokhara",
      description: "Into the lake city",
      details:
        "After breakfast, a picturesque six- to seven-hour drive to Pokhara with lunch and rest stops en route. Notice the changing landscape as you approach the Annapurna foothills.",
      destinationName: "Pokhara",
      distanceKm: 200,
      altitudeMaxM: 1400,
      altitudeMinM: 822,
      durationHours: 7,
      accommodation: "Hotel",
      meals: "Breakfast",
    },
    {
      dayNumber: 4,
      title: "Fly Pokhara to Jomsom — trek to Kagbeni",
      description: "Gateway to Upper Mustang",
      details:
        "A 20-minute scenic flight to Jomsom, then breakfast and permit formalities before trekking about three hours to Kagbeni—monastery village and gateway to the restricted area.",
      destinationName: "Kagbeni",
      distanceKm: 168,
      altitudeMaxM: 2804,
      altitudeMinM: 822,
      durationHours: 5,
      accommodation: "Tea house / mountain lodge",
      meals: "Breakfast, lunch, dinner",
      imageUrl: ITINERARY_IMAGES.kagbeni,
    },
    {
      dayNumber: 5,
      title: "Trek Kagbeni to Chele",
      description: "Into restricted Mustang",
      details:
        "Climb over Gyu La, cross the river, and ascend to Chele with Nilgiri visible for much of the day.",
      destinationName: "Chele",
      distanceKm: 18,
      altitudeMaxM: 3100,
      altitudeMinM: 2804,
      durationHours: 6,
      accommodation: "Tea house / mountain lodge",
      meals: "Breakfast, lunch, dinner",
    },
    {
      dayNumber: 6,
      title: "Trek Chele to Syangboche",
      description: "Via Samar",
      details:
        "Six to seven hours through phenomenal, breath-taking high-desert scenery via Samar to Syangboche.",
      destinationName: "Syangboche",
      distanceKm: 21,
      altitudeMaxM: 3800,
      altitudeMinM: 3100,
      durationHours: 7,
      accommodation: "Tea house / mountain lodge",
      meals: "Breakfast, lunch, dinner",
    },
    {
      dayNumber: 7,
      title: "Trek Syangboche to Tsarang",
      description: "Flaming mountains",
      details:
        "Cross Syangboche La and Nyila Pass (about 3,600 m). After the pass the landscape shifts to Mustang’s famous red cliffs. Lunch in Ghemi, then Tsarang La and Charang with its former royal palace.",
      destinationName: "Tsarang",
      distanceKm: 30,
      altitudeMaxM: 3800,
      altitudeMinM: 3560,
      durationHours: 7,
      accommodation: "Tea house / mountain lodge",
      meals: "Breakfast, lunch, dinner",
    },
    {
      dayNumber: 8,
      title: "Trek to Lo Manthang — last forbidden kingdom",
      description: "Walled capital of Lo",
      details:
        "Explore Tsarang’s monastery, then walk via Dhakmar toward walled Lo Manthang (about 3,840 m)—earth-brown and white houses within a single gateway, capital of ancient Mustang.",
      destinationName: "Lo Manthang",
      distanceKm: 15,
      altitudeMaxM: 3840,
      altitudeMinM: 3560,
      durationHours: 5,
      accommodation: "Tea house / mountain lodge",
      meals: "Breakfast, lunch, dinner",
      imageUrl: ITINERARY_IMAGES.upperMustang,
    },
    {
      dayNumber: 9,
      title: "Exploration day in Lo Manthang",
      description: "Temples and royal quarter",
      details:
        "Discover Lo Manthang’s temples and the king’s palace at the centre—still occupied, with a chance to glimpse local royalty in this region opened to foreigners only in the 1990s.",
      destinationName: "Lo Manthang",
      distanceKm: 3,
      altitudeMaxM: 3840,
      altitudeMinM: 3840,
      durationHours: 2,
      accommodation: "Tea house / mountain lodge",
      meals: "Breakfast, lunch, dinner",
    },
    {
      dayNumber: 10,
      title: "Trek Lo Manthang to Ghami via Drakmar",
      description: "Gyokar Gompa",
      details:
        "Leave Lo Manthang for Ghami via Drakmar—the deepest point of Upper Mustang on this route—and visit Gyokar Gompa, said to be more than 1,200 years old. Five to six hours walking.",
      destinationName: "Ghami",
      distanceKm: 26,
      altitudeMaxM: 3840,
      altitudeMinM: 3510,
      durationHours: 7,
      accommodation: "Tea house / mountain lodge",
      meals: "Breakfast, lunch, dinner",
    },
    {
      dayNumber: 11,
      title: "Trek Ghami to Chhuksang",
      description: "Desert trail",
      details:
        "Descend through arid country beside the river, crossing the Kali Gandaki to reach Chhuksang.",
      destinationName: "Chhuksang",
      distanceKm: 38,
      altitudeMaxM: 3510,
      altitudeMinM: 2980,
      durationHours: 7,
      accommodation: "Tea house / mountain lodge",
      meals: "Breakfast, lunch, dinner",
    },
    {
      dayNumber: 12,
      title: "Trek Chhuksang to Muktinath",
      description: "Sacred pilgrimage site",
      details:
        "Six to seven hours through desert-like sections, fields, apple orchards, caves, and Tibetan-style villages to Muktinath—108 holy taps, monastery, and temples shared by Hindus and Buddhists.",
      destinationName: "Muktinath",
      distanceKm: 32,
      altitudeMaxM: 3762,
      altitudeMinM: 2980,
      durationHours: 7,
      accommodation: "Tea house / mountain lodge",
      meals: "Breakfast, lunch, dinner",
      imageUrl: ITINERARY_IMAGES.muktinath,
    },
    {
      dayNumber: 13,
      title: "Trek Muktinath to Jomsom",
      description: "Last trekking day",
      details:
        "Five to six hours through villages and fields beside the Kali Gandaki, with Nilgiri and Dhaulagiri overhead, passing monasteries en route to Jomsom.",
      destinationName: "Jomsom",
      distanceKm: 20,
      altitudeMaxM: 3762,
      altitudeMinM: 2743,
      durationHours: 6,
      accommodation: "Tea house / mountain lodge",
      meals: "Breakfast, lunch, dinner",
      imageUrl: LOCATION_IMAGES.jomsom,
    },
    {
      dayNumber: 14,
      title: "Morning flight Jomsom to Pokhara",
      description: "Back to the lakeside",
      details:
        "Fly to Pokhara for lunch and a free afternoon to explore town, shops, and lakeside attractions.",
      destinationName: "Pokhara",
      distanceKm: 155,
      altitudeMaxM: 2743,
      altitudeMinM: 822,
      durationHours: 1,
      accommodation: "Hotel",
      meals: "Breakfast",
    },
    {
      dayNumber: 15,
      title: "Free day in Pokhara",
      description: "Rest and explore",
      details:
        "Optional visits to Phewa Lake, Devi’s Fall, World Peace Stupa, and lakeside cafés and restaurants.",
      destinationName: "Pokhara",
      distanceKm: 0,
      altitudeMaxM: 822,
      altitudeMinM: 822,
      durationHours: 0,
      accommodation: "Hotel",
      meals: "Breakfast",
    },
    {
      dayNumber: 16,
      title: "Fly Pokhara to Kathmandu",
      description: "Return to the capital",
      details:
        "A short flight (or optional bus) to Kathmandu, with time for final shopping and a farewell dinner with a traditional Nepali cultural show.",
      destinationName: "Kathmandu",
      distanceKm: 205,
      altitudeMaxM: 1400,
      altitudeMinM: 822,
      durationHours: 1,
      accommodation: "Hotel",
      meals: "Breakfast",
    },
    {
      dayNumber: 17,
      title: "Depart Kathmandu — airport transfer",
      description: "Farewell",
      details:
        "Transfer to the airport for your onward journey—we hope to welcome you back to Nepal.",
      destinationName: "Kathmandu",
      distanceKm: 5,
      altitudeMaxM: 1400,
      altitudeMinM: 1400,
      durationHours: 0.5,
      accommodation: "Hotel",
      meals: "Breakfast",
    },
  ],
};
