import type { PublicTrip } from "@/types/trip";
import { ITINERARY_IMAGES, LOCATION_IMAGES, TRIP_HERO_IMAGES } from "@/lib/trip-images";

const MAP_URL = "https://himalayancircuit.com/images/map/Group%20277.png";
const HERO_URL = TRIP_HERO_IMAGES["langtang-valley-trek-with-ganja-la-pass"];

export const FALLBACK_TRIP_LANGTANG_VALLEY_GANJA_LA_PASS_14_DAYS: PublicTrip = {
  id: 17,
  slug: "langtang-valley-trek-with-ganja-la-pass",
  title: "Langtang Valley Trek with Ganja La Pass",
  summary:
    "Fourteen days from Kathmandu along the classic Langtang valley to Kyanjin Gompa, then a high crossing of Ganja La Pass into Helambu’s Buddhist villages—bridges, yak pastures, Tamang and Hyolmo culture, and panoramas of Langtang Lirung and Shishapangma.",
  description:
    "Trekking Ganja La Pass extends the Langtang valley route in technical stretches where basic mountaineering awareness helps: rocky moraine, possible snow on the pass, and quieter trails after Kyanjin Gompa. Until Kyanjin you follow the same trail from Syabrubesi as on the standard Langtang trek; there you acclimatise with Tsergo Ri before committing to the pass. From Ganja La you descend into Helambu, rich in Yolmo heritage and ancient monasteries linked to Milarepa and Guru Rinpoche. Langtang is among the closest major trekking areas from Kathmandu, with Tibetan-influenced highland villages along the borderlands.",
  durationDays: 14,
  tripType: "trekking_hiking",
  budgetLevel: "premium",
  comfortLevel: "basic",
  difficultyLevel: "challenging",
  interestTags: [
    "langtang",
    "ganja_la",
    "helambu",
    "trekking",
    "high_pass",
    "tamang",
    "yolmo",
    "himalaya",
  ],
  priceFrom: { amount: "1854", currency: "USD" },
  imageUrl: HERO_URL,
  startingRegion: { slug: "kathmandu-valley", name: "Kathmandu Valley" },
  totalDistanceKm: 280,
  altitudeMaxM: 5121,
  altitudeMinM: 1400,
  routeGrades: ["Grade C (difficult)", "Grade D (quite the challenge)"],
  fitnessNotes: ["Strength", "Stamina"],
  recommendedSeasons: ["Autumn", "Spring"],
  mapImageUrl: MAP_URL,
  galleryImageUrls: [
    HERO_URL,
    LOCATION_IMAGES.langtangVillage,
    LOCATION_IMAGES.kyanjinGompa,
    LOCATION_IMAGES.tarkeGhyang,
  ],
  sourceReferenceUrl: "https://himalayancircuit.com/tour/langtang-valley-trek-with-ganja-la-pass",
  priceTable: {
    currency: "USD",
    supplementaryChargePercent: 30,
    footnote:
      "Indicative per-person pricing for the services described in this offer. Cost varies with customization. International flights are not included.",
    columns: [
      { key: "2", label: "2 travellers" },
      { key: "4", label: "4 travellers" },
      { key: "8", label: "8 travellers" },
    ],
    rows: [
      {
        label: "Standard",
        prices: { "2": "2070", "4": "1974", "8": "1854" },
      },
      {
        label: "Deluxe",
        prices: { "2": "2352", "4": "2256", "8": "2136" },
      },
    ],
  },
  bookingFeeItems: ["Price of entrance fee", "Trekking guide", "T-shirt"],
  gearChecklist: [
    "Hiking boots",
    "First-aid kit",
    "Thermal bottle",
    "Sleep wear / base layers",
    "Sandals",
    "Rain jacket",
    "Warm cap & gloves",
    "Travel towels",
    "Sunglasses / sun hat",
    "Personal medicines",
    "Down jacket",
    "Sleeping bag",
    "Backpack",
    "T-shirts",
    "Plug adapter (if needed)",
    "Lip balm",
    "Insect repellent",
  ],
  trekkingGradeNotes:
    "Grade C and D routes assume sections of steep ascent and descent, possible snow on Ganja La, and several long trekking days. Compare this with our written grading system in your pre-departure notes so expectations match your experience.",
  faq: [
    {
      question: "When is the best time to travel to Nepal?",
      answer:
        "Autumn (September–November) and spring (March–May) usually bring clearer skies, mild temperatures, and excellent trekking conditions.",
    },
    {
      question: "How are treks graded?",
      answer:
        "We publish grades so you can judge stamina and technical difficulty. Ganja La combines altitude with rough trail—confirm with us if you are unsure.",
    },
  ],
  reviewSnippets: [
    { name: "Christopher", location: "UK", date: "2026-04-20" },
    { name: "David", location: "Australia", date: "2026-04-09" },
    { name: "Mathis & Ida", location: "Germany", date: "2026-04-06" },
    { name: "Paul & Tim", location: "Germany", date: "2026-03-25" },
    { name: "Claudia", location: "Germany", date: "2026-03-18" },
  ],
  services: {
    included: [
      "Hotel accommodation in Kathmandu with breakfast",
      "Personal trekking guide (Sherpa-led team)",
      "Entrance fees, trekking permits, and TIMS",
      "All three meals during trekking",
      "All ground transfers as per itinerary",
      "Trekking guide and porters’ meals, accommodation, salary, and insurance",
      "Applicable taxes",
    ],
    excluded: [
      "International flights and Nepal visa fees",
      "Travel medical insurance including helicopter rescue",
      "Personal trekking gear",
      "Personal expenses and unforeseen costs",
      "Bar bills, bottled water, and snacks outside included meals",
      "Natural calamities beyond our control and rescue expenses",
      "Lunch and dinner in Kathmandu and gratuities for staff",
    ],
    optional: [
      "Room upgrade or single supplement",
      "Extra nights in Kathmandu",
      "Private vehicle or itinerary adjustments",
    ],
  },
  days: [
    {
      dayNumber: 1,
      title: "Arrival in Kathmandu and transfer to your hotel",
      description: "Meet-and-greet and transfer",
      details:
        "Flying toward the Himalaya, Kathmandu Valley spreads below—three historic cities (Kathmandu, Patan, Bhaktapur) hold seven UNESCO World Heritage Sites between them. Our representative meets you at the airport and drives you to the hotel with time to rest after your flight.",
      destinationName: "Kathmandu",
      distanceKm: 5,
      altitudeMaxM: 1400,
      altitudeMinM: 1400,
      durationHours: 0.5,
      accommodation: "Hotel",
      meals: "As arranged",
    },
    {
      dayNumber: 2,
      title: "Trekking warm-up — explore Kathmandu",
      description: "Sightseeing and briefing",
      details:
        "Sightseeing in the old city—for example Durbar Square with its former royal palace—and time to pick up any last gear. Later you receive a full briefing and gear check before leaving for the trek.",
      destinationName: "Kathmandu",
      distanceKm: 3,
      altitudeMaxM: 1400,
      altitudeMinM: 1400,
      durationHours: 3,
      accommodation: "Hotel",
      meals: "Breakfast",
    },
    {
      dayNumber: 3,
      title: "Drive from Kathmandu toward Dhunche; overnight Syabrubesi",
      description: "Road into Rasuwa",
      details:
        "You leave Kathmandu by vehicle through small settlements and changing landscapes toward Dhunche, headquarters of Rasuwa district. The road can be rough after Trishuli bazaar. Your guide completes trekking permits at the check post before you continue to Syabrubesi on the Langtang Khola for the night.",
      destinationName: "Syabrubesi",
      distanceKm: 100,
      altitudeMaxM: 2029,
      altitudeMinM: 1400,
      durationHours: 4,
      accommodation: "Tea house / mountain lodge",
      meals: "Breakfast, lunch, dinner",
    },
    {
      dayNumber: 4,
      title: "Trek to Lama Hotel",
      description: "Forest trails beside the river",
      details:
        "First full trekking day: suspension bridges over the Langtang river, deep valley walking, then ascent through bamboo toward Rimche and on to Lama Hotel—watch for monkeys in the forest and possible signs of red panda or bear.",
      destinationName: "Lama Hotel",
      distanceKm: 27,
      altitudeMaxM: 2470,
      altitudeMinM: 2030,
      durationHours: 7,
      accommodation: "Tea house / mountain lodge",
      meals: "Breakfast, lunch, dinner",
    },
    {
      dayNumber: 5,
      title: "Trek from Lama Hotel to Langtang village",
      description: "Into open pasture",
      details:
        "A steady climb through small settlements and yak pastures, crossing streams and moraine benches toward Kyangjin for lunch, then onward with time to explore Langtang village—photography-friendly ridges and welcoming lodges.",
      destinationName: "Langtang",
      distanceKm: 12,
      altitudeMaxM: 3430,
      altitudeMinM: 2470,
      durationHours: 6,
      accommodation: "Tea house / mountain lodge",
      meals: "Breakfast, lunch, dinner",
      imageUrl: ITINERARY_IMAGES.langtangVillage,
    },
    {
      dayNumber: 6,
      title: "Trek from Langtang to Kyanjin Gompa",
      description: "Glacier towers above the gompa",
      details:
        "Short ascent brings views toward Chorkari Ri and the Langtang giants—Langtang Lirung, Langshisa Ri, Gyanghempo, and Ganja La peaks. Afternoon options include the yak cheese factory and monastery; moraine and ice cliffs frame Kyanjin Gompa.",
      destinationName: "Kyanjin Gompa",
      distanceKm: 7,
      altitudeMaxM: 3870,
      altitudeMinM: 3430,
      durationHours: 3,
      accommodation: "Tea house / mountain lodge",
      meals: "Breakfast, lunch, dinner",
    },
    {
      dayNumber: 7,
      title: "Acclimatisation at Kyanjin Gompa — day hike to Tsergo Ri",
      description: "Altitude preparation",
      details:
        "Breakfast with local yak cheese, then a strenuous hike toward Tsergo Ri for sweeping Himalayan views—a useful acclimatisation step before Ganja La. Return to Kyanjin Gompa for a relaxed afternoon.",
      destinationName: "Kyanjin Gompa",
      distanceKm: 8,
      altitudeMaxM: 4957,
      altitudeMinM: 3430,
      durationHours: 6,
      accommodation: "Tea house / mountain lodge",
      meals: "Breakfast, lunch, dinner",
    },
    {
      dayNumber: 8,
      title: "Trek from Kyanjin Gompa to Ganja La Phedi",
      description: "Approach to the pass",
      details:
        "Remote trail toward Ganja La Phedi: cross the Langtang river and climb through rhododendron forest to a high camp area—often tented—with thinning air and careful pacing under your guide’s direction.",
      destinationName: "Ganja La Phedi",
      distanceKm: 8,
      altitudeMaxM: 5121,
      altitudeMinM: 4270,
      durationHours: 6,
      accommodation: "Tented camp",
      meals: "Breakfast, lunch, dinner",
    },
    {
      dayNumber: 9,
      title: "Cross Ganja La Pass to Keldang",
      description: "Summit day",
      details:
        "Early start for the pass—often snow-covered—with slow steps on rocky moraine. Langtang Himal fills the horizon before a demanding descent toward Keldang (camp); conserve energy for repeated ups and downs.",
      destinationName: "Keldang",
      distanceKm: 8,
      altitudeMaxM: 5130,
      altitudeMinM: 4300,
      durationHours: 6,
      accommodation: "Tented camp",
      meals: "Breakfast, lunch, dinner",
    },
    {
      dayNumber: 10,
      title: "Trek from Keldang to Dukpu",
      description: "Forests and ridges",
      details:
        "Descents through forest and pasture, keeping an eye out for red panda in bamboo, deer, or blue sheep; mountain views open along the ridges before reaching Dukpu—often the last camping night.",
      destinationName: "Dukpu",
      distanceKm: 12,
      altitudeMaxM: 4270,
      altitudeMinM: 4040,
      durationHours: 8,
      accommodation: "Tented camp",
      meals: "Breakfast, lunch, dinner",
    },
    {
      dayNumber: 11,
      title: "Trek from Dukpu to Tarke Gyang",
      description: "Helambu monasteries",
      details:
        "Continue descending with short climbs through Sherpa settlements to Tarke Gyang, known for Geke Gompa and Hyolmo hospitality—from tonight you may choose lodge stays instead of tents where available.",
      destinationName: "Tarke Gyang",
      distanceKm: 8,
      altitudeMaxM: 4040,
      altitudeMinM: 2740,
      durationHours: 7,
      accommodation: "Tea house / mountain lodge",
      meals: "Breakfast, lunch, dinner",
      imageUrl: ITINERARY_IMAGES.tarkeGhyang,
    },
    {
      dayNumber: 12,
      title: "Trek from Tarke Gyang to Shermathang",
      description: "Mani walls and terraces",
      details:
        "Wider, easier trails pass villages such as Setighyang and Ghangyul; Buddhist mani walls line the path and terraces step down the hillsides—observe daily farm work and Hyolmo life.",
      destinationName: "Shermathang",
      distanceKm: 11,
      altitudeMaxM: 2740,
      altitudeMinM: 2600,
      durationHours: 4,
      accommodation: "Tea house / mountain lodge",
      meals: "Breakfast, lunch, dinner",
    },
    {
      dayNumber: 13,
      title: "Shermathang — Melamchi — drive to Kathmandu",
      description: "Exit the hills by road",
      details:
        "Walk from Shermathang toward Melamchi Pool bazaar, chat with locals over lunch, then drive back to Kathmandu for a final evening with your team.",
      destinationName: "Kathmandu",
      distanceKm: 66,
      altitudeMaxM: 2590,
      altitudeMinM: 1400,
      durationHours: 4,
      accommodation: "Hotel",
      meals: "Breakfast, lunch, dinner",
    },
    {
      dayNumber: 14,
      title: "Kathmandu — onward travel or extend",
      description: "Departure day",
      details:
        "Transfer out according to your flight plan—two weeks of peaks, passes, and villages behind you, with Nepal’s invitation to return.",
      destinationName: "Kathmandu",
      distanceKm: 5,
      altitudeMaxM: 1400,
      altitudeMinM: 1400,
      durationHours: 0.5,
      accommodation: "Hotel",
      meals: "Breakfast",
    },
  ],
};
