import type { PublicTrip } from "@/types/trip";
import { ITINERARY_IMAGES, LOCATION_IMAGES, TRIP_HERO_IMAGES } from "@/lib/trip-images";

const MAP_URL = "https://himalayancircuit.com/images/map/Group%20277.png";
const HERO_URL = TRIP_HERO_IMAGES["ghorepani-poon-hill"];

export const FALLBACK_TRIP_GHOREPANI_POON_HILL: PublicTrip = {
  id: 3,
  slug: "ghorepani-poon-hill",
  title: "Ghorepani Poon Hill Trek",
  summary:
    "A gentle Annapurna circuit sampler: sunrise from Poon Hill at 3,210 m, lodge nights in Gurung villages like Ghorepani and Ghandruk, and big views of Dhaulagiri, Annapurna, and Machhapuchhre—ideal as a first multi-day trek.",
  description:
    "Ghorepani Poon Hill trekking is one of the most widely sought-after activities in Nepal. The Annapurna region offers immersive scenery, serene landscapes, and rich heritage for travellers who want more than adventure alone. Pokhara’s lakeside setting is a natural base—tranquil for rest, yet lively with paragliding, boating, and mountain views toward Machhapuchhre. From Nayapul the trail climbs through villages such as Tikhedhunga and Ghorepani, crossing forests, streams, and suspension bridges before the pre-dawn ascent to Poon Hill at 3,210 m for a full Himalayan panorama. The return via Ghandruk and Phedi completes a classic loop, with optional Kathmandu valley heritage at the end. Flying Kathmandu–Pokhara is among the most scenic short flights in the country.",
  durationDays: 8,
  tripType: "trekking_hiking",
  budgetLevel: "premium",
  comfortLevel: "basic",
  difficultyLevel: "easy",
  interestTags: [
    "ghorepani",
    "poon_hill",
    "annapurna",
    "pokhara",
    "ghandruk",
    "trekking",
    "sunrise",
    "gurung",
    "himalaya",
  ],
  priceFrom: { amount: "1399", currency: "USD" },
  imageUrl: HERO_URL,
  startingRegion: { slug: "kathmandu-valley", name: "Kathmandu Valley" },
  totalDistanceKm: 543,
  altitudeMaxM: 3210,
  altitudeMinM: 822,
  routeGrades: ["Grade A (an easy endeavour)"],
  fitnessNotes: ["Aerobic fitness"],
  recommendedSeasons: ["All year round"],
  mapImageUrl: MAP_URL,
  galleryImageUrls: [
    HERO_URL,
    "/images/trips/ghorepani-poon-hill/gallery-2511.jpeg",
    LOCATION_IMAGES.poonHill,
    LOCATION_IMAGES.ghandruk,
  ],
  sourceReferenceUrl:
    "https://himalayancircuit.com/tour/ghorepani-poonhill-trek-itinerary-price",
  priceTable: {
    currency: "USD",
    supplementaryChargePercent: 30,
    footnote:
      "Indicative per-person pricing for the services described in this offer. Cost varies with customization. International flights are not included.",
    columns: [
      { key: "2", label: "2 travellers" },
      { key: "4", label: "4 travellers" },
      { key: "8", label: "8 travellers" },
    ],
    rows: [
      {
        label: "Standard",
        prices: { "2": "1615", "4": "1519", "8": "1399" },
      },
      {
        label: "Deluxe",
        prices: { "2": "2247", "4": "2151", "8": "2031" },
      },
    ],
  },
  bookingFeeItems: [
    "T-shirt",
    "Annapurna Conservation Area fee",
    "Trekking permit",
    "Pre-departure guide",
    "Personal assistant",
  ],
  gearChecklist: [
    "Sleeping bag",
    "Backpack",
    "Hiking boots",
    "First-aid kit",
    "Travel towels",
    "Insect repellent",
    "Personal medicines",
    "Down jacket",
  ],
  trekkingGradeNotes:
    "Grade A is suitable for fit beginners: expect stone steps and steady climbs, but no extreme altitude. Poon Hill starts before dawn—dress warmly and pace the pre-sunrise walk.",
  faq: [
    {
      question: "What is the best season for trekking?",
      answer:
        "Short treks such as Ghorepani–Poon Hill can run in many seasons; spring and autumn usually offer the clearest sunrise views, while winter can be crisp and quiet on the ridge.",
    },
    {
      question: "Do I need vaccinations to enter Nepal?",
      answer:
        "No specific vaccinations are required for entry, but consult your doctor or a travel clinic before departure for personalised advice.",
    },
  ],
  reviewSnippets: [
    { name: "Christopher", location: "UK", date: "2026-04-20" },
    { name: "David", location: "Australia", date: "2026-04-09" },
    { name: "Mathis & Ida", location: "Germany", date: "2026-04-06" },
    { name: "Paul & Tim", location: "Germany", date: "2026-03-25" },
    { name: "Claudia", location: "Germany", date: "2026-03-18" },
  ],
  services: {
    included: [
      "Airport pickup and transfer to the hotel",
      "Double-room accommodations with breakfast in Kathmandu and Pokhara",
      "Entrance fees to cultural sites listed in the itinerary",
      "All city tours by private car",
      "English-speaking trekking guide",
      "All transportation in the destination area",
      "Tourist bus between Kathmandu and Pokhara (as per itinerary)",
      "English tour guide in Kathmandu",
      "Annapurna Conservation Area permit fees",
      "Ghorepani Poon Hill trekking permit",
      "TIMS card",
      "One porter for every two trekkers",
      "Full meals while trekking",
      "Airport drop-off",
      "All government taxes",
    ],
    excluded: [
      "Bar bills",
      "Natural calamities beyond our control and rescue expenses",
      "Travel / medical insurance",
      "International flights",
      "Nepal visa fees",
      "Lunch and dinner in Kathmandu and Pokhara (except where noted)",
      "Gratuity to staff",
    ],
    optional: [
      "Optional adventure activities in Pokhara (paragliding, ziplining, boating)",
      "Room upgrade or single supplement",
      "Extra nights in Kathmandu or Pokhara",
    ],
  },
  days: [
    {
      dayNumber: 1,
      title: "Arrival in Kathmandu and transfer to your hotel",
      description: "Welcome to Nepal",
      details:
        "After immigration our representative meets you at the airport and drives you to your hotel in central Kathmandu. Settle in after your journey; in the evening we outline the days ahead.",
      destinationName: "Kathmandu",
      distanceKm: 5,
      altitudeMaxM: 1400,
      altitudeMinM: 1400,
      durationHours: 0.5,
      accommodation: "Hotel",
      meals: "As arranged",
    },
    {
      dayNumber: 2,
      title: "Flight to Pokhara — Nayapul — trek to Tikhedhunga",
      description: "Start of the trail",
      details:
        "After breakfast a short flight brings you to Pokhara, where your trekking guide meets you for the drive to Nayapul (about 1.5 hours). You trek along the Modi Khola to Birethanti, then follow the Bhurungdi Khola through forest and rice terraces, climbing steadily via Hille to Tikhedhunga (1,570 m). Today is deliberately shorter for acclimatisation.",
      destinationName: "Tikhedhunga",
      distanceKm: 246,
      altitudeMaxM: 1480,
      altitudeMinM: 1400,
      durationHours: 6,
      accommodation: "Tea house / mountain lodge",
      meals: "Breakfast, lunch, dinner",
    },
    {
      dayNumber: 3,
      title: "Tikhedhunga to Ghorepani",
      description: "Rhododendron forest and Magar villages",
      details:
        "A full day of ascent—stone steps through Ulleri (2,070 m), a large Magar village, then gentler climbing in oak and rhododendron forest via Banthanti and Nangethanti to Ghorepani (2,840 m), with wide views of Annapurna, Nilgiri, and Dhaulagiri.",
      destinationName: "Ghorepani",
      distanceKm: 10,
      altitudeMaxM: 2874,
      altitudeMinM: 1480,
      durationHours: 7,
      accommodation: "Tea house / mountain lodge",
      meals: "Breakfast, lunch, dinner",
      imageUrl: ITINERARY_IMAGES.ghorepani,
    },
    {
      dayNumber: 4,
      title: "Poon Hill sunrise — trek to Ghandruk",
      description: "Classic panorama day",
      details:
        "You rise around 4 a.m. for Poon Hill (3,210 m)—among the finest viewpoints in Nepal, linking Dhaulagiri and Annapurna with Machhapuchhre, Nilgiri, Hiunchuli, and Annapurna South in one sweep. After sunrise and breakfast at Ghorepani the trail crosses rhododendron forest, the Deurali pass (3,160 m), and Tadapani before reaching the Gurung village of Ghandruk.",
      destinationName: "Ghandruk",
      distanceKm: 15,
      altitudeMaxM: 3210,
      altitudeMinM: 1940,
      durationHours: 7,
      accommodation: "Tea house / mountain lodge",
      meals: "Breakfast, lunch, dinner",
      imageUrl: ITINERARY_IMAGES.poonHill,
    },
    {
      dayNumber: 5,
      title: "Ghandruk to Phedi — drive to Pokhara",
      description: "End of trekking",
      details:
        "A steep descent through villages, terraces, and forest passes Dhampus to Phedi (about five hours on foot). Machhapuchhre, Annapurna South, Lamjung Himal, and Annapurna III frame the valley on the way down. You drive back to Pokhara for a free lakeside afternoon.",
      destinationName: "Pokhara",
      distanceKm: 44,
      altitudeMaxM: 1940,
      altitudeMinM: 822,
      durationHours: 6,
      accommodation: "Hotel",
      meals: "Breakfast",
    },
    {
      dayNumber: 6,
      title: "Drive from Pokhara to Kathmandu",
      description: "Return to the valley",
      details:
        "An early tourist bus (around 7:30) heads east to Kathmandu; mountain roads and traffic can lengthen the journey, so expect arrival in the late afternoon and a quiet evening at the hotel.",
      destinationName: "Kathmandu",
      distanceKm: 200,
      altitudeMaxM: 1400,
      altitudeMinM: 822,
      durationHours: 7,
      accommodation: "Hotel",
      meals: "Breakfast",
    },
    {
      dayNumber: 7,
      title: "Cultural sightseeing in Kathmandu",
      description: "Heritage after the trek",
      details:
        "Pashupatinath on the Bagmati River, Kathmandu Durbar Square with the Kumari shrine, and Swayambhunath (Monkey Temple)—365 steps to a stupa with sweeping valley views. The evening may include a traditional Nepali dinner with cultural music and dance.",
      destinationName: "Kathmandu",
      distanceKm: 13,
      altitudeMaxM: 1400,
      altitudeMinM: 1400,
      durationHours: 5,
      accommodation: "Hotel",
      meals: "Breakfast",
      imageUrl: ITINERARY_IMAGES.swayambhunath,
    },
    {
      dayNumber: 8,
      title: "Boudhanath and departure",
      description: "Farewell to Nepal",
      details:
        "Before your flight, visit Boudhanath—one of the world’s largest stupas at 36 m, ringed with prayer wheels and Buddha images. From the calm of the mandala you transfer to the airport for your journey home.",
      destinationName: "Kathmandu",
      distanceKm: 10,
      altitudeMaxM: 1400,
      altitudeMinM: 1400,
      durationHours: 3,
      accommodation: "Hotel",
      meals: "Breakfast",
      imageUrl: ITINERARY_IMAGES.boudha,
    },
  ],
};
