import type { PublicTrip } from "@/types/trip";
import { ITINERARY_IMAGES, LOCATION_IMAGES, TRIP_HERO_IMAGES } from "@/lib/trip-images";

const MAP_URL = "https://himalayancircuit.com/images/map/Group%20277.png";
const HERO_URL = TRIP_HERO_IMAGES["kathmandu-pokhara-chitwan-experience-nepal"];

export const FALLBACK_TRIP_KATHMANDU_POKHARA_CHITWAN_EXPERIENCE_NEPAL: PublicTrip = {
  id: 10,
  slug: "kathmandu-pokhara-chitwan-experience-nepal",
  title: "Kathmandu Pokhara Chitwan Experience Nepal",
  summary:
    "Fourteen days through Kathmandu’s UNESCO heritage, Chitwan jungle safaris and Tharu culture, Bandipur and Pokhara’s lakes, then Bhaktapur, Nagarkot, Panauti, and Namo Buddha—Nepal’s classic triangle in one experiential tour.",
  description:
    "Nepal welcomes you with Himalayan views, ancient culture, and warm hospitality. This experiential journey links Kathmandu’s UNESCO World Heritage sites—Patan, Swayambhunath, Bhaktapur, and living Newar towns—with Chitwan National Park’s rhinos, tigers, and jeep safaris, the hill town of Bandipur, Pokhara’s Sarangkot sunrises and Phewa Lake, Tibetan refugee settlements, Nagarkot ridges, historic Panauti, and peaceful Namo Buddha monastery. Expect Tharu dance, oxcart rides, Siddha Cave, pottery squares, and panoramic views from Dhaulagiri to Everest. Hotels and a monastery stay blend comfort with authentic encounters across the Kathmandu Valley, Terai jungle, and Annapurna foothills.",
  durationDays: 14,
  tripType: "cultural_heritage",
  budgetLevel: "premium",
  comfortLevel: "standard",
  difficultyLevel: "easy",
  interestTags: [
    "kathmandu",
    "pokhara",
    "chitwan",
    "culture",
    "wildlife",
    "heritage",
    "newar",
    "safari",
    "lakes",
    "nagarkot",
  ],
  priceFrom: { amount: "1400", currency: "USD" },
  imageUrl: HERO_URL,
  startingRegion: { slug: "kathmandu-valley", name: "Kathmandu Valley" },
  totalDistanceKm: 720,
  altitudeMaxM: 2100,
  altitudeMinM: 415,
  routeGrades: ["Grade A (an easy endeavour)"],
  fitnessNotes: ["Aerobic fitness"],
  recommendedSeasons: ["All year round"],
  mapImageUrl: MAP_URL,
  galleryImageUrls: [
    HERO_URL,
    LOCATION_IMAGES.boudha,
    LOCATION_IMAGES.chitwanSafari,
    LOCATION_IMAGES.phewaLake,
    LOCATION_IMAGES.bandipur,
  ],
  sourceReferenceUrl:
    "https://himalayancircuit.com/tour/experiential-nepal-tour",
  priceTable: {
    currency: "USD",
    supplementaryChargePercent: 30,
    footnote:
      "Indicative per-person pricing for the services described in this offer. Cost varies with customization. International flights are not included. Deluxe package includes domestic flights as per itinerary.",
    columns: [
      { key: "2", label: "2 travellers" },
      { key: "4", label: "4 travellers" },
      { key: "8", label: "8 travellers" },
    ],
    rows: [
      {
        label: "Standard",
        prices: { "2": "2000", "4": "1800", "8": "1400" },
      },
      {
        label: "Deluxe",
        prices: { "2": "2200", "4": "1900", "8": "1678" },
      },
    ],
  },
  bookingFeeItems: [
    "Umbrella",
    "Local village exploration",
    "T-shirt",
    "Entrance fees",
  ],
  gearChecklist: [
    "Backpack",
    "T-shirts",
    "First-aid kit",
    "Quick-dry T-shirts",
    "Sandals",
    "Rain jacket",
    "Plug adapter (if needed)",
    "Travel towels",
    "Sunglasses / sun hat",
    "Sun block",
    "Lip balm",
    "Personal medicines",
    "Neutral clothing for temples and monastery visits",
  ],
  trekkingGradeNotes:
    "This is a cultural and wildlife tour with short walks and drives—no high-altitude trekking. Light layers work for Chitwan heat and Nagarkot mornings.",
  faq: [
    {
      question: "What currency is used in Nepal?",
      answer:
        "The Nepalese Rupee (NPR) is official. ATMs are available in Kathmandu and Pokhara; carry cash for smaller towns and tips.",
    },
    {
      question: "Do I need travel insurance?",
      answer:
        "Travel insurance is strongly recommended, including medical cover and evacuation, especially for jungle activities and domestic flights on deluxe packages.",
    },
  ],
  reviewSnippets: [
    { name: "Christopher", location: "UK", date: "2026-04-20" },
    { name: "David", location: "Australia", date: "2026-04-09" },
    { name: "Mathis & Ida", location: "Germany", date: "2026-04-06" },
    { name: "Paul & Tim", location: "Germany", date: "2026-03-25" },
    { name: "Claudia", location: "Germany", date: "2026-03-18" },
  ],
  services: {
    included: [
      "Hotel accommodation with breakfast",
      "Private vehicle for ground transportation including airport transfers",
      "Domestic flights as per itinerary (Deluxe package)",
      "Tourist coach for long transfers (Standard package)",
      "Private guide on excursions",
      "Entrance and monument visit fees",
      "Wildlife activities as per itinerary",
      "Breakfast and dinner at monastery stay",
      "All meals in Chitwan",
      "All government taxes",
    ],
    excluded: [
      "International airfare and visa",
      "Travel medical insurance",
      "Drinks and private expenses",
      "Lunch and dinner except Chitwan and monastery dinners",
      "Single supplementary charge",
      "Natural calamities beyond our control and rescue expenses",
      "Gratuity to staff",
    ],
    optional: [
      "Deluxe package with domestic flights",
      "Extra nights in Kathmandu",
      "Everest mountain flight from Kathmandu",
    ],
  },
  days: [
    {
      dayNumber: 1,
      title: "Welcome to Kathmandu",
      description: "Arrival",
      details:
        "Meet at Tribhuvan International Airport and transfer to your hotel in Kathmandu. Rest after your flight—we are on hand to help you enjoy Nepal.",
      destinationName: "Kathmandu",
      distanceKm: 5,
      altitudeMaxM: 1400,
      altitudeMinM: 1400,
      durationHours: 0.5,
      accommodation: "Hotel",
      meals: "As arranged",
    },
    {
      dayNumber: 2,
      title: "Patan Durbar Square and Swayambhunath",
      description: "Living heritage",
      details:
        "Walk Patan’s alleys, Krishna temple, palace courtyards, and crafts workshops, then visit Swayambhunath (Monkey Temple) for valley panoramas and prayer wheels.",
      destinationName: "Kathmandu",
      distanceKm: 10,
      altitudeMaxM: 1400,
      altitudeMinM: 1400,
      durationHours: 6,
      accommodation: "Hotel",
      meals: "Breakfast",
      imageUrl: ITINERARY_IMAGES.swayambhunath,
    },
    {
      dayNumber: 3,
      title: "Kathmandu to Chitwan — Meghauli",
      description: "Into the Terai",
      details:
        "Fly or drive to Chitwan, jeep to Meghauli, sunset on the Narayani River, and an evening Tharu cultural dance with traditional dress and village walk.",
      destinationName: "Chitwan",
      distanceKm: 181,
      altitudeMaxM: 415,
      altitudeMinM: 1400,
      durationHours: 6,
      accommodation: "Hotel",
      meals: "Breakfast, lunch, dinner",
      imageUrl: ITINERARY_IMAGES.chitwanSafari,
    },
    {
      dayNumber: 4,
      title: "Chitwan National Park wildlife",
      description: "Birds and forest",
      details:
        "Forest bird watching, oxcart ride through villages, and time with naturalist guides—dinner at the lodge.",
      destinationName: "Chitwan",
      distanceKm: 20,
      altitudeMaxM: 415,
      altitudeMinM: 415,
      durationHours: 5,
      accommodation: "Hotel",
      meals: "Breakfast, lunch, dinner",
    },
    {
      dayNumber: 5,
      title: "Jeep safari — tiger tracing",
      description: "Jungle safari day",
      details:
        "Jeep safari through Chitwan National Park for rhinos, deer, elephants, and with luck tigers, plus a wilderness meal with naturalist guides.",
      destinationName: "Chitwan",
      distanceKm: 20,
      altitudeMaxM: 415,
      altitudeMinM: 415,
      durationHours: 5,
      accommodation: "Hotel",
      meals: "Breakfast, lunch, dinner",
    },
    {
      dayNumber: 6,
      title: "Drive Chitwan to Bandipur",
      description: "Hilltop Newar town",
      details:
        "Scenic drive to Bandipur’s preserved Newari architecture and Himalayan views, with a visit to Siddha Gufa—Nepal’s largest cave.",
      destinationName: "Bandipur",
      distanceKm: 101,
      altitudeMaxM: 1030,
      altitudeMinM: 415,
      durationHours: 4,
      accommodation: "Hotel",
      meals: "Breakfast",
      imageUrl: LOCATION_IMAGES.bandipur,
    },
    {
      dayNumber: 7,
      title: "Bandipur to Sarangkot — Pokhara sunset",
      description: "Lake city views",
      details:
        "Drive to Sarangkot (about 1,600 m) for panoramic Pokhara Valley views and a memorable sunset over the Annapurna range.",
      destinationName: "Sarangkot",
      distanceKm: 86,
      altitudeMaxM: 1600,
      altitudeMinM: 822,
      durationHours: 4,
      accommodation: "Hotel",
      meals: "Breakfast",
      imageUrl: ITINERARY_IMAGES.sarangkot,
    },
    {
      dayNumber: 8,
      title: "Sarangkot sunrise — Pokhara city tour",
      description: "Phewa Lake and falls",
      details:
        "Dawn over Annapurna, Dhaulagiri, and Machhapuchhre from Sarangkot, then Pokhara lakeside, boat to Tal Barahi temple, Devi’s Fall, and Gupteshwor Cave.",
      destinationName: "Pokhara",
      distanceKm: 20,
      altitudeMaxM: 1600,
      altitudeMinM: 822,
      durationHours: 4,
      accommodation: "Hotel",
      meals: "Breakfast",
      imageUrl: ITINERARY_IMAGES.phewaLake,
    },
    {
      dayNumber: 9,
      title: "Tibetan refugee camp — Pokhara",
      description: "Cultural encounter",
      details:
        "Visit a Tibetan settlement to learn about refugee life and history, followed by Nepali cuisine at a local restaurant.",
      destinationName: "Pokhara",
      distanceKm: 20,
      altitudeMaxM: 822,
      altitudeMinM: 822,
      durationHours: 3,
      accommodation: "Hotel",
      meals: "Breakfast",
    },
    {
      dayNumber: 10,
      title: "Fly to Kathmandu — Bhaktapur — Nagarkot",
      description: "Medieval city and hill station",
      details:
        "Flight to Kathmandu, guided Bhaktapur Durbar Square tour, optional pottery square experience, then drive to Nagarkot for hilltop sunset.",
      destinationName: "Nagarkot",
      distanceKm: 201,
      altitudeMaxM: 2100,
      altitudeMinM: 1400,
      durationHours: 7,
      accommodation: "Hotel",
      meals: "Breakfast",
    },
    {
      dayNumber: 11,
      title: "Nagarkot sunrise and village hike",
      description: "Ridge views",
      details:
        "Morning views from Nagarkot tower and a short village hike through rice fields and quiet hill country.",
      destinationName: "Nagarkot",
      distanceKm: 9,
      altitudeMaxM: 2100,
      altitudeMinM: 2100,
      durationHours: 2,
      accommodation: "Hotel",
      meals: "Breakfast",
    },
    {
      dayNumber: 12,
      title: "Nagarkot to Panauti — Namo Buddha",
      description: "Oldest towns and monastery",
      details:
        "Drive to historic Panauti’s temples and alleys, then continue to Namo Buddha for dinner at the monastery.",
      destinationName: "Namo Buddha",
      distanceKm: 40,
      altitudeMaxM: 1750,
      altitudeMinM: 1400,
      durationHours: 5,
      accommodation: "Monastery",
      meals: "Breakfast, dinner",
    },
    {
      dayNumber: 13,
      title: "Namo Buddha Monastery",
      description: "Buddhist immersion",
      details:
        "Morning worship session, prayer wheels, hilltop art, and interaction with monks to learn about Buddhist principles. Breakfast and dinner at the monastery.",
      destinationName: "Namo Buddha",
      distanceKm: 10,
      altitudeMaxM: 1750,
      altitudeMinM: 1750,
      durationHours: 2,
      accommodation: "Monastery",
      meals: "Breakfast, dinner",
    },
    {
      dayNumber: 14,
      title: "Departure from Kathmandu",
      description: "Farewell",
      details:
        "Checkout by noon after breakfast, then private transfer to the airport for your onward journey.",
      destinationName: "Kathmandu",
      distanceKm: 32,
      altitudeMaxM: 1400,
      altitudeMinM: 1400,
      durationHours: 2,
      accommodation: "Hotel",
      meals: "Breakfast",
    },
  ],
};
