import type { PublicTrip } from "@/types/trip";
import { ITINERARY_IMAGES, LOCATION_IMAGES, TRIP_HERO_IMAGES } from "@/lib/trip-images";

const MAP_URL = "https://himalayancircuit.com/images/map/Group%20277.png";
const HERO_URL = TRIP_HERO_IMAGES["mardi-himal-base-camp-trek"];

export const FALLBACK_TRIP_MARDI_HIMAL_BASE_CAMP_TREK: PublicTrip = {
  id: 19,
  slug: "mardi-himal-base-camp-trek",
  title: "Mardi Himal Base Camp Trek",
  summary:
    "Twelve days to Mardi Himal Base Camp at 4,500 m along a quiet Annapurna ridgeline: rhododendron forest, High Camp sunrises, and close views of Machhapuchhre, Annapurna South, and Hiunchuli—a calmer alternative to ABC.",
  description:
    "The Mardi Himal Trek is a popular moderate route in Nepal’s Annapurna region, known for spectacular views of Mardi Himal, Machhapuchhre (Fishtail), Annapurna South, and Hiunchuli. It offers a quieter alternative to the Annapurna Base Camp trek, with peaceful rhododendron forests, authentic teahouses, and dramatic ridgeline walking. Trekkers hike a narrow crest flanked by the Annapurna and Dhaulagiri massifs to the west and Machhapuchhre and Manaslu to the east, with the Mardi Himal range behind. Budding photographers enjoy unobstructed summit views. From Pokhara via Phedi and Pothana, the trail branches off the main circuit through Forest Camp and High Camp to base camp—ideal for beginners and experienced walkers seeking a shorter Himalayan immersion.",
  durationDays: 12,
  tripType: "trekking_hiking",
  budgetLevel: "premium",
  comfortLevel: "basic",
  difficultyLevel: "challenging",
  interestTags: [
    "mardi_himal",
    "annapurna",
    "machhapuchhre",
    "pokhara",
    "trekking",
    "ridgeline",
    "rhododendron",
    "himalaya",
  ],
  priceFrom: { amount: "1469", currency: "USD" },
  imageUrl: HERO_URL,
  startingRegion: { slug: "kathmandu-valley", name: "Kathmandu Valley" },
  totalDistanceKm: 537,
  altitudeMaxM: 4500,
  altitudeMinM: 822,
  routeGrades: ["Grade C (difficult)"],
  fitnessNotes: ["Strength", "Stamina"],
  recommendedSeasons: ["Autumn", "Spring"],
  mapImageUrl: MAP_URL,
  galleryImageUrls: [
    HERO_URL,
    LOCATION_IMAGES.mardiHimal,
    LOCATION_IMAGES.mardiHighCamp,
    LOCATION_IMAGES.australianCamp,
  ],
  sourceReferenceUrl:
    "https://himalayancircuit.com/tour/mardi-himal-base-camp-trek",
  priceTable: {
    currency: "USD",
    supplementaryChargePercent: 30,
    footnote:
      "Indicative per-person pricing for the services described in this offer. Cost varies with customization. International flights are not included.",
    columns: [
      { key: "2", label: "2 travellers" },
      { key: "4", label: "4 travellers" },
      { key: "8", label: "8 travellers" },
    ],
    rows: [
      {
        label: "Standard",
        prices: { "2": "1665", "4": "1600", "8": "1469" },
      },
      {
        label: "Deluxe",
        prices: { "2": "1990", "4": "1900", "8": "1729" },
      },
    ],
  },
  bookingFeeItems: [
    "T-shirt",
    "Annapurna Conservation Area fee",
    "Trekking permit",
    "Pre-departure guide",
    "Personal assistant",
  ],
  gearChecklist: [
    "Sleeping bag",
    "Hiking boots",
    "Socks",
    "Thermals",
    "T-shirts",
    "First-aid kit",
    "Travel towels",
    "Sunglasses / sun hat",
    "Lip balm",
    "Insect repellent",
    "Personal medicines",
    "Down jacket",
    "Rain jacket",
    "Backpack",
  ],
  trekkingGradeNotes:
    "Grade C includes steep forest climbs, High Camp altitude, and a rocky approach to Mardi Himal Base Camp. Allow time to acclimatise and discuss pace with your guide.",
  faq: [
    {
      question: "Is Nepal a safe destination for tourists?",
      answer:
        "Nepal is generally peaceful and welcoming. Use normal travel caution and follow your guide’s advice on trail and weather conditions, especially above High Camp.",
    },
    {
      question: "What about Nepal visa information?",
      answer:
        "Tribhuvan International Airport in Kathmandu is Nepal’s main international gateway. Visa on arrival is available for most nationalities—confirm requirements for your passport before travel.",
    },
  ],
  reviewSnippets: [
    { name: "Christopher", location: "UK", date: "2026-04-20" },
    { name: "David", location: "Australia", date: "2026-04-09" },
    { name: "Mathis & Ida", location: "Germany", date: "2026-04-06" },
    { name: "Paul & Tim", location: "Germany", date: "2026-03-25" },
    { name: "Claudia", location: "Germany", date: "2026-03-18" },
  ],
  services: {
    included: [
      "Airport pickup and transfer to the hotel",
      "Double-room accommodations with breakfast in Kathmandu and Pokhara",
      "Entrance fees to cultural sites listed in the itinerary",
      "All city tours by private car",
      "English-speaking trekking guide",
      "All transportation in the destination area",
      "Tourist bus between Kathmandu and Pokhara",
      "English tour guide in Kathmandu",
      "Annapurna Conservation Area permit fees",
      "TIMS card",
      "One porter for every two trekkers",
      "Full meals while trekking",
      "Airport drop-off",
      "All government taxes",
    ],
    excluded: [
      "Bar bills",
      "Natural calamities beyond our control and rescue expenses",
      "Travel / medical insurance",
      "International flights",
      "Nepal visa fees",
      "Lunch and dinner in Kathmandu and Pokhara (except where noted)",
      "Gratuity to staff",
    ],
    optional: [
      "Paragliding, boating, or other Pokhara activities on the free day",
      "Room upgrade or single supplement",
      "Extra nights in Kathmandu or Pokhara",
    ],
  },
  days: [
    {
      dayNumber: 1,
      title: "Arrival in Kathmandu and transfer to your hotel",
      description: "Welcome to Nepal",
      details:
        "After landing at Kathmandu Airport our representative meets you and drives you to your hotel. The evening is free to explore the lively streets of Thamel.",
      destinationName: "Kathmandu",
      distanceKm: 5,
      altitudeMaxM: 1400,
      altitudeMinM: 1400,
      durationHours: 0.5,
      accommodation: "Hotel",
      meals: "As arranged",
    },
    {
      dayNumber: 2,
      title: "Tour of Boudhanath and Pashupatinath",
      description: "Sacred Kathmandu",
      details:
        "Visit Boudhanath, one of the world’s largest stupas at 36 m, with prayer wheels and Buddha images encircling the mandala. Continue to Pashupatinath on the Bagmati River—Nepal’s revered Shiva temple where Hindu cremation rites offer a profound view of life’s cycle.",
      destinationName: "Kathmandu",
      distanceKm: 14,
      altitudeMaxM: 1400,
      altitudeMinM: 1400,
      durationHours: 6,
      accommodation: "Hotel",
      meals: "Breakfast",
      imageUrl: ITINERARY_IMAGES.boudha,
    },
    {
      dayNumber: 3,
      title: "Drive from Kathmandu to Pokhara",
      description: "Into the lake city",
      details:
        "A scenic drive of about six to seven hours (with lunch en route) brings you to Pokhara, Nepal’s second-largest city—gateway to treks, lakes, paragliding, and wide Himalayan views.",
      destinationName: "Pokhara",
      distanceKm: 200,
      altitudeMaxM: 1400,
      altitudeMinM: 820,
      durationHours: 7,
      accommodation: "Hotel",
      meals: "Breakfast",
    },
    {
      dayNumber: 4,
      title: "Pokhara — Phedi — trek to Pothana",
      description: "Australian Camp views",
      details:
        "Drive to Phedi and trek through Gurung villages including Dhampus toward Australian Camp, then on to Pothana—an Annapurna Circuit trailhead—with sweeping views of Annapurna and Machhapuchhre.",
      destinationName: "Pothana",
      distanceKm: 37,
      altitudeMaxM: 1900,
      altitudeMinM: 822,
      durationHours: 6,
      accommodation: "Tea house / mountain lodge",
      meals: "Breakfast, lunch, dinner",
    },
    {
      dayNumber: 5,
      title: "Trek from Pothana to Forest Camp",
      description: "Off the main circuit",
      details:
        "The trail briefly follows the Annapurna Circuit route, then branches east on a quieter path to Forest Camp. Watch for wildlife—monkeys, deer, birds—and enjoy Dhaulagiri and Annapurna views before camp.",
      destinationName: "Forest Camp",
      distanceKm: 11,
      altitudeMaxM: 2550,
      altitudeMinM: 1900,
      durationHours: 5,
      accommodation: "Tea house / mountain lodge",
      meals: "Breakfast, lunch, dinner",
    },
    {
      dayNumber: 6,
      title: "Trek from Forest Camp to High Camp",
      description: "Rhododendron and juniper",
      details:
        "A steep climb through rhododendron and juniper forest leads to High Camp (3,580 m), with rewarding views of Machhapuchhre, the Annapurna range, the ABC valley, and Mardi Himal ahead.",
      destinationName: "High Camp",
      distanceKm: 8,
      altitudeMaxM: 3580,
      altitudeMinM: 2550,
      durationHours: 4,
      accommodation: "Tea house / mountain lodge",
      meals: "Breakfast, lunch, dinner",
      imageUrl: LOCATION_IMAGES.mardiHighCamp,
    },
    {
      dayNumber: 7,
      title: "Trek from High Camp to Mardi Himal Base Camp",
      description: "Summit day",
      details:
        "Pre-dawn start for sunrise at High Camp, then a demanding rocky ascent to Mardi Himal Base Camp at 4,500 m—danphe (Himalayan monal) may appear as the giants of the Annapurna massif fill the horizon.",
      destinationName: "Mardi Himal Base Camp",
      distanceKm: 6,
      altitudeMaxM: 4500,
      altitudeMinM: 3580,
      durationHours: 4,
      accommodation: "Tea house / mountain lodge",
      meals: "Breakfast, lunch, dinner",
      imageUrl: ITINERARY_IMAGES.mardiHimal,
    },
    {
      dayNumber: 8,
      title: "Trek from Mardi Himal Base Camp to Siding",
      description: "Long descent",
      details:
        "Having reached your goal, descend about six to seven hours to Siding (1,900 m), a beautiful village offering an authentic taste of rural Nepal on your last full day in the hills.",
      destinationName: "Siding",
      distanceKm: 14,
      altitudeMaxM: 4500,
      altitudeMinM: 1900,
      durationHours: 6,
      accommodation: "Tea house / mountain lodge",
      meals: "Breakfast, lunch, dinner",
    },
    {
      dayNumber: 9,
      title: "Trek Siding to Lumre — drive to Pokhara",
      description: "End of trekking",
      details:
        "Walk to Lumre and drive to Pokhara for rest, refreshment, and farewell to your trekking crew after days on the ridge.",
      destinationName: "Pokhara",
      distanceKm: 37,
      altitudeMaxM: 1700,
      altitudeMinM: 822,
      durationHours: 3,
      accommodation: "Hotel",
      meals: "Breakfast",
    },
    {
      dayNumber: 10,
      title: "Free day in Pokhara",
      description: "Lakeside leisure",
      details:
        "A full free day: stroll Phewa Lake, paraglide over the city, boat to Tal Barahi temple, or visit Devi’s Fall, Bat Cave, Mahendra Cave, and the Tibetan refugee settlement—with Machhapuchhre reflected on still water.",
      destinationName: "Pokhara",
      distanceKm: 0,
      altitudeMaxM: 822,
      altitudeMinM: 822,
      durationHours: 0,
      accommodation: "Hotel",
      meals: "Breakfast",
    },
    {
      dayNumber: 11,
      title: "Drive back to Kathmandu",
      description: "Return to the capital",
      details:
        "After breakfast, drive to Kathmandu. A farewell dinner with traditional Nepali food, dance, and music closes the journey.",
      destinationName: "Kathmandu",
      distanceKm: 200,
      altitudeMaxM: 1400,
      altitudeMinM: 822,
      durationHours: 7,
      accommodation: "Hotel",
      meals: "Breakfast",
    },
    {
      dayNumber: 12,
      title: "Departure from Kathmandu",
      description: "Farewell to the Himalaya",
      details:
        "Airport transfer for your flight home—we hope you carry sweet memories of Mardi Himal, Nepal’s forests, and its welcoming people.",
      destinationName: "Kathmandu",
      distanceKm: 5,
      altitudeMaxM: 1400,
      altitudeMinM: 1400,
      durationHours: 0.5,
      accommodation: "Hotel",
      meals: "Breakfast",
    },
  ],
};
