import type { PublicTrip } from "@/types/trip";

const MAP_URL = "https://himalayancircuit.com/images/map/Group%20277.png";
const HERO_URL =
  "https://himalayancircuit.com/storage/media/monk-for-a-month.webp";

export const FALLBACK_TRIP_MONK_FOR_A_MONTH_NEPAL: PublicTrip = {
  id: 27,
  slug: "monk-for-a-month-nepal",
  title: "Monk for a Month Nepal",
  summary:
    "Nineteen days of Buddhist teaching, monastery stays, UNESCO heritage in Kathmandu, Chitwan jungle, Lumbini’s sacred garden, Pokhara lakes, and Sarangkot sunrise—with meditation classes led by Khempos.",
  description:
    "Monk for a Month Nepal is a pilgrimage and experiential tour through Nepal’s tranquil landscapes and living Buddhist culture. As the birthplace of Lord Buddha, the country blends Hinduism and Buddhism at sites from Kathmandu Durbar Square to Swayambhunath and Boudhanath. A four-day introductory course with Khempos—monks who have completed twenty-one years of study—covers Buddhist philosophy and meditation, followed by three nights in a monastery. The journey continues to Chitwan National Park for jungle activities, Lumbini’s Maya Devi Temple and Ashoka pillar, Pokhara’s lake city and Sarangkot sunrise over Machhapuchhre, and Pharping’s Padmasambhava caves before a farewell dinner in Kathmandu. Hotel and monastery accommodation, valley tours, and Himalayan views offer spiritual depth and Nepal’s cultural diversity in one paced itinerary.",
  durationDays: 19,
  tripType: "spiritual_pilgrimage",
  budgetLevel: "premium",
  comfortLevel: "standard",
  difficultyLevel: "easy",
  interestTags: [
    "spiritual_pilgrimage",
    "buddhism",
    "meditation",
    "monastery",
    "lumbini",
    "chitwan",
    "pokhara",
    "culture",
    "heritage",
    "experiential",
  ],
  priceFrom: { amount: "2743", currency: "USD" },
  imageUrl: HERO_URL,
  startingRegion: { slug: "kathmandu-valley", name: "Kathmandu Valley" },
  totalDistanceKm: 656,
  altitudeMaxM: 1400,
  altitudeMinM: 150,
  routeGrades: ["Grade A (an easy endeavour)"],
  fitnessNotes: ["Aerobic fitness"],
  recommendedSeasons: ["All year round"],
  mapImageUrl: MAP_URL,
  galleryImageUrls: [
    HERO_URL,
    "https://himalayancircuit.com/storage/media/Boudhanath-Half-Day-Tour.webp",
    "https://himalayancircuit.com/storage/media/Swayambhuanath-Stupa.webp",
    MAP_URL,
  ],
  sourceReferenceUrl:
    "https://himalayancircuit.com/tour/monk-for-a-month-nepal",
  priceTable: {
    currency: "USD",
    supplementaryChargePercent: 30,
    footnote:
      "Indicative per-person pricing for the services described in this offer. Cost varies with customization. International flights are not included.",
    columns: [
      { key: "2", label: "2 travellers" },
      { key: "4", label: "4 travellers" },
      { key: "8", label: "8 travellers" },
    ],
    rows: [
      {
        label: "Standard",
        prices: { "2": "2959", "4": "2863", "8": "2743" },
      },
      {
        label: "Deluxe",
        prices: { "2": "3976", "4": "3880", "8": "3760" },
      },
    ],
  },
  bookingFeeItems: [
    "T-shirt",
    "Entrance fee",
    "Spiritual practices",
    "Learn Buddhism",
  ],
  gearChecklist: [
    "Backpack",
    "First-aid kit",
    "Easy-dry T-shirts",
    "Sandals",
    "Rain jacket",
    "Plug adapter (if needed)",
    "Travel towels",
    "Sunglasses / sun hat",
    "Sun block",
    "Lip balm",
    "Personal medicines",
    "T-shirts",
    "Modest clothing for monastery and temple visits",
  ],
  trekkingGradeNotes:
    "A pilgrimage and cultural tour with short walks and overland drives—no high-altitude trekking. Modest dress is appreciated at temples and during monastery stays.",
  faq: [
    {
      question: "What should I pack for my trip to Nepal?",
      answer:
        "Pack layers for valley, Terai, and lakeside climates, comfortable walking shoes, rain gear, sun protection, and personal medicines. Monastery stays may be cooler in the evenings.",
    },
    {
      question: "When is the best time to travel to Nepal?",
      answer:
        "Autumn (September–November) and spring (March–May) offer clear skies and mild temperatures. This tour runs year-round with comfortable sightseeing conditions.",
    },
  ],
  reviewSnippets: [
    { name: "Christopher", location: "UK", date: "2026-04-20" },
    { name: "David", location: "Australia", date: "2026-04-09" },
    { name: "Mathis & Ida", location: "Germany", date: "2026-04-06" },
    { name: "Paul & Tim", location: "Germany", date: "2026-03-25" },
    { name: "Claudia", location: "Germany", date: "2026-03-18" },
  ],
  services: {
    included: [
      "Airport pickup and transfers by vehicle as described in the itinerary",
      "Accommodation in Kathmandu, Lumbini, and Pokhara including breakfast in twin-sharing room",
      "Kathmandu city tours inclusive of permits, vehicle transfer, and professional English-speaking tour guide",
      "Entrance fees for above-mentioned places",
      "Three meals a day at Chitwan",
      "Most meals in monastery",
      "Land transportation (tourist bus or private vehicle)",
      "Government taxes",
    ],
    excluded: [
      "Alcoholic drinks, hot water, cold drinks, laundry, phone calls, and internet",
      "Travel insurance, accident or health emergency, evacuation, loss, theft, or damage to baggage and personal effects",
      "Costs arising from unforeseen events beyond our control",
      "Lunch and dinner in Kathmandu, Lumbini, and Pokhara",
      "Single supplementary charge US $450",
      "Tips and gratuities",
    ],
    optional: [
      "Deluxe package upgrades",
      "Paragliding, zip flyer, or skydiving in Pokhara",
      "Extra nights in Kathmandu or Pokhara",
    ],
  },
  days: [
    {
      dayNumber: 1,
      title: "Arrival in Kathmandu",
      description: "Welcome to the city of temples",
      details:
        "After arrival at the airport, our representative welcomes you and transfers you to your hotel in the heart of the city. Explore vibrant Thamel’s restaurants, cafés, and shops, or rest after your long journey.",
      destinationName: "Kathmandu",
      distanceKm: 15,
      altitudeMaxM: 1400,
      altitudeMinM: 1400,
      durationHours: 0.5,
      accommodation: "Hotel",
      meals: "Breakfast",
    },
    {
      dayNumber: 2,
      title: "Orientation and Swayambhunath (Monkey Temple)",
      description: "Hilltop stupa and valley views",
      details:
        "Visit Swayambhunath atop its hill—a hallmark of faith and harmony where Buddhists and Hindus gather. Climb 365 stone steps to Nepal’s oldest stupa for panoramic views over Kathmandu; troops of monkeys share the sacred site.",
      destinationName: "Kathmandu",
      distanceKm: 4,
      altitudeMaxM: 1400,
      altitudeMinM: 1400,
      durationHours: 4,
      accommodation: "Hotel",
      meals: "Breakfast",
    },
    {
      dayNumber: 3,
      title: "Kathmandu Durbar Square",
      description: "Living goddess and Malla craft",
      details:
        "Explore Kathmandu Durbar Square, once a royal palace and now home to the living goddess Kumari. Among three valley durbar squares, this UNESCO site holds ancient temples, palaces, and a nine-storey pagoda palace with superb valley views and 14th-century woodcraft.",
      destinationName: "Kathmandu",
      distanceKm: 2,
      altitudeMaxM: 1400,
      altitudeMinM: 1400,
      durationHours: 3,
      accommodation: "Hotel",
      meals: "Breakfast",
    },
    {
      dayNumber: 4,
      title: "Buddhism teaching class and Boudhanath",
      description: "First day of four-day course",
      details:
        "Arrive at the monastery at 9:45 for an introductory class with a Khempo from 10:00–12:00. After lunch, visit Boudhanath—the world’s largest stupa at 36 m—with prayer wheels and 108 Buddha images. Walk the kora around the mandala before returning to your hotel. Buddhism teaching continues 1.5 hours daily for four days.",
      destinationName: "Kathmandu",
      distanceKm: 6,
      altitudeMaxM: 1400,
      altitudeMinM: 1400,
      durationHours: 7,
      accommodation: "Hotel",
      meals: "Breakfast",
    },
    {
      dayNumber: 5,
      title: "Buddhism class and Pashupatinath",
      description: "Sacred river and cremation rites",
      details:
        "Morning teaching at the monastery, then Pashupatinath—among the world’s most revered Hindu temples on the Bagmati River, listed as UNESCO heritage. Gilt roofs, carved silver doors, and open cremation ghats offer a profound view of life’s cycle.",
      destinationName: "Kathmandu",
      distanceKm: 5,
      altitudeMaxM: 1400,
      altitudeMinM: 1400,
      durationHours: 6,
      accommodation: "Hotel",
      meals: "Breakfast",
    },
    {
      dayNumber: 6,
      title: "Buddhism class — free time",
      description: "Reflection in the valley",
      details:
        "Morning monastery class from 10:00–12:00, lunch break, then free time from 2:00 pm to explore Kathmandu at your own pace before returning to the hotel.",
      destinationName: "Kathmandu",
      distanceKm: 0,
      altitudeMaxM: 1400,
      altitudeMinM: 1400,
      durationHours: 4,
      accommodation: "Hotel",
      meals: "Breakfast",
    },
    {
      dayNumber: 7,
      title: "Buddhism class — social organization visit",
      description: "Community engagement",
      details:
        "Complete the morning teaching block, then visit a local social organization from 2:00 pm—an experiential window into Nepali community life beyond the monasteries and stupas.",
      destinationName: "Kathmandu",
      distanceKm: 7,
      altitudeMaxM: 1400,
      altitudeMinM: 1400,
      durationHours: 6,
      accommodation: "Hotel",
      meals: "Breakfast",
    },
    {
      dayNumber: 8,
      title: "Three nights of monastery stay begins",
      description: "Immersive monastic life",
      details:
        "From today you stay three nights at the monastery. Learning meditation and Buddhist study is learning about your own mind—the key to joy and suffering. Whether religious or not, understanding the mind brings peace and perspective.",
      destinationName: "Kathmandu",
      distanceKm: 0,
      altitudeMaxM: 1400,
      altitudeMinM: 1400,
      durationHours: 0,
      accommodation: "Monastery",
      meals: "Breakfast",
    },
    {
      dayNumber: 9,
      title: "Departure from monastery and botanical garden",
      description: "Godawari gardens",
      details:
        "After lunch and checkout, visit the National Botanical Garden at Godawari (1,515 m) below Phulchowki. Over 500 plant species thrive across 82 hectares; spring and autumn bring rhododendron arboreum—the national flower—and colourful blooms.",
      destinationName: "Kathmandu",
      distanceKm: 7,
      altitudeMaxM: 1515,
      altitudeMinM: 1400,
      durationHours: 5,
      accommodation: "Hotel",
      meals: "Breakfast",
    },
    {
      dayNumber: 10,
      title: "Drive to Chitwan",
      description: "Into the Terai jungle",
      details:
        "Leave the Kathmandu Valley on the winding road along the Trishuli River to Chitwan National Park—932 sq km of Terai forest, a UNESCO site since 1984, home to rhinos, tigers, leopards, gaur, sloth bears, deer, crocodiles, and over 530 bird species.",
      destinationName: "Chitwan",
      distanceKm: 180,
      altitudeMaxM: 415,
      altitudeMinM: 1400,
      durationHours: 5,
      accommodation: "Hotel",
      meals: "Breakfast, lunch, dinner",
    },
    {
      dayNumber: 11,
      title: "Explore Chitwan",
      description: "Jungle activities",
      details:
        "Village walk, sunset views, Tharu stick dance, canoe ride, elephant breeding centre, optional elephant-back safari, and bird watching among Chitwan’s rich wildlife and Tharu culture.",
      destinationName: "Chitwan",
      distanceKm: 0,
      altitudeMaxM: 415,
      altitudeMinM: 415,
      durationHours: 8,
      accommodation: "Hotel",
      meals: "Breakfast, lunch, dinner",
    },
    {
      dayNumber: 12,
      title: "Chitwan to Lumbini",
      description: "Birthplace of Buddha",
      details:
        "Finish remaining Chitwan activities, then drive to Lumbini—birthplace of Lord Buddha and a UNESCO pilgrimage site where Prince Siddhartha Gautama was born in 623 BC. Ashoka’s commemorative pillar from 249 BC marks the nativity site.",
      destinationName: "Lumbini",
      distanceKm: 177,
      altitudeMaxM: 150,
      altitudeMinM: 415,
      durationHours: 5,
      accommodation: "Hotel",
      meals: "Breakfast",
    },
    {
      dayNumber: 13,
      title: "Explore Lumbini",
      description: "Sacred garden and temples",
      details:
        "Explore Lumbini’s temples, Mayadevi Temple, Holy Pond, and Kapilvastu remains—one of four great Buddhist pilgrimage sites alongside Kushinagar, Bodh Gaya, and Sarnath, where the Buddha lived until age 29.",
      destinationName: "Lumbini",
      distanceKm: 0,
      altitudeMaxM: 150,
      altitudeMinM: 150,
      durationHours: 6,
      accommodation: "Hotel",
      meals: "Breakfast",
    },
    {
      dayNumber: 14,
      title: "Lumbini to Pokhara",
      description: "Lake city drive",
      details:
        "Scenic drive to Pokhara, Nepal’s third-largest city and tourism capital—famous for Himalayan views, Phewa Lake, boating, trekking gateways, paragliding, and zip lining beneath the Annapurna range.",
      destinationName: "Pokhara",
      distanceKm: 203,
      altitudeMaxM: 900,
      altitudeMinM: 150,
      durationHours: 7,
      accommodation: "Hotel",
      meals: "Breakfast",
    },
    {
      dayNumber: 15,
      title: "Explore Pokhara",
      description: "Lakes and caves",
      details:
        "Visit Phewa Lake, Devi’s Fall, Mahendra and Bat caves, a Tibetan refugee camp, and local museums—or add adventure options such as paragliding, zip flyer, skydiving, or mountain biking.",
      destinationName: "Pokhara",
      distanceKm: 0,
      altitudeMaxM: 900,
      altitudeMinM: 900,
      durationHours: 6,
      accommodation: "Hotel",
      meals: "Breakfast",
    },
    {
      dayNumber: 16,
      title: "Sarangkot sunrise",
      description: "Himalayan panorama",
      details:
        "Pre-dawn drive or hike to Sarangkot above Phewa Lake for sunrise reflecting on Annapurna, Dhaulagiri, Machhapuchhre, and Ganesh Himal—with a 360° view back over the lake. Return to Pokhara for cafés, lakeside dining, or spa time.",
      destinationName: "Pokhara",
      distanceKm: 10,
      altitudeMaxM: 1600,
      altitudeMinM: 900,
      durationHours: 4,
      accommodation: "Hotel",
      meals: "Breakfast",
    },
    {
      dayNumber: 17,
      title: "Pokhara to Kathmandu",
      description: "Return to the valley",
      details:
        "After breakfast, drive back to Kathmandu. Rest, explore Thamel, or enjoy restaurants and bars before the final valley days.",
      destinationName: "Kathmandu",
      distanceKm: 201,
      altitudeMaxM: 1400,
      altitudeMinM: 900,
      durationHours: 7,
      accommodation: "Hotel",
      meals: "Breakfast",
    },
    {
      dayNumber: 18,
      title: "Pharping monastery and farewell dinner",
      description: "Padmasambhava caves",
      details:
        "Visit Pharping’s Dakshinkali Temple, Asura Cave where Guru Padmasambhava was enlightened, Gorakhanath, Sheshnarayan, and monasteries. Shop for spices, tea, or pashmina in local markets, then a Nepalese dinner with cultural program.",
      destinationName: "Kathmandu",
      distanceKm: 20,
      altitudeMaxM: 1400,
      altitudeMinM: 1400,
      durationHours: 6,
      accommodation: "Hotel",
      meals: "Breakfast, dinner",
    },
    {
      dayNumber: 19,
      title: "Final departure",
      description: "Farewell Nepal",
      details:
        "Transfer to the airport for your flight home with memories of temples, monasteries, jungle, Lumbini, lakes, and Himalayan sunrises.",
      destinationName: "Kathmandu",
      distanceKm: 5,
      altitudeMaxM: 1400,
      altitudeMinM: 1400,
      durationHours: 0.5,
      accommodation: "N/A",
      meals: "Breakfast",
    },
  ],
};
