import type { PublicTrip } from "@/types/trip";

const MAP_URL = "https://himalayancircuit.com/images/map/Group%20277.png";
const HERO_URL =
  "https://himalayancircuit.com/storage/media/gosainkuna-trek.webp";

export const FALLBACK_TRIP_LANGTANG_VALLEY_WITH_GOSAIKUNDA_TREK: PublicTrip = {
  id: 21,
  slug: "langtang-valley-with-gosaikunda-trek",
  title: "Langtang Valley with Gosaikunda Trek",
  summary:
    "Seventeen days linking Langtang valley, Kyanjin Gompa, sacred Gosaikunda lakes, Laurebina Pass, and Helambu to Chisapani—Nepal’s first Himalayan national park, Tamang and Sherpa villages, and peaks to 7,246 m.",
  description:
    "Langtang is among the most picturesque treks near Kathmandu, connecting the Langtang and Helambu valleys with the high lake country of Gosaikunda. The journey begins with a drive to Syabrubesi and follows the Langtang Khola through forest where red panda, langur monkeys, and rhododendron thrive in Nepal’s first Himalayan National Park (1971). Views open toward Langtang Lirung (7,246 m), Dorje Lakpa, Gang Chhenpo, and Naya Kanga. At Kyanjin Gompa (3,870 m) you can visit the monastery and yak-cheese factory, with optional climbs toward Chorkari Ri. After descending toward Thulo Syabru, the trail rises through Sing Gomba to holy Gosaikunda, crosses Laurebina Pass (4,610 m), and finishes through Helambu and Chisapani to Sundarijal. Sherpa and Tamang culture, summer wildflower valleys, and constant mountain scenery make this a demanding but unforgettable loop.",
  durationDays: 17,
  tripType: "trekking_hiking",
  budgetLevel: "premium",
  comfortLevel: "basic",
  difficultyLevel: "challenging",
  interestTags: [
    "langtang",
    "gosaikunda",
    "helambu",
    "kyanjin",
    "trekking",
    "tamang",
    "sherpa",
    "national_park",
    "himalaya",
  ],
  priceFrom: { amount: "2386", currency: "USD" },
  imageUrl: HERO_URL,
  startingRegion: { slug: "kathmandu-valley", name: "Kathmandu Valley" },
  totalDistanceKm: 281,
  altitudeMaxM: 4380,
  altitudeMinM: 1400,
  routeGrades: ["Grade C (difficult)"],
  fitnessNotes: ["Strength", "Stamina"],
  recommendedSeasons: ["Autumn", "Spring"],
  mapImageUrl: MAP_URL,
  galleryImageUrls: [HERO_URL, MAP_URL],
  sourceReferenceUrl:
    "https://himalayancircuit.com/tour/langtang-valley-with-gosaikunda-trek",
  priceTable: {
    currency: "USD",
    supplementaryChargePercent: 30,
    footnote:
      "Indicative per-person pricing for the services described in this offer. Cost varies with customization. International flights are not included.",
    columns: [
      { key: "2", label: "2 travellers" },
      { key: "4", label: "4 travellers" },
      { key: "8", label: "8 travellers" },
    ],
    rows: [
      {
        label: "Standard",
        prices: { "2": "2552", "4": "2458", "8": "2386" },
      },
      {
        label: "Deluxe",
        prices: { "2": "2818", "4": "2756", "8": "2665" },
      },
    ],
  },
  bookingFeeItems: [
    "Trekking permit",
    "Entrance fees",
    "15 days advance booking required",
  ],
  gearChecklist: [
    "Hiking boots",
    "Thermals",
    "First-aid kit",
    "Thermal bottle",
    "Sleep wear / under clothes",
    "Rain jacket",
    "Warm cap & gloves",
    "Torch with extra batteries",
    "Plug adapter (if needed)",
    "Travel towels",
    "Sun block",
    "Personal medicines",
    "Lip balm",
    "Down jacket",
    "Sleeping bag",
    "Backpack",
  ],
  trekkingGradeNotes:
    "Grade C: sustained climbing, Laurebina Pass, and long days. Prior trekking experience and good fitness are recommended; optional Chorkari Ri approaches 5,050 m.",
  faq: [
    {
      question: "What should I pack for my trip to Nepal?",
      answer:
        "Layered clothing, broken-in boots, rain gear, and a day pack cover the essentials. Rent or buy extra warm layers in Kathmandu if needed.",
    },
    {
      question: "What currency is used in Nepal?",
      answer:
        "The Nepalese Rupee (NPR) is official. ATMs exist in Kathmandu; carry cash for remote tea houses on the trek.",
    },
  ],
  reviewSnippets: [
    { name: "Christopher", location: "UK", date: "2026-04-20" },
    { name: "David", location: "Australia", date: "2026-04-09" },
    { name: "Mathis & Ida", location: "Germany", date: "2026-04-06" },
    { name: "Paul & Tim", location: "Germany", date: "2026-03-25" },
    { name: "Claudia", location: "Germany", date: "2026-03-18" },
  ],
  services: {
    included: [
      "Airport transfers to and from the hotel",
      "Twin/double room with breakfast in Kathmandu",
      "Private vehicle for Kathmandu–Dhunche–Kathmandu ground transport",
      "English-speaking tour and trekking guide",
      "One porter for every two trekkers",
      "Langtang National Park permit and TIMS card",
      "Teahouse accommodation with breakfast, lunch, and dinner on trek",
      "First-aid kit and water-purification tablets",
      "All government and local taxes",
    ],
    excluded: [
      "Bar bills and personal expenses including laundry",
      "Natural calamities beyond our control and rescue expenses",
      "Travel / medical insurance",
      "Nepal visa fees",
      "International airfares",
      "Lunch and dinner in Kathmandu",
      "Gratuity to staff",
    ],
    optional: [
      "Program split into Langtang-only or Gosaikunda-only sections",
      "Extra nights in Kathmandu",
      "Room upgrade or single supplement",
    ],
  },
  days: [
    {
      dayNumber: 1,
      title: "Arrival in Kathmandu",
      description: "Namaste and welcome",
      details:
        "Fly into the Kathmandu Valley with Himalayan views below. Our representative meets you at the airport and drives you to your hotel with time to rest after your flight.",
      destinationName: "Kathmandu",
      distanceKm: 5,
      altitudeMaxM: 1400,
      altitudeMinM: 1400,
      durationHours: 0.5,
      accommodation: "Hotel",
      meals: "As arranged",
    },
    {
      dayNumber: 2,
      title: "Kathmandu UNESCO heritage tour",
      description: "Swayambhunath and Durbar Square",
      details:
        "Visit Swayambhunath (Monkey Temple), a sacred hilltop stupa linking Buddhist and Hindu traditions, then explore Kathmandu Durbar Square with its Malla-era palaces, Kumari shrine, and pagoda architecture.",
      destinationName: "Kathmandu",
      distanceKm: 7,
      altitudeMaxM: 1400,
      altitudeMinM: 1400,
      durationHours: 6,
      accommodation: "Hotel",
      meals: "Breakfast",
    },
    {
      dayNumber: 3,
      title: "Drive from Kathmandu to Dhunche — Syabrubesi",
      description: "Into Rasuwa",
      details:
        "Scenic driving through villages and changing landscapes to Dhunche, Rasuwa district headquarters. Your guide completes permit formalities before you continue to Syabrubesi on the Langtang Khola for the night.",
      destinationName: "Syabrubesi",
      distanceKm: 100,
      altitudeMaxM: 2030,
      altitudeMinM: 1400,
      durationHours: 8,
      accommodation: "Tea house / mountain lodge",
      meals: "Breakfast, lunch, dinner",
    },
    {
      dayNumber: 4,
      title: "Trek from Dhunche to Lama Hotel",
      description: "First full trekking day",
      details:
        "Cross suspension bridges and follow the Langtang river deep into the valley through bamboo forest to Rimche and Lama Hotel, with chances to spot monkeys, red panda, or bear sign.",
      destinationName: "Lama Hotel",
      distanceKm: 27,
      altitudeMaxM: 2470,
      altitudeMinM: 2030,
      durationHours: 10,
      accommodation: "Tea house / mountain lodge",
      meals: "Breakfast, lunch, dinner",
    },
    {
      dayNumber: 5,
      title: "Trek from Lama Hotel to Langtang village",
      description: "Into the national park",
      details:
        "Pass Gumanechok and Ghoda Tabela, climbing through forest and yak pastures toward Langtang village with views of Langtang Lirung—about six hours to the heart of the valley.",
      destinationName: "Langtang",
      distanceKm: 12,
      altitudeMaxM: 3430,
      altitudeMinM: 2470,
      durationHours: 6,
      accommodation: "Tea house / mountain lodge",
      meals: "Breakfast, lunch, dinner",
    },
    {
      dayNumber: 6,
      title: "Trek from Langtang village to Kyanjin Gompa",
      description: "Yak pastures and moraine",
      details:
        "A shorter day through small settlements and yak kharka, crossing streams and moraine to Kyanjin Gompa (3,870 m) with time to explore, photograph, and rest.",
      destinationName: "Kyanjin Gompa",
      distanceKm: 7,
      altitudeMaxM: 3870,
      altitudeMinM: 3430,
      durationHours: 2,
      accommodation: "Tea house / mountain lodge",
      meals: "Breakfast, lunch, dinner",
    },
    {
      dayNumber: 7,
      title: "Exploration at Kyanjin — optional Chorkari Ri",
      description: "Acclimatisation and views",
      details:
        "Optional climb toward Chorkari Ri (about 5,050 m) for panoramas of Langtang Lirung, Langshisha Ri, Ganja La peaks, and the icefalls above Kyanjin. Visit the yak-cheese factory and monastery in the afternoon.",
      destinationName: "Kyanjin Gompa",
      distanceKm: 8,
      altitudeMaxM: 5050,
      altitudeMinM: 3870,
      durationHours: 6,
      accommodation: "Tea house / mountain lodge",
      meals: "Breakfast, lunch, dinner",
    },
    {
      dayNumber: 8,
      title: "Trek from Kyanjin Gompa to Lama Hotel",
      description: "Descend the valley",
      details:
        "Retrace the trail downstream through forest and villages to Lama Hotel, with a restful evening before branching toward Gosaikunda.",
      destinationName: "Lama Hotel",
      distanceKm: 19,
      altitudeMaxM: 3870,
      altitudeMinM: 2470,
      durationHours: 6,
      accommodation: "Tea house / mountain lodge",
      meals: "Breakfast, lunch, dinner",
    },
    {
      dayNumber: 9,
      title: "Trek from Lama Hotel to Thulo Syabru",
      description: "Ridge villages",
      details:
        "Climb through bright terrain to upper Syabru, watching for red pandas and birds, with views of Ganesh Himal, Langtang, and neighbouring peaks from Thulo Syabru.",
      destinationName: "Thulo Syabru",
      distanceKm: 12,
      altitudeMaxM: 2470,
      altitudeMinM: 2210,
      durationHours: 5,
      accommodation: "Tea house / mountain lodge",
      meals: "Breakfast, lunch, dinner",
    },
    {
      dayNumber: 10,
      title: "Trek from Thulo Syabru to Sing Gomba (Chandanbari)",
      description: "Rhododendron and cheese country",
      details:
        "Ascend through Dimsa, rhododendron, hemlock, and oak forest to Sing Gomba, known for yak cheese and wide views of Langtang and Annapurna ranges.",
      destinationName: "Sing Gomba",
      distanceKm: 11,
      altitudeMaxM: 3330,
      altitudeMinM: 2210,
      durationHours: 6,
      accommodation: "Tea house / mountain lodge",
      meals: "Breakfast, lunch, dinner",
    },
    {
      dayNumber: 11,
      title: "Trek from Sing Gomba to Gosaikunda",
      description: "Holy lakes",
      details:
        "Climb through laurel forest and open ridge to Gosaikunda (4,380 m)—sacred to Hindus, especially during August pilgrimages—with time to explore the lakes at sunset.",
      destinationName: "Gosaikunda",
      distanceKm: 10,
      altitudeMaxM: 4380,
      altitudeMinM: 3330,
      durationHours: 4,
      accommodation: "Tea house / mountain lodge",
      meals: "Breakfast, lunch, dinner",
    },
    {
      dayNumber: 12,
      title: "Trek from Gosaikunda to Ghopte",
      description: "Laurebina Pass",
      details:
        "A demanding day over Laurebina Pass (4,610 m) past small lakes, ridge trails, and forest to Ghopte—one of the trek’s physical highlights.",
      destinationName: "Ghopte",
      distanceKm: 11,
      altitudeMaxM: 4610,
      altitudeMinM: 3330,
      durationHours: 6,
      accommodation: "Tea house / mountain lodge",
      meals: "Breakfast, lunch, dinner",
    },
    {
      dayNumber: 13,
      title: "Trek from Ghopte to Kutumsang",
      description: "Into Helambu",
      details:
        "Join the Helambu circuit route, descending through fir and rhododendron with views of Gangchempo and Dorje Lakpa via Tharepati and Kuala Bhanjyang to Kutumsang.",
      destinationName: "Kutumsang",
      distanceKm: 13,
      altitudeMaxM: 3330,
      altitudeMinM: 2470,
      durationHours: 6,
      accommodation: "Tea house / mountain lodge",
      meals: "Breakfast, lunch, dinner",
    },
    {
      dayNumber: 14,
      title: "Trek from Kutumsang to Chisapani",
      description: "Sunrise ridges",
      details:
        "Kutumsang is known for golden sunrise light on the Himalaya. Follow the ridge about six to seven hours to Chisapani.",
      destinationName: "Chisapani",
      distanceKm: 17,
      altitudeMaxM: 2470,
      altitudeMinM: 2165,
      durationHours: 7,
      accommodation: "Tea house / mountain lodge",
      meals: "Breakfast, lunch, dinner",
    },
    {
      dayNumber: 15,
      title: "Trek Chisapani to Sundarijal — drive to Kathmandu",
      description: "Exit Shivapuri hills",
      details:
        "Tamang heritage trails through Mulkharka and Shivapuri National Park to Sundarijal, then drive back to Kathmandu to complete the loop.",
      destinationName: "Kathmandu",
      distanceKm: 10,
      altitudeMaxM: 2165,
      altitudeMinM: 1400,
      durationHours: 4,
      accommodation: "Hotel",
      meals: "Breakfast, lunch, dinner",
    },
    {
      dayNumber: 16,
      title: "Pashupatinath and Patan Durbar Square",
      description: "Final culture day",
      details:
        "Visit Pashupatinath on the Bagmati River and Patan Durbar Square’s Krishna Temple, courtyards, and Newari craftsmanship—a closing look at valley heritage.",
      destinationName: "Kathmandu",
      distanceKm: 15,
      altitudeMaxM: 1400,
      altitudeMinM: 1400,
      durationHours: 6,
      accommodation: "Hotel",
      meals: "Breakfast",
    },
    {
      dayNumber: 17,
      title: "Departure from Kathmandu",
      description: "Farewell to Nepal",
      details:
        "Airport transfer for your onward flight—until the mountains call you back.",
      destinationName: "Kathmandu",
      distanceKm: 5,
      altitudeMaxM: 1400,
      altitudeMinM: 1400,
      durationHours: 0.5,
      accommodation: "Hotel",
      meals: "Breakfast",
    },
  ],
};
