import type { PublicTrip } from "@/types/trip";

const MAP_URL = "https://himalayancircuit.com/images/map/Group%20277.png";
const HERO_URL =
  "https://himalayancircuit.com/storage/media/pikey-peak-trekking.webp";

export const FALLBACK_TRIP_PIKEY_BASE_CAMP_TREK_EVEREST_VIEW: PublicTrip = {
  id: 23,
  slug: "pikey-base-camp-trek-everest-view",
  title: "Pikey Base Camp Trek – Everest View",
  summary:
    "Ten days to Pikey Base Camp and Pikey Peak viewpoints in lower Solu—Sir Edmund Hillary’s favourite Everest panorama, rhododendron ridges, Sherpa villages, and a quieter alternative to the main Khumbu trail.",
  description:
    "Pikey Peak was among Sir Edmund Hillary’s preferred viewpoints for Mt. Everest, and the base camp trek at about 3,640 m offers a shorter, less-crowded Solu alternative for Everest lovers. On clear days the panorama sweeps from Dhaulagiri west to Kanchenjunga east—including Everest, Manaslu, Thamserku, Numbur, Kantega, Gauri Shankar, Dorje Lakpa, and Mera Peak. The hike passes rhododendron, oak, and pine forest, Buddhist mani walls, and farming villages on ridges above the Solu Khola, with road access via the Solu–Salleri corridor making logistics easier than in the past. Village homestays, simple tea houses, and optional extensions toward Phaplu or Tingla add cultural depth to this Grade B trek in the Everest region without requiring extreme altitude.",
  durationDays: 10,
  tripType: "trekking_hiking",
  budgetLevel: "premium",
  comfortLevel: "basic",
  difficultyLevel: "moderate",
  interestTags: [
    "pikey_peak",
    "everest_view",
    "solu",
    "trekking",
    "rhododendron",
    "sherpa",
    "phaplu",
    "less_crowded",
    "himalaya",
  ],
  priceFrom: { amount: "1795", currency: "USD" },
  imageUrl: HERO_URL,
  startingRegion: { slug: "kathmandu-valley", name: "Kathmandu Valley" },
  totalDistanceKm: 352,
  altitudeMaxM: 4070,
  altitudeMinM: 1300,
  routeGrades: ["Grade B (mildly difficult)"],
  fitnessNotes: ["Aerobic fitness"],
  recommendedSeasons: ["Autumn", "Spring"],
  mapImageUrl: MAP_URL,
  galleryImageUrls: [HERO_URL, MAP_URL],
  sourceReferenceUrl:
    "https://himalayancircuit.com/tour/pikey-base-camp-trek-everest-view",
  priceTable: {
    currency: "USD",
    supplementaryChargePercent: 30,
    footnote:
      "Indicative per-person pricing for the services described in this offer. Cost varies with customization. International flights are not included.",
    columns: [
      { key: "2", label: "2 travellers" },
      { key: "4", label: "4 travellers" },
      { key: "8", label: "8 travellers" },
    ],
    rows: [
      {
        label: "Standard",
        prices: { "2": "2011", "4": "1915", "8": "1795" },
      },
      {
        label: "Deluxe",
        prices: { "2": "2143", "4": "2047", "8": "1927" },
      },
    ],
  },
  bookingFeeItems: [
    "Possible extension to Everest Base Camp trek",
    "Fly back from Phaplu",
    "Other cultural city tours",
    "Village trek extension in Tingla",
  ],
  gearChecklist: [
    "Sleeping bag",
    "Backpack",
    "Hiking boots",
    "Socks",
    "Trekking shorts",
    "T-shirts",
    "Thermals",
    "Sunglasses / sun hat",
    "Lip balm",
    "Personal medicines",
    "Down jacket",
    "Rain jacket",
    "First-aid kit",
  ],
  trekkingGradeNotes:
    "Grade B: steady ridge walking with some long drive days. Pikey Base Camp is moderate altitude; optional Pikey Peak viewpoints reach about 4,070 m—pace yourself and hydrate.",
  faq: [
    {
      question: "Is Nepal a safe destination for tourists?",
      answer:
        "Nepal is generally peaceful and welcoming. Follow your guide on remote Solu trails and check weather before ridge walks.",
    },
    {
      question: "When is the best time to travel to Nepal?",
      answer:
        "Autumn (September–November) and spring (March–May) offer the clearest Everest and eastern Himalayan views from Pikey ridges.",
    },
  ],
  reviewSnippets: [
    { name: "Christopher", location: "UK", date: "2026-04-20" },
    { name: "David", location: "Australia", date: "2026-04-09" },
    { name: "Mathis & Ida", location: "Germany", date: "2026-04-06" },
    { name: "Paul & Tim", location: "Germany", date: "2026-03-25" },
    { name: "Claudia", location: "Germany", date: "2026-03-18" },
  ],
  services: {
    included: [
      "International airport pickup and hotel transfer",
      "Three nights hotel in Kathmandu with breakfast",
      "English-speaking city tour guide",
      "Entrance fees to cultural sites listed in the itinerary",
      "All private transportation in the destination area",
      "Six nights in tea house, homestay, or tented camp on trek",
      "Three standard meals per day during trekking",
      "Kathmandu–Jantardhap private drive",
      "Experienced licensed English-speaking trekking guide",
      "TIMS card",
      "Pasang Lamu Village Municipality fees",
      "Pikey Peak trekking permit",
      "One porter per two trekkers (about 10 kg each)",
      "Guide and porter salary, remuneration, and insurance",
      "Tingla to Kathmandu private jeep transfer",
      "Government tax",
      "Airport transfer on completion of the programme",
    ],
    excluded: [
      "Bar bills, mineral water, cold drinks, and cigarettes",
      "Client personal insurance and unforeseen expenses",
      "Natural calamities beyond our control and rescue expenses",
      "Travel / medical insurance and Nepal visa fees",
      "International flights",
      "Lunch and dinner in Kathmandu (except where noted)",
      "Gratuity to staff",
    ],
    optional: [
      "Extension to Everest Base Camp trek",
      "Flight from Phaplu",
      "Extra days in Tingla village homestay",
    ],
  },
  days: [
    {
      dayNumber: 1,
      title: "Arrival in Kathmandu",
      description: "Welcome to Nepal",
      details:
        "Our representative meets you at the airport and transfers you to your hotel in central Kathmandu. The afternoon is free to stroll the city before trekking to Pikey.",
      destinationName: "Kathmandu",
      distanceKm: 5,
      altitudeMaxM: 1400,
      altitudeMinM: 1300,
      durationHours: 0.5,
      accommodation: "Hotel",
      meals: "Breakfast",
    },
    {
      dayNumber: 2,
      title: "Drive from Kathmandu to Jantardhap",
      description: "Into eastern Nepal",
      details:
        "An eight-hour drive reaches Jantardhap (about 1,450 m), a small village in the hills east of Kathmandu—the gateway to lower Solu.",
      destinationName: "Jantardhap",
      distanceKm: 140,
      altitudeMaxM: 1450,
      altitudeMinM: 1400,
      durationHours: 8,
      accommodation: "Tea house / mountain lodge",
      meals: "Breakfast, lunch, dinner",
    },
    {
      dayNumber: 3,
      title: "Jantardhap to Jhapre",
      description: "First mountain sunrise",
      details:
        "Pre-dawn climb to Chuiyathan Danda for sunrise over hills and a first sight of Everest, then trek through rhododendron, pine, and bamboo via Sigane to Jhapre (2,950 m) and its monastery.",
      destinationName: "Jhapre",
      distanceKm: 10,
      altitudeMaxM: 2100,
      altitudeMinM: 1450,
      durationHours: 5,
      accommodation: "Tea house / mountain lodge",
      meals: "Breakfast, lunch, dinner",
    },
    {
      dayNumber: 4,
      title: "Jhapre to Pikey Base Camp",
      description: "Ridge panorama day",
      details:
        "Ascend through rhododendron forest and villages—Lamje, Chayapsa, Samsing Bhanjyang—to Pikey Base Camp (3,640 m) with 360° mountain views along the ridge.",
      destinationName: "Pikey Base Camp",
      distanceKm: 8,
      altitudeMaxM: 3640,
      altitudeMinM: 2600,
      durationHours: 4,
      accommodation: "Tea house / mountain lodge",
      meals: "Breakfast, lunch, dinner",
    },
    {
      dayNumber: 5,
      title: "Pikey Base Camp to Loding",
      description: "Descend toward Solu",
      details:
        "Descend through villages toward the Solu River, cross and climb toward Phaplu (2,250 m) with optional views of apple orchards and farms, then continue on rural trails toward Loding.",
      destinationName: "Loding",
      distanceKm: 8,
      altitudeMaxM: 3640,
      altitudeMinM: 1960,
      durationHours: 4,
      accommodation: "Tea house / mountain lodge",
      meals: "Breakfast, lunch, dinner",
    },
    {
      dayNumber: 6,
      title: "Loding to Jorboudha or Salme",
      description: "Rural Solu life",
      details:
        "Gentle walking past farming terraces and working villages—experience subsistence agriculture and quiet hill life away from the main Everest highway.",
      destinationName: "Jorboudha",
      distanceKm: 14,
      altitudeMaxM: 2350,
      altitudeMinM: 1960,
      durationHours: 5,
      accommodation: "Tea house / mountain lodge",
      meals: "Breakfast, lunch, dinner",
    },
    {
      dayNumber: 7,
      title: "Jorboudha or Salme to Tingla",
      description: "Village homestay",
      details:
        "A shorter hiking day with time to visit local hydro projects and walk with villagers. Overnight in arranged homestay accommodation in Tingla.",
      destinationName: "Tingla",
      distanceKm: 10,
      altitudeMaxM: 3500,
      altitudeMinM: 2600,
      durationHours: 5,
      accommodation: "Homestay",
      meals: "Breakfast, lunch, dinner",
    },
    {
      dayNumber: 8,
      title: "Drive from Tingla to Kathmandu",
      description: "Return to the capital",
      details:
        "Eight to nine hours by private jeep back to Kathmandu, with optional extra village days in Tingla if arranged in advance.",
      destinationName: "Kathmandu",
      distanceKm: 140,
      altitudeMaxM: 2000,
      altitudeMinM: 1400,
      durationHours: 7,
      accommodation: "Hotel",
      meals: "Breakfast, lunch",
    },
    {
      dayNumber: 9,
      title: "Boudhanath and Pashupatinath cultural tour",
      description: "Valley heritage",
      details:
        "Visit Boudhanath—among the world’s largest stupas with prayer wheels and Buddha images—and Pashupatinath on the Bagmati River, Nepal’s revered Shiva temple and cremation ghats.",
      destinationName: "Kathmandu",
      distanceKm: 12,
      altitudeMaxM: 1350,
      altitudeMinM: 1350,
      durationHours: 5,
      accommodation: "Hotel",
      meals: "Breakfast",
    },
    {
      dayNumber: 10,
      title: "Departure",
      description: "Farewell to Nepal",
      details:
        "Airport transfer for your onward flight—we wish you a safe journey and hope Pikey’s views stay with you.",
      destinationName: "Kathmandu",
      distanceKm: 5,
      altitudeMaxM: 1350,
      altitudeMinM: 1350,
      durationHours: 0.5,
      accommodation: "Hotel",
      meals: "Breakfast",
    },
  ],
};
