import type { PublicTrip } from "@/types/trip";

const MAP_URL = "https://himalayancircuit.com/images/map/Group%20277.png";
const HERO_URL = "https://himalayancircuit.com/storage/media/gokyo-trek.jpg";

export const FALLBACK_TRIP_EBC_TREK_WITH_GOKYO_LAKE_TREKKING: PublicTrip = {
  id: 24,
  slug: "ebc-trek-with-gokyo-lake-trekking",
  title: "EBC Trek with Gokyo Lake Trekking",
  summary:
    "Twenty days combining Everest Base Camp, Kala Patthar, the Cho La corridor, and sacred Gokyo lakes—with Namche, Tengboche, Lobuche, Gokyo Ri, and the full Khumbu panorama in one extended trek.",
  description:
    "The Everest Base Camp trek with Gokyo valley adds turquoise high lakes and Gokyo Ri’s sweeping eight-thousand-metre views to the classic Khumbu journey. Trek through UNESCO-listed Sagarmatha National Park—rhododendron forests, red panda habitat, and Sherpa villages from Phakding and Namche to Tengboche, Dingboche, Lobuche, Gorak Shep, and Base Camp at 5,364 m. Cross glacier country toward Gokyo Cho (Dudh Pokhari) beneath Cho Oyu and Kantega, with rest days for acclimatisation and optional Mani Rimdu season culture. This extended route is among Nepal’s most popular treks: demanding, rewarding, and a once-in-a-lifetime encounter with the world’s highest peaks.",
  durationDays: 20,
  tripType: "trekking_hiking",
  budgetLevel: "premium",
  comfortLevel: "basic",
  difficultyLevel: "challenging",
  interestTags: [
    "everest",
    "ebc",
    "gokyo",
    "gokyo_ri",
    "khumbu",
    "cho_la",
    "kalapatthar",
    "sherpa",
    "trekking",
    "himalaya",
  ],
  priceFrom: { amount: "3704", currency: "USD" },
  imageUrl: HERO_URL,
  startingRegion: { slug: "kathmandu-valley", name: "Kathmandu Valley" },
  totalDistanceKm: 776,
  altitudeMaxM: 5555,
  altitudeMinM: 1400,
  routeGrades: ["Grade C (difficult)", "Grade D (quite the challenge)"],
  fitnessNotes: ["Strength", "Stamina"],
  recommendedSeasons: ["Autumn", "Spring"],
  mapImageUrl: MAP_URL,
  galleryImageUrls: [HERO_URL, MAP_URL],
  sourceReferenceUrl:
    "https://himalayancircuit.com/tour/ebc-trek-with-gokyo-lake-trekking",
  priceTable: {
    currency: "USD",
    supplementaryChargePercent: 30,
    footnote:
      "Indicative per-person pricing for the services described in this offer. Cost varies with customization. International flights are not included.",
    columns: [
      { key: "2", label: "2 travellers" },
      { key: "4", label: "4 travellers" },
      { key: "8", label: "8 travellers" },
    ],
    rows: [
      {
        label: "Standard",
        prices: { "2": "3920", "4": "3824", "8": "3704" },
      },
      {
        label: "Deluxe",
        prices: { "2": "4059", "4": "3963", "8": "3843" },
      },
    ],
  },
  bookingFeeItems: [
    "T-shirt",
    "Entrance fee",
    "Guide fee",
    "Sagarmatha National Park fees",
    "Village municipality fees",
  ],
  gearChecklist: [
    "Sleeping bag",
    "Backpack",
    "First-aid kit",
    "Rain jacket",
    "Warm cap & gloves",
    "Torch with extra batteries",
    "Plug adapter (if needed)",
    "Travel towels",
    "Sunglasses / sun hat",
    "Insect repellent",
    "Personal medicines",
    "Down jacket",
    "Hiking boots",
    "Socks",
    "Thermals",
    "T-shirts",
    "Lip balm",
  ],
  trekkingGradeNotes:
    "Grade C and D: includes Cho La glacier terrain, Gokyo altitude, and long days. Crampons or microspikes may be needed for icy sections—confirm with your guide by season.",
  faq: [
    {
      question: "How does this differ from the standard Everest Base Camp trek?",
      answer:
        "This itinerary adds Gokyo lakes, Gokyo Ri, and the high route via Cho La after Base Camp—more days, more altitude variety, and broader Himalayan views.",
    },
    {
      question: "What should I pack for Gokyo and EBC?",
      answer:
        "Full cold-weather kit, sun protection, and sturdy boots are essential. A down jacket and sleeping bag suitable for sub-zero lodge nights are recommended.",
    },
  ],
  reviewSnippets: [
    { name: "Christopher", location: "UK", date: "2026-04-20" },
    { name: "David", location: "Australia", date: "2026-04-09" },
    { name: "Mathis & Ida", location: "Germany", date: "2026-04-06" },
    { name: "Paul & Tim", location: "Germany", date: "2026-03-25" },
    { name: "Claudia", location: "Germany", date: "2026-03-18" },
  ],
  services: {
    included: [
      "Accommodation in Kathmandu with standard twin room and breakfast",
      "All airport pickups and hotel transfers",
      "Breakfast, lunch, and dinner while trekking",
      "Twin-share tea house accommodation on trek",
      "Private vehicle for ground transportation in Kathmandu",
      "TIMS card",
      "Sagarmatha (Everest) National Park permit",
      "Experienced trekking guide",
      "One porter for every two trekkers",
      "Kathmandu–Lukla–Kathmandu flights",
      "All meals, insurance, equipment, and transport for trekking staff",
      "Airport transfer on completion of the programme",
      "All taxes",
    ],
    excluded: [
      "Bar bills",
      "Client personal insurance and unforeseen expenses",
      "Natural calamities beyond our control and rescue expenses",
      "Travel / medical insurance and Nepal visa fees",
      "Lunch and dinner in Kathmandu",
      "Gratuity to staff",
      "Single supplementary charge",
    ],
    optional: [
      "Extra nights in Kathmandu for Lukla weather delays",
      "Room upgrade or single supplement",
    ],
  },
  days: [
    {
      dayNumber: 1,
      title: "Arrival in Kathmandu",
      description: "Welcome to Nepal",
      details:
        "Our representative meets you at the airport and transfers you to your hotel in central Kathmandu. Explore Thamel or rest after your journey.",
      destinationName: "Kathmandu",
      distanceKm: 5,
      altitudeMaxM: 1400,
      altitudeMinM: 1400,
      durationHours: 0.5,
      accommodation: "Hotel",
      meals: "As arranged",
    },
    {
      dayNumber: 2,
      title: "Kathmandu cultural tour",
      description: "Monkey Temple and Durbar Square",
      details:
        "Orientation and sightseeing including Swayambhunath and Kathmandu Durbar Square. Rest in the afternoon before the early Lukla flight.",
      destinationName: "Kathmandu",
      distanceKm: 10,
      altitudeMaxM: 1400,
      altitudeMinM: 1400,
      durationHours: 5,
      accommodation: "Hotel",
      meals: "Breakfast",
    },
    {
      dayNumber: 3,
      title: "Flight to Lukla — trek to Phakding",
      description: "Himalayan flight",
      details:
        "Morning flight to Tenzing-Hillary Airport at Lukla (2,860 m), then trek along the Dudh Kosi to Phakding.",
      destinationName: "Phakding",
      distanceKm: 12,
      altitudeMaxM: 2860,
      altitudeMinM: 1400,
      durationHours: 4,
      accommodation: "Tea house / mountain lodge",
      meals: "Breakfast, lunch, dinner",
    },
    {
      dayNumber: 4,
      title: "Trek to Namche Bazaar",
      description: "Sagarmatha National Park",
      details:
        "Cross suspension bridges, enter the national park, and climb to Namche Bazaar—the Khumbu’s main trading hub.",
      destinationName: "Namche Bazaar",
      distanceKm: 12,
      altitudeMaxM: 3440,
      altitudeMinM: 2610,
      durationHours: 6,
      accommodation: "Tea house / mountain lodge",
      meals: "Breakfast, lunch, dinner",
    },
    {
      dayNumber: 5,
      title: "Acclimatisation in Namche Bazaar",
      description: "First views of Everest",
      details:
        "Climb high, sleep low, with a museum visit and first views of Everest near the Tenzing Norgay memorial.",
      destinationName: "Namche Bazaar",
      distanceKm: 5,
      altitudeMaxM: 3880,
      altitudeMinM: 3440,
      durationHours: 4,
      accommodation: "Tea house / mountain lodge",
      meals: "Breakfast, lunch, dinner",
    },
    {
      dayNumber: 6,
      title: "Trek to Tengboche Monastery",
      description: "Buddhist ceremony",
      details:
        "Walk beside the Dudh Kosi with Everest overhead to Tengboche monastery for prayer ceremonies, Buddha statues, and lama robes.",
      destinationName: "Tengboche",
      distanceKm: 11,
      altitudeMaxM: 3860,
      altitudeMinM: 3440,
      durationHours: 6,
      accommodation: "Tea house / mountain lodge",
      meals: "Breakfast, lunch, dinner",
    },
    {
      dayNumber: 7,
      title: "Trek to Dingboche",
      description: "Ama Dablam views",
      details:
        "Cross the Imja Khola via Pangboche’s mani stones to Dingboche with views of Lhotse, Island Peak, and Ama Dablam.",
      destinationName: "Dingboche",
      distanceKm: 5,
      altitudeMaxM: 4410,
      altitudeMinM: 3860,
      durationHours: 4,
      accommodation: "Tea house / mountain lodge",
      meals: "Breakfast, lunch, dinner",
    },
    {
      dayNumber: 8,
      title: "Acclimatisation — Chhukung and Dingboche",
      description: "Lhotse south face",
      details:
        "Day hike to Chhukung valley for dramatic Lhotse wall views, returning to sleep in Dingboche.",
      destinationName: "Dingboche",
      distanceKm: 5,
      altitudeMaxM: 4730,
      altitudeMinM: 4410,
      durationHours: 4,
      accommodation: "Tea house / mountain lodge",
      meals: "Breakfast, lunch, dinner",
    },
    {
      dayNumber: 9,
      title: "Trek to Lobuche",
      description: "Climber memorials",
      details:
        "Follow Khumbu Glacier moraine past memorials to fallen climbers, reaching Lobuche at about 4,940 m.",
      destinationName: "Lobuche",
      distanceKm: 9,
      altitudeMaxM: 4940,
      altitudeMinM: 4410,
      durationHours: 6,
      accommodation: "Tea house / mountain lodge",
      meals: "Breakfast, lunch, dinner",
    },
    {
      dayNumber: 10,
      title: "Gorak Shep — Kala Patthar sunset",
      description: "Panorama at dusk",
      details:
        "Slow ascent toward Gorak Shep with Khumbu Glacier views, then climb Kala Patthar (about 5,550 m) for sunset on Everest, Nuptse, Pumori, and Lhotse before returning to Gorak Shep.",
      destinationName: "Gorak Shep",
      distanceKm: 15,
      altitudeMaxM: 5550,
      altitudeMinM: 4940,
      durationHours: 8,
      accommodation: "Tea house / mountain lodge",
      meals: "Breakfast, lunch, dinner",
    },
    {
      dayNumber: 11,
      title: "Everest Base Camp — Pheriche",
      description: "Foot of Everest",
      details:
        "Walk the glacier to Everest Base Camp (5,364 m), then descend to Pheriche for the night.",
      destinationName: "Pheriche",
      distanceKm: 11,
      altitudeMaxM: 5364,
      altitudeMinM: 4371,
      durationHours: 8,
      accommodation: "Tea house / mountain lodge",
      meals: "Breakfast, lunch, dinner",
    },
    {
      dayNumber: 12,
      title: "Toward Cho La — Thagnag",
      description: "Glacier crossing approach",
      details:
        "Cross arid valley and icy trails toward Cho La glacier country, descending to Thagnag with views of Machhermo peak.",
      destinationName: "Thagnag",
      distanceKm: 10,
      altitudeMaxM: 5420,
      altitudeMinM: 4700,
      durationHours: 8,
      accommodation: "Tea house / mountain lodge",
      meals: "Breakfast, lunch, dinner",
    },
    {
      dayNumber: 13,
      title: "Trek to Gokyo",
      description: "Sacred lakes",
      details:
        "Follow the glacier route to Gokyo Cho (Dudh Pokhari) in the Gokyo valley—turquoise water with Everest and Cho Oyu on the horizon. Wind can be strong; views are unforgettable.",
      destinationName: "Gokyo",
      distanceKm: 8,
      altitudeMaxM: 5357,
      altitudeMinM: 4790,
      durationHours: 6,
      accommodation: "Tea house / mountain lodge",
      meals: "Breakfast, lunch, dinner",
    },
    {
      dayNumber: 14,
      title: "Rest and explore Gokyo",
      description: "Ngozumpa glacier",
      details:
        "Rest day beside Nepal’s largest glacier, Ngozumpa, with views toward Kantega and Cho Oyu and time for Sherpa culture.",
      destinationName: "Gokyo",
      distanceKm: 0,
      altitudeMaxM: 4750,
      altitudeMinM: 4750,
      durationHours: 0,
      accommodation: "Tea house / mountain lodge",
      meals: "Breakfast, lunch, dinner",
    },
    {
      dayNumber: 15,
      title: "Gokyo Ri — trek toward Machhermo",
      description: "Eight-thousander panorama",
      details:
        "Ascend Gokyo Ri for a spectacular 360° view of eight-thousanders and countless peaks, then continue through yak pastures toward Machhermo.",
      destinationName: "Machhermo",
      distanceKm: 14,
      altitudeMaxM: 5357,
      altitudeMinM: 3440,
      durationHours: 7,
      accommodation: "Tea house / mountain lodge",
      meals: "Breakfast, lunch, dinner",
    },
    {
      dayNumber: 16,
      title: "Trek from Gokyo to Dole",
      description: "Descent through valleys",
      details:
        "Leave Gokyo on forested trails descending toward Dole through rhododendron and pine.",
      destinationName: "Dole",
      distanceKm: 18,
      altitudeMaxM: 4790,
      altitudeMinM: 4200,
      durationHours: 8,
      accommodation: "Tea house / mountain lodge",
      meals: "Breakfast, lunch, dinner",
    },
    {
      dayNumber: 17,
      title: "Trek from Dole to Namche Bazaar",
      description: "Return to the Sherpa capital",
      details:
        "Continue downhill through villages and forest back to Namche Bazaar.",
      destinationName: "Namche Bazaar",
      distanceKm: 12,
      altitudeMaxM: 4200,
      altitudeMinM: 3440,
      durationHours: 6,
      accommodation: "Tea house / mountain lodge",
      meals: "Breakfast, lunch, dinner",
    },
    {
      dayNumber: 18,
      title: "Trek from Namche to Lukla",
      description: "Celebrate the journey",
      details:
        "Final trekking day to Lukla—celebrate completing Base Camp, Kala Patthar, and Gokyo with your team.",
      destinationName: "Lukla",
      distanceKm: 18,
      altitudeMaxM: 3440,
      altitudeMinM: 2860,
      durationHours: 8,
      accommodation: "Tea house / mountain lodge",
      meals: "Breakfast, lunch, dinner",
    },
    {
      dayNumber: 19,
      title: "Fly to Kathmandu — farewell dinner",
      description: "Back to the valley",
      details:
        "Morning flight to Kathmandu, hotel transfer, and traditional Nepali farewell dinner in the evening.",
      destinationName: "Kathmandu",
      distanceKm: 300,
      altitudeMaxM: 2860,
      altitudeMinM: 1400,
      durationHours: 1,
      accommodation: "Hotel",
      meals: "Breakfast",
    },
    {
      dayNumber: 20,
      title: "Departure",
      description: "Farewell to Nepal",
      details:
        "Airport transfer after breakfast. Safe travels—we hope the Khumbu and Gokyo valleys stay with you.",
      destinationName: "Kathmandu",
      distanceKm: 5,
      altitudeMaxM: 1400,
      altitudeMinM: 1400,
      durationHours: 0.5,
      accommodation: "Hotel",
      meals: "Breakfast",
    },
  ],
};
