import type { PublicTrip } from "@/types/trip";

const MAP_URL = "https://himalayancircuit.com/images/map/Group%20277.png";
const HERO_URL =
  "https://himalayancircuit.com/storage/media/kathmandu-cultural-tour1.webp";

export const FALLBACK_TRIP_HIGHLIGHTS_OF_NEPAL_TOUR: PublicTrip = {
  id: 25,
  slug: "highlights-of-nepal-tour",
  title: "Highlights of Nepal Tour",
  summary:
    "Twelve days linking Kathmandu’s Boudhanath and Pashupatinath, Chitwan jungle safaris, Pokhara lakes and Sarangkot sunrises, World Peace Stupa hike, and Bhaktapur’s living heritage—with a farewell cultural dinner.",
  description:
    "Highlights of Nepal Tours spotlight the Kathmandu Valley—Swayambhunath, Patan Durbar Square, Boudhanath, and Pashupatinath—before a scenic drive to Chitwan National Park for jungle walks, jeep safaris, elephant briefings, and Tharu village culture. Continue to Pokhara for Phewa Lake, the Mountain Museum, Davis Falls, Gupteshwor Cave, Sarangkot dawn views over Annapurna and Machhapuchhre, and a hike to the World Peace Stupa. Fly back to Kathmandu for Bhaktapur Durbar Square’s pagodas, pottery square, and Newar alleys, capped by a traditional Nepalese dinner with cultural program. Hotel comfort throughout; optional paragliding and zip-line adventures in Pokhara.",
  durationDays: 12,
  tripType: "cultural_heritage",
  budgetLevel: "mid_range",
  comfortLevel: "standard",
  difficultyLevel: "easy",
  interestTags: [
    "kathmandu",
    "chitwan",
    "pokhara",
    "culture",
    "wildlife",
    "heritage",
    "safari",
    "lakes",
    "bhaktapur",
    "peace-stupa",
  ],
  priceFrom: { amount: "1269", currency: "USD" },
  imageUrl: HERO_URL,
  startingRegion: { slug: "kathmandu-valley", name: "Kathmandu Valley" },
  totalDistanceKm: 650,
  altitudeMaxM: 1600,
  altitudeMinM: 415,
  routeGrades: ["Grade A (an easy endeavour)"],
  fitnessNotes: ["Aerobic fitness"],
  recommendedSeasons: ["All year round"],
  mapImageUrl: MAP_URL,
  galleryImageUrls: [HERO_URL, MAP_URL],
  sourceReferenceUrl:
    "https://himalayancircuit.com/tour/highlights-of-nepal-tour",
  priceTable: {
    currency: "USD",
    supplementaryChargePercent: 30,
    footnote:
      "Indicative per-person pricing for the services described in this offer. Cost varies with customization. International flights are not included. Deluxe package includes Pokhara–Kathmandu flight.",
    columns: [
      { key: "2", label: "2 travellers" },
      { key: "4", label: "4 travellers" },
      { key: "8", label: "8 travellers" },
    ],
    rows: [
      {
        label: "Standard",
        prices: { "2": "1469", "4": "1400", "8": "1269" },
      },
      {
        label: "Deluxe",
        prices: { "2": "1769", "4": "1649", "8": "1429" },
      },
    ],
  },
  bookingFeeItems: [
    "Entrance fee",
    "T-shirt",
    "Kathmandu - Chitwan - Pokhara tour",
    "City tour",
    "Experiential tours",
  ],
  gearChecklist: [
    "Backpack",
    "First-aid kit",
    "Quick-dry T-shirts",
    "Sandals",
    "Rain jacket",
    "Warm cap and gloves",
    "Plug adapter (if needed)",
    "Travel towels",
    "Sunglasses / sun hat",
    "Sun block",
    "Lip balm",
    "Personal medicines",
  ],
  trekkingGradeNotes:
    "A cultural and wildlife tour with short hikes—no high-altitude trekking. Light layers suit Chitwan heat and Sarangkot mornings.",
  faq: [
    {
      question: "How can I stay connected in Nepal?",
      answer:
        "Mobile networks and affordable data plans work well in Kathmandu and Pokhara. eSIM and local SIM options are widely available before heading to more remote areas.",
    },
    {
      question: "Do I need vaccinations for Nepal?",
      answer:
        "No specific vaccinations are required to enter Nepal. Consult your doctor or a travel clinic for personalized advice before departure.",
    },
  ],
  reviewSnippets: [
    { name: "Christopher", location: "UK", date: "2026-04-20" },
    { name: "David", location: "Australia", date: "2026-04-09" },
    { name: "Mathis & Ida", location: "Germany", date: "2026-04-06" },
    { name: "Paul & Tim", location: "Germany", date: "2026-03-25" },
    { name: "Claudia", location: "Germany", date: "2026-03-18" },
  ],
  services: {
    included: [
      "All airport pickup and drop",
      "All accommodation with breakfast",
      "English-speaking city tour guide",
      "English-speaking guides during excursions",
      "Entrance fees to cultural heritage sites and Durbar Squares as per itinerary",
      "English-speaking naturalist in Chitwan",
      "Meals included in Chitwan",
      "Pokhara–Kathmandu flight (Deluxe package)",
      "Government tax",
      "Airport transfer upon completion of the program",
    ],
    excluded: [
      "Bar bills (alcoholic drinks, mineral water, cold drinks)",
      "Client personal insurance and unforeseen expenses",
      "Natural calamities beyond our control and rescue expenses",
      "Travel / medical insurance and Nepal visa fees",
      "Lunch and dinner in Kathmandu and Pokhara (except farewell dinner)",
      "Gratuity to staff",
    ],
    optional: [
      "Deluxe package with domestic flight",
      "Paragliding, zip-line, or skymotion adventures in Pokhara",
      "Extra nights in Kathmandu",
    ],
  },
  days: [
    {
      dayNumber: 1,
      title: "Arrival in Kathmandu",
      description: "Welcome to Nepal",
      details:
        "Meet at Tribhuvan International Airport and transfer to your hotel in the heart of Kathmandu. Rest after your journey and meet your travel expert to review the adventure ahead.",
      destinationName: "Kathmandu",
      distanceKm: 5,
      altitudeMaxM: 1400,
      altitudeMinM: 1400,
      durationHours: 0.5,
      accommodation: "Hotel",
      meals: "As arranged",
    },
    {
      dayNumber: 2,
      title: "Boudhanath and Pashupatinath city tour",
      description: "Sacred valley sites",
      details:
        "Visit Boudhanath—the world’s largest stupa in the valley—with prayer wheels and Buddha images, then Pashupatinath on the Bagmati River, a UNESCO-listed Hindu temple where cremation rites offer a profound view of life’s cycle.",
      destinationName: "Kathmandu",
      distanceKm: 15,
      altitudeMaxM: 1400,
      altitudeMinM: 1400,
      durationHours: 5,
      accommodation: "Hotel",
      meals: "Breakfast",
    },
    {
      dayNumber: 3,
      title: "Drive Kathmandu to Chitwan National Park",
      description: "Into the Terai",
      details:
        "Scenic 6–7 hour drive along the Trishuli River to Sauraha and Chitwan National Park—a UNESCO site since 1984, home to rhinos, tigers, leopards, deer, crocodiles, and over 530 bird species. Evening Tharu village visit and sunset over the river.",
      destinationName: "Chitwan",
      distanceKm: 170,
      altitudeMaxM: 415,
      altitudeMinM: 1400,
      durationHours: 6,
      accommodation: "Hotel",
      meals: "Breakfast, lunch, dinner",
    },
    {
      dayNumber: 4,
      title: "Explore Chitwan National Park",
      description: "Jungle activities",
      details:
        "Jeep safari, guided jungle walk with naturalists, elephant briefing, and visit to the elephant breeding centre—full board at the lodge with chances to spot rhinos, deer, and with luck tigers or leopards.",
      destinationName: "Chitwan",
      distanceKm: 20,
      altitudeMaxM: 415,
      altitudeMinM: 415,
      durationHours: 5,
      accommodation: "Hotel",
      meals: "Breakfast, lunch, dinner",
    },
    {
      dayNumber: 5,
      title: "Chitwan National Park continue",
      description: "Wildlife and birds",
      details:
        "Continue Chitwan’s included activities—jeep safari, guided walks, elephant centre, and bird watching with trackers and naturalists.",
      destinationName: "Chitwan",
      distanceKm: 20,
      altitudeMaxM: 415,
      altitudeMinM: 415,
      durationHours: 5,
      accommodation: "Hotel",
      meals: "Breakfast, lunch, dinner",
    },
    {
      dayNumber: 6,
      title: "Chitwan to Pokhara — lakeside",
      description: "Lake city arrival",
      details:
        "Drive to Pokhara, Nepal’s scenic second city on Phewa Lake, framed by the Annapurna range—a hub for boating, trekking, rafting, and paragliding with relaxed lakeside cafés.",
      destinationName: "Pokhara",
      distanceKm: 160,
      altitudeMaxM: 822,
      altitudeMinM: 415,
      durationHours: 6,
      accommodation: "Hotel",
      meals: "Breakfast",
    },
    {
      dayNumber: 7,
      title: "Guided tour in Pokhara",
      description: "Museum and caves",
      details:
        "Half-day Mountain Museum tour on Nepal’s climbing culture, then Davis Falls and Gupteshwor Cave with ornately carved staircases—free time to enjoy Pokhara’s lakeside.",
      destinationName: "Pokhara",
      distanceKm: 20,
      altitudeMaxM: 822,
      altitudeMinM: 822,
      durationHours: 5,
      accommodation: "Hotel",
      meals: "Breakfast",
    },
    {
      dayNumber: 8,
      title: "Sarangkot tour — free time",
      description: "Sunrise and adventure options",
      details:
        "Pre-dawn drive to Sarangkot for sunrise over Annapurna, Dhaulagiri, and Machhapuchhre, then return to Pokhara for leisure or optional paragliding, zip-line, skymotion, or mountain biking.",
      destinationName: "Sarangkot",
      distanceKm: 10,
      altitudeMaxM: 1600,
      altitudeMinM: 822,
      durationHours: 2,
      accommodation: "Hotel",
      meals: "Breakfast",
    },
    {
      dayNumber: 9,
      title: "Hike to World Peace Stupa",
      description: "Phewa Lake and stupa",
      details:
        "Boat across Phewa Lake, then a comfortable 45-minute hike to the World Peace Stupa for panoramic Annapurna and Machhapuchhre views—a signature Pokhara experience.",
      destinationName: "Pokhara",
      distanceKm: 8,
      altitudeMaxM: 1100,
      altitudeMinM: 822,
      durationHours: 1,
      accommodation: "Hotel",
      meals: "Breakfast",
    },
    {
      dayNumber: 10,
      title: "Fly Pokhara to Kathmandu",
      description: "Return to the capital",
      details:
        "Late-afternoon flight or drive to Kathmandu and transfer to your hotel with time to explore Thamel’s shops and restaurants.",
      destinationName: "Kathmandu",
      distanceKm: 201,
      altitudeMaxM: 1400,
      altitudeMinM: 822,
      durationHours: 7,
      accommodation: "Hotel",
      meals: "Breakfast",
    },
    {
      dayNumber: 11,
      title: "Bhaktapur Durbar Square city tour",
      description: "City of devotees",
      details:
        "Tour Bhaktapur’s Durbar Square—Peacock Window, pottery square, Golden Temple, and Newar alleys—then a farewell Nepalese dinner with cultural program.",
      destinationName: "Bhaktapur",
      distanceKm: 16,
      altitudeMaxM: 1400,
      altitudeMinM: 1400,
      durationHours: 2,
      accommodation: "Hotel",
      meals: "Breakfast, dinner",
    },
    {
      dayNumber: 12,
      title: "Departure from Kathmandu",
      description: "Farewell",
      details:
        "Transfer to Tribhuvan International Airport after breakfast for your flight home with memories of temples, jungle, lakes, and mountains.",
      destinationName: "Kathmandu",
      distanceKm: 5,
      altitudeMaxM: 1400,
      altitudeMinM: 1400,
      durationHours: 0.5,
      accommodation: "N/A",
      meals: "Breakfast",
    },
  ],
};
