import type { PublicTrip } from "@/types/trip";
import { ITINERARY_IMAGES, LOCATION_IMAGES, TRIP_HERO_IMAGES } from "@/lib/trip-images";

const MAP_URL = "https://himalayancircuit.com/images/map/Group%20277.png";
const HERO_URL = TRIP_HERO_IMAGES["ghandruk-landruk-annapurna-trek-experience"];

export const FALLBACK_TRIP_GHANDRUK_LANDRUK_ANNAPURNA_TREK_EXPERIENCE: PublicTrip = {
  id: 20,
  slug: "ghandruk-landruk-annapurna-trek-experience",
  title: "Ghandruk & Landruk Annapurna Trek Experience",
  summary:
    "Eight days from Kathmandu to Pokhara and a gentle Annapurna loop: Phedi to Pothana, Landruk above the Modi Khola, and Gurung Ghandruk—with Annapurna South, Hiunchuli, and Machhapuchhre views throughout.",
  description:
    "The Pothana–Landruk–Ghandruk trek is a short, scenic circuit in Nepal’s Annapurna foothills—ideal for families, first-time trekkers, and anyone wanting culture without extreme altitude. From a drive to Phedi, the trail climbs through rhododendron and oak to Pothana, continues to Landruk above the Modi Khola, and finishes in hilltop Ghandruk with its stone houses and warm Gurung hospitality. Expect terraced fields, suspension bridges, tea-house stays, and panoramas of Annapurna South, Hiunchuli, and Machhapuchhre. Spring (March–May) and autumn (September–November) bring the clearest skies; winter can be quiet and pleasant, while monsoon months are best avoided. Kathmandu bookends the journey before you return from Nayapul to Pokhara’s lakeside.",
  durationDays: 8,
  tripType: "trekking_hiking",
  budgetLevel: "premium",
  comfortLevel: "standard",
  difficultyLevel: "moderate",
  interestTags: [
    "ghandruk",
    "landruk",
    "pothana",
    "annapurna",
    "pokhara",
    "gurung",
    "trekking",
    "family_friendly",
    "himalaya",
  ],
  priceFrom: { amount: "1137", currency: "USD" },
  imageUrl: HERO_URL,
  startingRegion: { slug: "kathmandu-valley", name: "Kathmandu Valley" },
  totalDistanceKm: 515,
  altitudeMaxM: 2012,
  altitudeMinM: 822,
  routeGrades: ["Grade B (mildly difficult)"],
  fitnessNotes: ["Aerobic fitness"],
  recommendedSeasons: ["All year round"],
  mapImageUrl: MAP_URL,
  galleryImageUrls: [
    HERO_URL,
    LOCATION_IMAGES.ghandruk,
    LOCATION_IMAGES.australianCamp,
  ],
  sourceReferenceUrl:
    "https://himalayancircuit.com/tour/ghandruk-landruk-annapurna-trek-experience",
  priceTable: {
    currency: "USD",
    supplementaryChargePercent: 30,
    footnote:
      "Indicative per-person pricing for the services described in this offer. Cost varies with customization. International flights are not included. Deluxe package may include Kathmandu–Pokhara flights.",
    columns: [
      { key: "2", label: "2 travellers" },
      { key: "4", label: "4 travellers" },
      { key: "8", label: "8 travellers" },
    ],
    rows: [
      {
        label: "Standard",
        prices: { "2": "1353", "4": "1257", "8": "1137" },
      },
      {
        label: "Deluxe",
        prices: { "2": "1628", "4": "1586", "8": "1466" },
      },
    ],
  },
  bookingFeeItems: [
    "Local village tour",
    "T-shirt",
    "Entrance fees",
    "Cultural immersion",
  ],
  gearChecklist: [
    "Hiking boots",
    "Socks",
    "Trekking shorts",
    "Sleep wear / under clothes",
    "Quick-dry T-shirts",
    "Rain jacket",
    "Warm cap & gloves",
    "Torch with extra batteries",
    "Plug adapter (if needed)",
    "Travel towels",
    "Sunglasses / sun hat",
    "Sun block",
    "Backpack",
    "T-shirts",
    "Thermals",
    "First-aid kit",
  ],
  trekkingGradeNotes:
    "Grade B: moderate ups and downs on stone paths and terraces, but no high altitude. Suitable for fit beginners and families with older children.",
  faq: [
    {
      question: "What should I pack for my trip to Nepal?",
      answer:
        "Layers for cool mornings, sturdy shoes, rain gear, and a day pack suffice on this trek. Heavier items can be bought or rented in Kathmandu or Pokhara if needed.",
    },
    {
      question: "When is the best time to travel to Nepal?",
      answer:
        "Autumn (September–November) and spring (March–May) offer the clearest mountain views on this route. Winter can be crisp and quiet; monsoon months are wetter on the trails.",
    },
  ],
  reviewSnippets: [
    { name: "Christopher", location: "UK", date: "2026-04-20" },
    { name: "David", location: "Australia", date: "2026-04-09" },
    { name: "Mathis & Ida", location: "Germany", date: "2026-04-06" },
    { name: "Paul & Tim", location: "Germany", date: "2026-03-25" },
    { name: "Claudia", location: "Germany", date: "2026-03-18" },
  ],
  services: {
    included: [
      "Airport pickup and transfer to the hotel",
      "Deluxe room with breakfast in Kathmandu and Pokhara",
      "Super deluxe room with breakfast in Pokhara (as per package)",
      "Standard teahouse accommodation with all meals during trekking",
      "Entrance fees to sightseeing sites listed in the itinerary",
      "Private air-conditioned vehicle with driver and guide for Pokhara touring",
      "Luxury coach Kathmandu–Pokhara–Kathmandu (standard package)",
      "Kathmandu–Pokhara–Kathmandu flights (deluxe package)",
      "Trekking guide",
      "One porter for every two trekkers",
      "All trekking permits as per itinerary",
      "All meals during trekking",
      "Government tax",
      "Airport transfer on completion of the programme",
    ],
    excluded: [
      "Bar bills and drinks",
      "Client personal insurance and unforeseen expenses",
      "Natural calamities beyond our control and rescue expenses",
      "Travel / medical insurance",
      "Nepal visa fees",
      "Lunch and dinner in Kathmandu and Pokhara",
      "International flights",
      "Gratuity to staff",
    ],
    optional: [
      "Deluxe package with internal flights",
      "Extra nights in Kathmandu or Pokhara",
      "Local village tours and cultural add-ons",
    ],
  },
  days: [
    {
      dayNumber: 1,
      title: "Arrival in Kathmandu and transfer to your hotel",
      description: "Welcome to Nepal",
      details:
        "Upon arrival in Kathmandu you are greeted at the airport and transferred to your hotel in the city centre. The evening is free to explore nearby markets and landmarks or rest before the journey to Pokhara.",
      destinationName: "Kathmandu",
      distanceKm: 6,
      altitudeMaxM: 1400,
      altitudeMinM: 1400,
      durationHours: 0.5,
      accommodation: "Hotel",
      meals: "Breakfast",
    },
    {
      dayNumber: 2,
      title: "Drive from Kathmandu to Pokhara",
      description: "Scenic highway",
      details:
        "A seven- to eight-hour private drive through lush hills, terraced fields, and river valleys brings you to Pokhara beneath the Annapurna skyline. Check in and enjoy the lakeside in the evening.",
      destinationName: "Pokhara",
      distanceKm: 200,
      altitudeMaxM: 1400,
      altitudeMinM: 822,
      durationHours: 7,
      accommodation: "Hotel",
      meals: "Breakfast",
    },
    {
      dayNumber: 3,
      title: "Drive to Phedi and trek to Pothana",
      description: "Start of the trail",
      details:
        "After breakfast, drive to Phedi and trek about four to five hours through forest and terraces to Pothana (1,900 m), with emerging views of the Annapurna range.",
      destinationName: "Pothana",
      distanceKm: 38,
      altitudeMaxM: 1900,
      altitudeMinM: 822,
      durationHours: 5,
      accommodation: "Tea house / mountain lodge",
      meals: "Breakfast, lunch, dinner",
      imageUrl: LOCATION_IMAGES.australianCamp,
    },
    {
      dayNumber: 4,
      title: "Trek from Pothana to Landruk",
      description: "Modi Khola views",
      details:
        "Five to six hours descending through villages and terraced slopes to Landruk (1,556 m), a traditional settlement above the Modi Khola with Annapurna peaks behind.",
      destinationName: "Landruk",
      distanceKm: 8,
      altitudeMaxM: 1900,
      altitudeMinM: 1556,
      durationHours: 6,
      accommodation: "Tea house / mountain lodge",
      meals: "Breakfast, lunch, dinner",
    },
    {
      dayNumber: 5,
      title: "Trek from Landruk to Ghandruk",
      description: "Gurung heartland",
      details:
        "Four to five hours through forests and terraces to Ghandruk (2,012 m)—stone houses, Gurung culture, and wide views of Annapurna South and Machhapuchhre.",
      destinationName: "Ghandruk",
      distanceKm: 4,
      altitudeMaxM: 2012,
      altitudeMinM: 1556,
      durationHours: 5,
      accommodation: "Tea house / mountain lodge",
      meals: "Breakfast, lunch, dinner",
      imageUrl: ITINERARY_IMAGES.ghandruk,
    },
    {
      dayNumber: 6,
      title: "Trek Ghandruk to Nayapul — drive to Pokhara",
      description: "End of trekking",
      details:
        "Descend about four to five hours to Nayapul through terraced hillsides, then drive one and a half to two hours back to Pokhara for a comfortable lakeside night.",
      destinationName: "Pokhara",
      distanceKm: 54,
      altitudeMaxM: 2012,
      altitudeMinM: 822,
      durationHours: 7,
      accommodation: "Hotel",
      meals: "Breakfast, lunch",
    },
    {
      dayNumber: 7,
      title: "Drive from Pokhara to Kathmandu",
      description: "Return to the capital",
      details:
        "Six to eight hours on the Prithvi Highway through river valleys, forests, and hill towns—Mugling, Kurintar, and Damauli—before entering the Kathmandu Valley.",
      destinationName: "Kathmandu",
      distanceKm: 200,
      altitudeMaxM: 1400,
      altitudeMinM: 822,
      durationHours: 7,
      accommodation: "Hotel",
      meals: "Breakfast",
    },
    {
      dayNumber: 8,
      title: "Departure",
      description: "Farewell to Nepal",
      details:
        "Transfer to the airport for your onward flight, with memories of Landruk, Ghandruk, and the Annapurna foothills.",
      destinationName: "Kathmandu",
      distanceKm: 5,
      altitudeMaxM: 1400,
      altitudeMinM: 1400,
      durationHours: 0.5,
      accommodation: "Hotel",
      meals: "Breakfast",
    },
  ],
};
