import type { PublicTrip } from "@/types/trip";
import { ITINERARY_IMAGES, LOCATION_IMAGES, TRIP_HERO_IMAGES } from "@/lib/trip-images";

const MAP_URL = "https://himalayancircuit.com/images/map/Group%20277.png";
const HERO_URL = TRIP_HERO_IMAGES["everest-base-camp-trek"];

export const FALLBACK_TRIP_EVEREST_BASE_CAMP: PublicTrip = {
  id: 12,
  slug: "everest-base-camp-trek",
  title: "Everest Base Camp Trek",
  summary:
    "Eighteen days to the foot of the world’s highest peak: Lukla, Namche, Tengboche, Dingboche, Everest Base Camp, Kala Patthar sunrise, and the Khumbu’s Sherpa heartland—with Kathmandu sightseeing at each end.",
  description:
    "Everest Base Camp is among the greatest trekking challenges on earth—a journey to 8,848 m’s doorstep that rewards effort with prayer flags, clear skies, and a new perspective on your limits. The route climbs through Sagarmatha National Park past Namche Bazaar, Tengboche monastery, and the Imja valley to Gorak Shep and Base Camp, with a pre-dawn ascent of Kala Patthar for the classic Everest sunrise. Acclimatisation walks—including optional Chhukung—help you adapt to thin air on rocky, sometimes uneven trails. Sherpa villages, mani walls, glacier moraine, and expedition camps at Base Camp define the high Khumbu experience. This is a strenuous trek for fit walkers who want Nepal’s most iconic mountain journey.",
  durationDays: 18,
  tripType: "trekking_hiking",
  budgetLevel: "premium",
  comfortLevel: "basic",
  difficultyLevel: "challenging",
  interestTags: [
    "everest",
    "ebc",
    "khumbu",
    "kalapatthar",
    "sagarmatha",
    "sherpa",
    "tengboche",
    "trekking",
    "himalaya",
  ],
  priceFrom: { amount: "3352", currency: "USD" },
  imageUrl: HERO_URL,
  startingRegion: { slug: "kathmandu-valley", name: "Kathmandu Valley" },
  totalDistanceKm: 712,
  altitudeMaxM: 5644,
  altitudeMinM: 1400,
  routeGrades: ["Grade C (difficult)", "Grade D (quite the challenge)"],
  fitnessNotes: ["Strength", "Stamina"],
  recommendedSeasons: ["Autumn", "Spring"],
  mapImageUrl: MAP_URL,
  galleryImageUrls: [
    HERO_URL,
    "/images/trips/everest-base-camp/gallery-2516.jpeg",
    LOCATION_IMAGES.namche,
    LOCATION_IMAGES.kalaPatthar,
  ],
  sourceReferenceUrl: "https://himalayancircuit.com/tour/everest-base-camp-trek",
  priceTable: {
    currency: "USD",
    supplementaryChargePercent: 30,
    footnote:
      "Indicative per-person pricing for the services described in this offer. Cost varies with customization. International flights are not included.",
    columns: [
      { key: "2", label: "2 travellers" },
      { key: "4", label: "4 travellers" },
      { key: "8", label: "8 travellers" },
    ],
    rows: [
      {
        label: "Standard",
        prices: { "2": "3568", "4": "3472", "8": "3352" },
      },
      {
        label: "Deluxe",
        prices: { "2": "3751", "4": "3655", "8": "3535" },
      },
    ],
  },
  bookingFeeItems: [
    "Trekking permit",
    "TIMS",
    "Entrance fees",
    "15 days advance booking required",
  ],
  gearChecklist: [
    "Sleeping bag",
    "Backpack",
    "Hiking boots",
    "Socks",
    "Thermals",
    "First-aid kit",
    "Thermal bottle",
    "Sleep wear / under clothes",
    "Quick-dry T-shirts",
    "Rain jacket",
    "Warm cap & gloves",
    "Torch with extra batteries",
    "Plug adapter (if needed)",
    "Travel towels",
    "Sunglasses / sun hat",
    "Sun block",
    "Lip balm",
    "Insect repellent",
    "Personal medicines",
    "Down jacket",
  ],
  trekkingGradeNotes:
    "Grade C and D reflect long days, high altitude, and cold nights above Gorak Shep. Prior trekking experience and comprehensive travel insurance including helicopter rescue are strongly recommended.",
  faq: [
    {
      question: "What should I pack for my trip to Nepal?",
      answer:
        "Layered clothing, broken-in boots, sun protection, and a good down jacket are essential. Rent or buy gear in Kathmandu if needed; porters carry about 10 kg per person on this trek.",
    },
    {
      question: "Do I need vaccinations to enter Nepal?",
      answer:
        "No specific vaccinations are required for entry, but consult your doctor or a travel clinic before departure for personalised advice.",
    },
  ],
  reviewSnippets: [
    { name: "Christopher", location: "UK", date: "2026-04-20" },
    { name: "David", location: "Australia", date: "2026-04-09" },
    { name: "Mathis & Ida", location: "Germany", date: "2026-04-06" },
    { name: "Paul & Tim", location: "Germany", date: "2026-03-25" },
    { name: "Claudia", location: "Germany", date: "2026-03-18" },
  ],
  services: {
    included: [
      "Airport pickup and transfer to the hotel",
      "Four nights room accommodation with breakfast in Kathmandu",
      "All meals during trek with tea and coffee",
      "All ground transfers by private vehicle",
      "English-speaking tour guide in Kathmandu",
      "Experienced trekking guide",
      "Kathmandu–Lukla–Kathmandu flights for clients",
      "Kathmandu–Lukla–Kathmandu flight for guide",
      "Entrance fees to cultural sites listed in the itinerary",
      "TIMS card",
      "Sagarmatha National Park permit fees",
      "One porter for every two trekkers",
      "Food, accommodation, salary, and insurance for guide and porters",
      "Airport transfer on completion of the programme",
    ],
    excluded: [
      "Bar bills, mineral water, cold drinks, and cigarettes",
      "Client personal insurance and unforeseen expenses",
      "Natural calamities beyond our control and rescue expenses",
      "Comprehensive travel / medical insurance covering helicopter rescue",
      "Nepal visa fees",
      "Lunch and dinner in Kathmandu",
      "Gratuity to staff",
    ],
    optional: [
      "Extra nights in Kathmandu for Lukla weather delays",
      "Room upgrade or single supplement",
    ],
  },
  days: [
    {
      dayNumber: 1,
      title: "Arrival in Kathmandu",
      description: "Welcome to Nepal",
      details:
        "Our representative meets you at the airport and drives you to your hotel in central Kathmandu. Explore Thamel’s restaurants and shops or rest after your flight.",
      destinationName: "Kathmandu",
      distanceKm: 5,
      altitudeMaxM: 1400,
      altitudeMinM: 1400,
      durationHours: 0.5,
      accommodation: "Hotel",
      meals: "As arranged",
    },
    {
      dayNumber: 2,
      title: "Kathmandu Valley sightseeing",
      description: "Monkey Temple and Durbar Square",
      details:
        "Morning orientation and a tour of Swayambhunath (Monkey Temple) with 360° valley views, plus Kathmandu Durbar Square. Rest in the afternoon before the early start to Lukla.",
      destinationName: "Kathmandu",
      distanceKm: 7,
      altitudeMaxM: 1400,
      altitudeMinM: 1400,
      durationHours: 5,
      accommodation: "Hotel",
      meals: "Breakfast",
      imageUrl: ITINERARY_IMAGES.swayambhunath,
    },
    {
      dayNumber: 3,
      title: "Fly to Lukla — trek to Phakding",
      description: "Into the Khumbu",
      details:
        "Early flight to Tenzing-Hillary Airport at Lukla (2,804 m), then descend toward the Dudh Kosi and trek about 3.5 hours to Phakding for your first lodge night.",
      destinationName: "Phakding",
      distanceKm: 12,
      altitudeMaxM: 2804,
      altitudeMinM: 1400,
      durationHours: 4,
      accommodation: "Tea house / mountain lodge",
      meals: "Breakfast, lunch, dinner",
      imageUrl: ITINERARY_IMAGES.lukla,
    },
    {
      dayNumber: 4,
      title: "Trek to Namche Bazaar",
      description: "Sherpa capital",
      details:
        "Cross suspension bridges, enter Sagarmatha National Park, and climb to Namche Bazaar (3,440 m)—the Khumbu’s main market with lodges, bakeries, and shops.",
      destinationName: "Namche Bazaar",
      distanceKm: 7,
      altitudeMaxM: 3440,
      altitudeMinM: 2650,
      durationHours: 5,
      accommodation: "Tea house / mountain lodge",
      meals: "Breakfast, lunch, dinner",
      imageUrl: ITINERARY_IMAGES.namche,
    },
    {
      dayNumber: 5,
      title: "Acclimatisation day in Namche Bazaar",
      description: "Climb high, sleep low",
      details:
        "Adjust to altitude with a museum visit and views toward Everest near the Tenzing Norgay memorial—your first clear sight of the world’s highest peak.",
      destinationName: "Namche Bazaar",
      distanceKm: 0,
      altitudeMaxM: 3441,
      altitudeMinM: 3441,
      durationHours: 0,
      accommodation: "Tea house / mountain lodge",
      meals: "Breakfast, lunch, dinner",
    },
    {
      dayNumber: 6,
      title: "Trek to Tengboche Monastery",
      description: "Prayer flags and peaks",
      details:
        "Follow the Dudh Kosi with glacier views to Tengboche (3,867 m) and its famous monastery—ornate hangings, a large Buddha statue, and optional evening prayer ceremony.",
      destinationName: "Tengboche",
      distanceKm: 9,
      altitudeMaxM: 3867,
      altitudeMinM: 3441,
      durationHours: 5,
      accommodation: "Tea house / mountain lodge",
      meals: "Breakfast, lunch, dinner",
      imageUrl: ITINERARY_IMAGES.tengboche,
    },
    {
      dayNumber: 7,
      title: "Trek to Dingboche",
      description: "Mani stones and Ama Dablam",
      details:
        "Cross the Imja Khola, pass carved mani stones and Pangboche, and reach Dingboche with views of Lhotse, Island Peak, and Ama Dablam.",
      destinationName: "Dingboche",
      distanceKm: 10,
      altitudeMaxM: 4410,
      altitudeMinM: 3867,
      durationHours: 5,
      accommodation: "Tea house / mountain lodge",
      meals: "Breakfast, lunch, dinner",
      imageUrl: ITINERARY_IMAGES.dingboche,
    },
    {
      dayNumber: 8,
      title: "Acclimatisation — Chhukung and return to Dingboche",
      description: "Imja valley views",
      details:
        "Day hike toward Chhukung (4,730 m) for dramatic Lhotse south-face views, then descend to sleep again in Dingboche.",
      destinationName: "Dingboche",
      distanceKm: 9,
      altitudeMaxM: 4730,
      altitudeMinM: 4350,
      durationHours: 5,
      accommodation: "Tea house / mountain lodge",
      meals: "Breakfast, lunch, dinner",
    },
    {
      dayNumber: 9,
      title: "Trek to Lobuche",
      description: "Climber memorials",
      details:
        "Walk the Khumbu Glacier moraine past stone memorials to fallen climbers, reaching Lobuche (about 4,910 m) among surrounding snow peaks.",
      destinationName: "Lobuche",
      distanceKm: 9,
      altitudeMaxM: 4940,
      altitudeMinM: 4350,
      durationHours: 5,
      accommodation: "Tea house / mountain lodge",
      meals: "Breakfast, lunch, dinner",
    },
    {
      dayNumber: 10,
      title: "Trek to Gorak Shep",
      description: "Edge of the glacier",
      details:
        "Slow, gradual ascent to Gorak Shep (5,164 m) with views of Nuptse, Lobuche, and the Khumbu Glacier—rest before Base Camp day.",
      destinationName: "Gorak Shep",
      distanceKm: 5,
      altitudeMaxM: 5164,
      altitudeMinM: 4940,
      durationHours: 4,
      accommodation: "Tea house / mountain lodge",
      meals: "Breakfast, lunch, dinner",
    },
    {
      dayNumber: 11,
      title: "Everest Base Camp — return to Gorak Shep",
      description: "Goal day",
      details:
        "Trek along the glacier to Everest Base Camp (5,364 m)—closest most walkers can get without climbing permits—then return to Gorak Shep for the night.",
      destinationName: "Gorak Shep",
      distanceKm: 7,
      altitudeMaxM: 5364,
      altitudeMinM: 5164,
      durationHours: 6,
      accommodation: "Tea house / mountain lodge",
      meals: "Breakfast, lunch, dinner",
    },
    {
      dayNumber: 12,
      title: "Kala Patthar sunrise — trek to Pheriche",
      description: "Best Everest view",
      details:
        "Pre-dawn climb to Kala Patthar (about 5,550 m) for sunrise on Everest, Nuptse, Pumori, and Lhotse, then descend via Gorak Shep to Pheriche.",
      destinationName: "Pheriche",
      distanceKm: 10,
      altitudeMaxM: 5644,
      altitudeMinM: 4371,
      durationHours: 7,
      accommodation: "Tea house / mountain lodge",
      meals: "Breakfast, lunch, dinner",
      imageUrl: ITINERARY_IMAGES.kalaPatthar,
    },
    {
      dayNumber: 13,
      title: "Trek to Tengboche",
      description: "Descent through Pangboche",
      details:
        "Drop to Orsho and Pangboche to visit one of the region’s oldest monasteries, then continue to Tengboche.",
      destinationName: "Tengboche",
      distanceKm: 9,
      altitudeMaxM: 4371,
      altitudeMinM: 3867,
      durationHours: 4,
      accommodation: "Tea house / mountain lodge",
      meals: "Breakfast, lunch, dinner",
    },
    {
      dayNumber: 14,
      title: "Trek to Manju",
      description: "Below the high valley",
      details:
        "Morning at Tengboche monastery, then descend through Namche Bazaar to Manju (Monjo area) for a lower sleep.",
      destinationName: "Manju",
      distanceKm: 8,
      altitudeMaxM: 3867,
      altitudeMinM: 2840,
      durationHours: 6,
      accommodation: "Tea house / mountain lodge",
      meals: "Breakfast, lunch, dinner",
    },
    {
      dayNumber: 15,
      title: "Trek to Lukla",
      description: "Celebrate the journey",
      details:
        "Final trekking day back to Lukla—reflect on reaching Base Camp and Kala Patthar with your team.",
      destinationName: "Lukla",
      distanceKm: 12,
      altitudeMaxM: 2845,
      altitudeMinM: 2840,
      durationHours: 5,
      accommodation: "Tea house / mountain lodge",
      meals: "Breakfast, lunch, dinner",
    },
    {
      dayNumber: 16,
      title: "Morning flight to Kathmandu",
      description: "Last mountain views",
      details:
        "Fly from Lukla to Kathmandu and transfer to your hotel for a well-earned rest.",
      destinationName: "Kathmandu",
      distanceKm: 300,
      altitudeMaxM: 2845,
      altitudeMinM: 1400,
      durationHours: 3,
      accommodation: "Hotel",
      meals: "Breakfast",
    },
    {
      dayNumber: 17,
      title: "Free day in Kathmandu",
      description: "Rest and farewell dinner",
      details:
        "A free day to explore Thamel, the Garden of Dreams, or shop for souvenirs. Traditional Nepali farewell dinner in the evening.",
      destinationName: "Kathmandu",
      distanceKm: 0,
      altitudeMaxM: 1400,
      altitudeMinM: 1400,
      durationHours: 0,
      accommodation: "Hotel",
      meals: "Breakfast, dinner",
    },
    {
      dayNumber: 18,
      title: "Departure",
      description: "Airport transfer",
      details:
        "After breakfast, transfer to the airport for your onward flight. Safe travels—we hope the Khumbu stays with you.",
      destinationName: "Kathmandu",
      distanceKm: 5,
      altitudeMaxM: 1400,
      altitudeMinM: 1400,
      durationHours: 0.5,
      accommodation: "Hotel",
      meals: "Breakfast",
    },
  ],
};
