import type { PublicTrip } from "@/types/trip";
import { ITINERARY_IMAGES, LOCATION_IMAGES, TRIP_HERO_IMAGES } from "@/lib/trip-images";

const MAP_URL = "https://himalayancircuit.com/images/map/Group%20277.png";
const HERO_URL = TRIP_HERO_IMAGES["annapurna-circuit-trek-classic-trek"];

export const FALLBACK_TRIP_ANNAPURNA_CIRCUIT_CLASSIC_TREK: PublicTrip = {
  id: 7,
  slug: "annapurna-circuit-trek-classic-trek",
  title: "Annapurna Circuit Trek | Classic Trek",
  summary:
    "Twenty-one days around the full Annapurna Circuit: Marsyangdi villages and Manang acclimatisation, Thorung La at 5,416 m, Muktinath and the Kali Gandaki gorge, hot springs at Tatopani, and a Poon Hill sunrise finish—one of the world’s great long-distance treks.",
  description:
    "The Annapurna Circuit is among the most popular and longest classic treks in Nepal, often ranked among the world’s top ten. From Besisahar you follow the Marsyangdi through hill villages and lush forest to Manang at 3,500 m, with Buddhist monasteries and some of the Himalaya’s finest mid-range views. After acclimatisation you cross Thorung La (5,416 m) to Muktinath, descend through Kagbeni and the deep Kali Gandaki—one of the world’s deepest gorges—via Marpha and Tukuche, then Tatopani’s hot springs before rejoining the Ghorepani–Poon Hill trail. Rivers, waterfalls, and changing ecosystems make this a complete Himalayan journey.",
  durationDays: 21,
  tripType: "trekking_hiking",
  budgetLevel: "premium",
  comfortLevel: "basic",
  difficultyLevel: "challenging",
  interestTags: [
    "annapurna",
    "annapurna_circuit",
    "thorung_la",
    "muktinath",
    "manang",
    "poon_hill",
    "trekking",
    "himalaya",
    "mustang",
  ],
  priceFrom: { amount: "2419", currency: "USD" },
  imageUrl: HERO_URL,
  startingRegion: { slug: "kathmandu-valley", name: "Kathmandu Valley" },
  totalDistanceKm: 673,
  altitudeMaxM: 5416,
  altitudeMinM: 760,
  routeGrades: ["Grade C (difficult)", "Grade D (quite the challenge)"],
  fitnessNotes: ["Strength", "Stamina"],
  recommendedSeasons: ["Autumn", "Spring"],
  mapImageUrl: MAP_URL,
  galleryImageUrls: [
    HERO_URL,
    LOCATION_IMAGES.muktinath,
    LOCATION_IMAGES.kagbeni,
    LOCATION_IMAGES.poonHill,
  ],
  sourceReferenceUrl:
    "https://himalayancircuit.com/tour/annapurna-circuit-trek-classic-trek",
  priceTable: {
    currency: "USD",
    supplementaryChargePercent: 30,
    footnote:
      "Indicative per-person pricing for the services described in this offer. Cost varies with customization. International flights are not included.",
    columns: [
      { key: "2", label: "2 travellers" },
      { key: "4", label: "4 travellers" },
      { key: "8", label: "8 travellers" },
    ],
    rows: [
      {
        label: "Standard",
        prices: { "2": "2669", "4": "2600", "8": "2419" },
      },
      {
        label: "Deluxe",
        prices: { "2": "3369", "4": "3269", "8": "2919" },
      },
    ],
  },
  bookingFeeItems: [
    "T-shirt",
    "Annapurna Conservation Area fee",
    "Trekking permit",
    "Pre-departure guide",
    "Personal assistant",
  ],
  gearChecklist: [
    "Sleeping bag",
    "Backpack",
    "Hiking boots",
    "Socks",
    "Thermals",
    "Trekking shorts",
    "T-shirts",
    "First-aid kit",
    "Sleep wear / under clothes",
    "Warm cap & gloves",
    "Travel towels",
    "Sunglasses / sun hat",
    "Lip balm",
    "Insect repellent",
    "Down jacket",
    "Rain jacket",
  ],
  trekkingGradeNotes:
    "Grade C and D reflect Thorung La, long Kali Gandaki days, and the hot climb to Ghorepani. Prior multi-day trekking experience and solid fitness are recommended.",
  faq: [
    {
      question: "When is the best time for the Annapurna Circuit?",
      answer:
        "Autumn (September–November) and spring (March–May) usually offer the clearest weather for Thorung La and the best mountain views.",
    },
    {
      question: "How should I prepare for Thorung La?",
      answer:
        "Use the Manang rest day for acclimatisation walks, stay hydrated, and discuss any symptoms with your guide. The pass day starts early and is long—pace yourself from Thorung Phedi.",
    },
  ],
  reviewSnippets: [
    { name: "Christopher", location: "UK", date: "2026-04-20" },
    { name: "David", location: "Australia", date: "2026-04-09" },
    { name: "Mathis & Ida", location: "Germany", date: "2026-04-06" },
    { name: "Paul & Tim", location: "Germany", date: "2026-03-25" },
    { name: "Claudia", location: "Germany", date: "2026-03-18" },
  ],
  services: {
    included: [
      "All airport and hotel transfers",
      "Four nights in hotels in Kathmandu and Pokhara with breakfast",
      "Sixteen nights in standard lodges and teahouses in the mountains",
      "Farewell dinner at a Nepali restaurant",
      "All ground transportation",
      "All accommodation and standard meals during trekking",
      "Experienced English-speaking tour and trek guides",
      "Porters to carry luggage",
      "All necessary paperwork and permits",
      "A comprehensive medical kit",
      "All government and local taxes",
    ],
    excluded: [
      "Bar bills",
      "Natural calamities beyond our control and rescue expenses",
      "Private personal expenses",
      "Travel / medical insurance",
      "Nepal visa fees",
      "International airfares to and from Kathmandu",
      "Lunch and dinner in Kathmandu and Pokhara (except where noted)",
      "Gratuity to staff",
    ],
    optional: [
      "Room upgrade or single supplement",
      "Extra nights in Kathmandu or Pokhara",
      "Private vehicle or itinerary adjustments",
    ],
  },
  days: [
    {
      dayNumber: 1,
      title: "Arrival in Kathmandu and transfer to your hotel",
      description: "Welcome to Nepal",
      details:
        "After immigration you are met and transferred to your Kathmandu hotel. We give a short trip overview and answer questions—bring your passport and four recent passport photos for trekking permits.",
      destinationName: "Kathmandu",
      distanceKm: 5,
      altitudeMaxM: 1400,
      altitudeMinM: 1400,
      durationHours: 0.5,
      accommodation: "Hotel",
      meals: "As arranged",
    },
    {
      dayNumber: 2,
      title: "Cultural sightseeing tour in Kathmandu",
      description: "Valley heritage",
      details:
        "After breakfast you meet your tour guide for a briefing, then visit Swayambhunath (Monkey Temple) on its hilltop, followed by Patan Durbar Square with its medieval courtyards and craftsmanship.",
      destinationName: "Kathmandu",
      distanceKm: 15,
      altitudeMaxM: 1400,
      altitudeMinM: 1400,
      durationHours: 6,
      accommodation: "Hotel",
      meals: "Breakfast",
    },
    {
      dayNumber: 3,
      title: "Drive from Kathmandu to Besisahar",
      description: "Into the Marsyangdi valley",
      details:
        "A scenic drive of about six hours reaches Besisahar, a subtropical town with views toward Machhapuchhre and Annapurna, where you spend the night in a teahouse.",
      destinationName: "Besisahar",
      distanceKm: 177,
      altitudeMaxM: 1400,
      altitudeMinM: 760,
      durationHours: 6,
      accommodation: "Tea house / mountain lodge",
      meals: "Breakfast, lunch, dinner",
    },
    {
      dayNumber: 4,
      title: "Trek from Besisahar to Bahundanda",
      description: "Waterfalls and Manaslu views",
      details:
        "Cross a suspension bridge at Bhulbhule, pass a cascading waterfall, and traverse rice terraces with Manaslu coming into view. A steep climb leads to Ngadi’s shops, then Bahundanda—the northernmost Brahmin ridge village in the Marsyangdi Valley.",
      destinationName: "Bahundanda",
      distanceKm: 18,
      altitudeMaxM: 1310,
      altitudeMinM: 807,
      durationHours: 6,
      accommodation: "Tea house / mountain lodge",
      meals: "Breakfast, lunch, dinner",
    },
    {
      dayNumber: 5,
      title: "Trek from Bahundanda to Jagat",
      description: "Deep Marsyangdi gorge",
      details:
        "Descend through terraces to a stream and waterfall, then follow the river via Syange on a path that climbs high above the water before dropping to picturesque Jagat and a Tibetan-run lodge.",
      destinationName: "Jagat",
      distanceKm: 13,
      altitudeMaxM: 1310,
      altitudeMinM: 1300,
      durationHours: 6,
      accommodation: "Tea house / mountain lodge",
      meals: "Breakfast, lunch, dinner",
    },
    {
      dayNumber: 6,
      title: "Trek from Jagat to Dharapani",
      description: "Chamje and rock-hewn trail",
      details:
        "Steep forest climbing opens waterfall views before Chamje. Cross the river, climb to Sattale, pass Tal on its river plain, then wind through rock-cut sections and Karte to Dharapani’s stone kani entrance.",
      destinationName: "Dharapani",
      distanceKm: 14,
      altitudeMaxM: 1860,
      altitudeMinM: 1300,
      durationHours: 6,
      accommodation: "Tea house / mountain lodge",
      meals: "Breakfast, lunch, dinner",
    },
    {
      dayNumber: 7,
      title: "Trek from Dharapani to Chame",
      description: "Gateway to Manang",
      details:
        "Pine and oak forest, Danagyu, and a thundering waterfall lead toward Koto and a clearing with a Tibetan teahouse and Manaslu views. Annapurna II towers overhead before Chame—Manang’s administrative hub with shops, school, and army post.",
      destinationName: "Chame",
      distanceKm: 17,
      altitudeMaxM: 2670,
      altitudeMinM: 1860,
      durationHours: 7,
      accommodation: "Tea house / mountain lodge",
      meals: "Breakfast, lunch, dinner",
    },
    {
      dayNumber: 8,
      title: "Trek from Chame to Pisang",
      description: "Cool forest walking",
      details:
        "Quiet woods and peak views accompany the walk to Pisang, with the afternoon free to explore the village or climb to Upper Pisang for Annapurna II and III.",
      destinationName: "Pisang",
      distanceKm: 15,
      altitudeMaxM: 3200,
      altitudeMinM: 2670,
      durationHours: 6,
      accommodation: "Tea house / mountain lodge",
      meals: "Breakfast, lunch, dinner",
    },
    {
      dayNumber: 9,
      title: "Trek from Pisang to Manang",
      description: "High valley hub",
      details:
        "Manang’s flat-roofed houses sit at 3,540 m beneath Annapurna III, Gangapurna, and a dramatic riverside icefall. Bakeries, lodges, and an old gompa fill the lanes; you may join a Himalayan Rescue Association altitude lecture.",
      destinationName: "Manang",
      distanceKm: 16,
      altitudeMaxM: 3540,
      altitudeMinM: 3200,
      durationHours: 6,
      accommodation: "Tea house / mountain lodge",
      meals: "Breakfast, lunch, dinner",
    },
    {
      dayNumber: 10,
      title: "Rest and acclimatisation day in Manang",
      description: "Altitude preparation",
      details:
        "Options include Ice Lake, Milarepa’s cave, the Hundred Rupee Lama cave, or a gentle 300 m gain for acclimatisation—avoid overexertion while enjoying bakery stops and peak views from the lodge.",
      destinationName: "Manang",
      distanceKm: 0,
      altitudeMaxM: 3540,
      altitudeMinM: 3540,
      durationHours: 0,
      accommodation: "Tea house / mountain lodge",
      meals: "Breakfast, lunch, dinner",
    },
    {
      dayNumber: 11,
      title: "Trek from Manang to Yak Kharka",
      description: "Toward the pass",
      details:
        "A shorter day with steady gain past Tengi and Gunsang to Yak Kharka, often sharing the trail with Manangi horses in ornate Tibetan saddles.",
      destinationName: "Yak Kharka",
      distanceKm: 14,
      altitudeMaxM: 4050,
      altitudeMinM: 3540,
      durationHours: 6,
      accommodation: "Tea house / mountain lodge",
      meals: "Breakfast, lunch, dinner",
    },
    {
      dayNumber: 12,
      title: "Trek from Yak Kharka to Thorung Phedi",
      description: "Base of the pass",
      details:
        "About three hours to Thorung Phedi, with time to reach High Camp after lunch. Sleep early—tomorrow starts before dawn. Anyone feeling altitude symptoms may stay lower at Thorung Phedi base camp.",
      destinationName: "Thorung Phedi",
      distanceKm: 10,
      altitudeMaxM: 4525,
      altitudeMinM: 4050,
      durationHours: 3,
      accommodation: "Tea house / mountain lodge",
      meals: "Breakfast, lunch, dinner",
    },
    {
      dayNumber: 13,
      title: "Thorung Phedi — Thorung La — Muktinath",
      description: "Pass day",
      details:
        "Ascend to Thorung La at 5,416 m for sweeping Mustang views, then descend to Chabarbu for tea before continuing to Muktinath’s sacred Hindu and Buddhist temple complex.",
      destinationName: "Muktinath",
      distanceKm: 16,
      altitudeMaxM: 5416,
      altitudeMinM: 3760,
      durationHours: 9,
      accommodation: "Tea house / mountain lodge",
      meals: "Breakfast, lunch, dinner",
      imageUrl: ITINERARY_IMAGES.muktinath,
    },
    {
      dayNumber: 14,
      title: "Trek from Muktinath to Marpha",
      description: "Kali Gandaki and apple village",
      details:
        "Follow the Kali Gandaki riverbed toward windy Jomsom—aim to arrive before noon—then continue to Marpha’s cobbled lanes, gompa, and apple-country charm.",
      destinationName: "Marpha",
      distanceKm: 22,
      altitudeMaxM: 3800,
      altitudeMinM: 2650,
      durationHours: 7,
      accommodation: "Tea house / mountain lodge",
      meals: "Breakfast, lunch, dinner",
    },
    {
      dayNumber: 15,
      title: "Trek from Marpha to Ghasa",
      description: "Deep in the gorge",
      details:
        "Via Tukuche and wind-sheltered Larjung’s tunnels and courtyards, through juniper and cypress to Kalopani with Annapurna I and Fang, then on to Ghasa.",
      destinationName: "Ghasa",
      distanceKm: 27,
      altitudeMaxM: 3519,
      altitudeMinM: 2650,
      durationHours: 9,
      accommodation: "Tea house / mountain lodge",
      meals: "Breakfast, lunch, dinner",
    },
    {
      dayNumber: 16,
      title: "Trek from Ghasa to Tatopani",
      description: "Hot springs reward",
      details:
        "Descend to Tatopani and soak in riverside hot springs—optional massage and bakery treats cap a long descent day.",
      destinationName: "Tatopani",
      distanceKm: 14,
      altitudeMaxM: 2650,
      altitudeMinM: 1200,
      durationHours: 6,
      accommodation: "Tea house / mountain lodge",
      meals: "Breakfast, lunch, dinner",
    },
    {
      dayNumber: 17,
      title: "Trek from Tatopani to Ghorepani",
      description: "Strenuous climb",
      details:
        "One of the hardest stages: hot, hilly walking via Beni onto the Ghorepani branch with relentless ups toward the rhododendron ridge.",
      destinationName: "Ghorepani",
      distanceKm: 15,
      altitudeMaxM: 2874,
      altitudeMinM: 1200,
      durationHours: 8,
      accommodation: "Tea house / mountain lodge",
      meals: "Breakfast, lunch, dinner",
      imageUrl: ITINERARY_IMAGES.ghorepani,
    },
    {
      dayNumber: 18,
      title: "Poon Hill — trek to Tikhedhunga",
      description: "Sunrise panorama",
      details:
        "Optional pre-dawn hike to Poon Hill (3,210 m) for a 360° sunrise over the Annapurna range, then breakfast and a half-day descent toward Tikhedhunga with Machhapuchhre views—watch for monkeys along the trail.",
      destinationName: "Tikhedhunga",
      distanceKm: 9,
      altitudeMaxM: 3210,
      altitudeMinM: 1570,
      durationHours: 5,
      accommodation: "Tea house / mountain lodge",
      meals: "Breakfast, lunch, dinner",
      imageUrl: ITINERARY_IMAGES.poonHill,
    },
    {
      dayNumber: 19,
      title: "Tikhedhunga to Nayapul — drive to Pokhara",
      description: "End of trekking",
      details:
        "Terraces, waterfalls, and suspension bridges lead to Nayapul along the Modi Khola with Annapurna and Machhapuchhre above the ridges. After lunch, drive to Pokhara for a shower and lakeside evening.",
      destinationName: "Pokhara",
      distanceKm: 50,
      altitudeMaxM: 1480,
      altitudeMinM: 822,
      durationHours: 7,
      accommodation: "Hotel",
      meals: "Breakfast, lunch",
    },
    {
      dayNumber: 20,
      title: "Drive to Kathmandu",
      description: "Return to the capital",
      details:
        "After breakfast the tourist bus returns to Kathmandu. A farewell dinner with traditional Nepali food, dance, and music closes the journey.",
      destinationName: "Kathmandu",
      distanceKm: 200,
      altitudeMaxM: 1400,
      altitudeMinM: 822,
      durationHours: 7,
      accommodation: "Hotel",
      meals: "Breakfast",
    },
    {
      dayNumber: 21,
      title: "Final departure from Kathmandu",
      description: "Farewell",
      details:
        "Transfer to the airport for your flight home, carrying memories of Thorung La, the Kali Gandaki, and three weeks in the Annapurna.",
      destinationName: "Kathmandu",
      distanceKm: 5,
      altitudeMaxM: 1400,
      altitudeMinM: 1400,
      durationHours: 0.5,
      accommodation: "Hotel",
      meals: "Breakfast",
    },
  ],
};
