import type { PublicTrip } from "@/types/trip";
import { ITINERARY_IMAGES, LOCATION_IMAGES, TRIP_HERO_IMAGES } from "@/lib/trip-images";

const MAP_URL = "https://himalayancircuit.com/images/map/Group%20277.png";
const HERO_URL = TRIP_HERO_IMAGES["lumbini-pokhara-tour"];

export const FALLBACK_TRIP_LUMBINI_POKHARA_TOUR: PublicTrip = {
  id: 28,
  slug: "lumbini-pokhara-tour",
  title: "Lumbini & Pokhara Tour",
  summary:
    "Nine days linking Kathmandu’s UNESCO stupas, Namo Buddha monastery, Lumbini’s sacred garden, Pokhara’s lakes, Sarangkot sunrise, Peace Pagoda, and Pharping with Swayambhunath—spiritual, cultural, and Himalayan scenery in one tour.",
  description:
    "This Buddhist pilgrimage with Pokhara tour blends spiritual, cultural, and natural experiences across Nepal’s diversity. Visit Pashupatinath, Boudhanath, and Swayambhunath in the Kathmandu Valley, spend time with monks at Namo Buddha, fly to Lumbini—the birthplace of Lord Buddha and a UNESCO World Heritage Site—and continue to Pokhara for Sarangkot’s sunrise over Machhapuchhre and the Annapurna range, the World Peace Pagoda, and optional adventure activities. Pharping’s Padmasambhava caves complete the arc before departure. Monastery and hotel stays, domestic flights, and guided valley tours offer religious harmony, medieval heritage, and lakeside Himalayan views in a well-rounded nine-day itinerary.",
  durationDays: 9,
  tripType: "spiritual_pilgrimage",
  budgetLevel: "premium",
  comfortLevel: "standard",
  difficultyLevel: "easy",
  interestTags: [
    "spiritual_pilgrimage",
    "buddhism",
    "lumbini",
    "pokhara",
    "namo-buddha",
    "culture",
    "heritage",
    "stupa",
    "sarangkot",
    "pharping",
  ],
  priceFrom: { amount: "2143", currency: "USD" },
  imageUrl: HERO_URL,
  startingRegion: { slug: "kathmandu-valley", name: "Kathmandu Valley" },
  totalDistanceKm: 761,
  altitudeMaxM: 1750,
  altitudeMinM: 150,
  routeGrades: ["Grade A (an easy endeavour)"],
  fitnessNotes: ["Aerobic fitness"],
  recommendedSeasons: ["All year round"],
  mapImageUrl: MAP_URL,
  galleryImageUrls: [
    HERO_URL,
    LOCATION_IMAGES.lumbini,
    LOCATION_IMAGES.peaceStupaPokhara,
    LOCATION_IMAGES.boudha,
  ],
  sourceReferenceUrl:
    "https://himalayancircuit.com/tour/lumbini-pokhara-tour",
  priceTable: {
    currency: "USD",
    supplementaryChargePercent: 30,
    footnote:
      "Indicative per-person pricing for the services described in this offer. Cost varies with customization. International flights are not included. Deluxe package includes domestic flights as per itinerary.",
    columns: [
      { key: "2", label: "2 travellers" },
      { key: "4", label: "4 travellers" },
      { key: "8", label: "8 travellers" },
    ],
    rows: [
      {
        label: "Standard",
        prices: { "2": "2359", "4": "2263", "8": "2143" },
      },
      {
        label: "Deluxe",
        prices: { "2": "2682", "4": "2586", "8": "2466" },
      },
    ],
  },
  bookingFeeItems: [
    "T-shirt",
    "Entrance fee",
    "Spiritual practices",
    "Learn Buddhism",
  ],
  gearChecklist: [
    "Backpack",
    "T-shirts",
    "First-aid kit",
    "Easy-dry T-shirts",
    "Sandals",
    "Rain jacket",
    "Plug adapter (if needed)",
    "Travel towels",
    "Sunglasses / sun hat",
    "Sun block",
    "Lip balm",
    "Personal medicines",
    "Modest clothing for monastery and temple visits",
  ],
  trekkingGradeNotes:
    "A pilgrimage and cultural tour with short walks and domestic flights—no high-altitude trekking. Modest dress is appreciated at temples and monasteries.",
  faq: [
    {
      question: "What cultural norms should I follow in Nepal?",
      answer:
        "Nepal has deep religious traditions—dress modestly at temples and monasteries, remove shoes where required, ask before photographing people or rituals, and walk clockwise around stupas when locals do.",
    },
    {
      question: "Do I need vaccinations before traveling to Nepal?",
      answer:
        "No specific vaccinations are required for entry, but consult your doctor or a travel clinic for personalized advice on routine and recommended immunizations before departure.",
    },
  ],
  reviewSnippets: [
    { name: "Christopher", location: "UK", date: "2026-04-20" },
    { name: "David", location: "Australia", date: "2026-04-09" },
    { name: "Mathis & Ida", location: "Germany", date: "2026-04-06" },
    { name: "Paul & Tim", location: "Germany", date: "2026-03-25" },
    { name: "Claudia", location: "Germany", date: "2026-03-18" },
  ],
  services: {
    included: [
      "Domestic and international airport pickup and hotel transfers",
      "Twin-sharing accommodation with breakfast in Kathmandu, Pokhara, Namo Buddha, and Lumbini",
      "English-speaking tour guide in Kathmandu and Lumbini",
      "Kathmandu–Namo Buddha–Kathmandu airport private vehicle with driver",
      "Kathmandu–Bhairawa domestic flight",
      "Tricycle tour in Lumbini garden",
      "Lumbini to Pokhara in a private vehicle",
      "Pokhara to Kathmandu by domestic flight",
      "Airport transfer upon completion of the programs",
      "Government tax",
    ],
    excluded: [
      "Bar bills and personal drinks",
      "Client personal insurance and unforeseen expenses",
      "Natural calamities beyond our control and rescue expenses",
      "Travel / medical insurance",
      "Lunch and dinner in Kathmandu, Namo Buddha, Lumbini, and Pokhara",
      "Gratuity to staff",
    ],
    optional: [
      "Paragliding, zip flyer, or skymotion in Pokhara",
      "Extra nights in Kathmandu or Pokhara",
      "Mountain flight from Kathmandu",
    ],
  },
  days: [
    {
      dayNumber: 1,
      title: "Arrival in Kathmandu",
      description: "Welcome to Nepal",
      details:
        "After arrival at the airport, our representative welcomes you and transfers you to your hotel in the heart of the city. Explore Thamel’s restaurants, cafés, and shops, or rest after your journey.",
      destinationName: "Kathmandu",
      distanceKm: 5,
      altitudeMaxM: 1400,
      altitudeMinM: 1400,
      durationHours: 0.5,
      accommodation: "Hotel",
      meals: "As arranged",
    },
    {
      dayNumber: 2,
      title: "Boudhanath, Pashupatinath, and Namo Buddha",
      description: "Spiritual sightseeing",
      details:
        "Visit Boudhanath—the 36 m stupa with prayer wheels and rooftop lunch views—then Pashupatinath on the Bagmati River, where Hindu cremation rites offer perspective on life’s cycle. Continue to serene Namo Buddha amid Himalayan panoramas for an overnight monastery stay.",
      destinationName: "Namo Buddha",
      distanceKm: 49,
      altitudeMaxM: 1750,
      altitudeMinM: 1400,
      durationHours: 5,
      accommodation: "Monastery",
      meals: "Breakfast, dinner",
      imageUrl: ITINERARY_IMAGES.boudha,
    },
    {
      dayNumber: 3,
      title: "Free day with monks at Namo Buddha",
      description: "Monastery immersion",
      details:
        "Free time at Namo Buddha to spend with monks, meditate, or hike nearby villages and absorb local culture and ridge-top landscapes.",
      destinationName: "Namo Buddha",
      distanceKm: 0,
      altitudeMaxM: 1750,
      altitudeMinM: 1750,
      durationHours: 0,
      accommodation: "Monastery",
      meals: "Breakfast, dinner",
    },
    {
      dayNumber: 4,
      title: "Fly to Bhairawa — Lumbini",
      description: "Birthplace of Buddha",
      details:
        "Leave early from Namo Buddha and fly to Lumbini in the Terai—one of Buddhism’s greatest pilgrimage sites where Prince Siddhartha Gautama was born in 623 BC, visited by more than 400,000 pilgrims yearly and protected as UNESCO heritage.",
      destinationName: "Lumbini",
      distanceKm: 288,
      altitudeMaxM: 150,
      altitudeMinM: 1750,
      durationHours: 8,
      accommodation: "Hotel",
      meals: "Breakfast",
      imageUrl: ITINERARY_IMAGES.lumbini,
    },
    {
      dayNumber: 5,
      title: "Drive to Pokhara",
      description: "Lake city",
      details:
        "After breakfast, drive to Pokhara—Nepal’s third-largest city and tourism capital—famous for Himalayan views, Phewa Lake, boating, trekking gateways, paragliding, and zip lining.",
      destinationName: "Pokhara",
      distanceKm: 203,
      altitudeMaxM: 900,
      altitudeMinM: 150,
      durationHours: 7,
      accommodation: "Hotel",
      meals: "Breakfast",
    },
    {
      dayNumber: 6,
      title: "Sarangkot sunrise and Peace Pagoda",
      description: "Himalayan views",
      details:
        "Pre-dawn visit to Sarangkot for sunrise on Annapurna, Dhaulagiri, Machhapuchhre, and Ganesh Himal with Phewa Lake below. Afternoon hike to the World Peace Pagoda—Nepal’s first Nipponzan-Myōhōji pagoda—for sunset over the range and lake.",
      destinationName: "Pokhara",
      distanceKm: 10,
      altitudeMaxM: 1600,
      altitudeMinM: 900,
      durationHours: 6,
      accommodation: "Hotel",
      meals: "Breakfast",
      imageUrl: ITINERARY_IMAGES.sarangkot,
    },
    {
      dayNumber: 7,
      title: "Free day in Pokhara",
      description: "Leisure and adventure",
      details:
        "Explore Devi’s Fall, Mahendra and Bat caves, Tibetan refugee camp, or museums—or add paragliding, zip flyer, skymotion, or mountain biking with your guide’s help organizing sightseeing.",
      destinationName: "Pokhara",
      distanceKm: 0,
      altitudeMaxM: 900,
      altitudeMinM: 900,
      durationHours: 0,
      accommodation: "Hotel",
      meals: "Breakfast",
    },
    {
      dayNumber: 8,
      title: "Fly to Kathmandu — Pharping and Swayambhunath",
      description: "Valley heritage",
      details:
        "Fly back to Kathmandu and visit Pharping’s Dakshinkali Temple, Asura Cave, Gorakhanath, Sheshnarayan, and monasteries linked to Guru Padmasambhava. Finish at Swayambhunath (Monkey Temple) for valley panoramas and centuries of Hindu–Buddhist harmony.",
      destinationName: "Kathmandu",
      distanceKm: 201,
      altitudeMaxM: 1400,
      altitudeMinM: 900,
      durationHours: 7,
      accommodation: "Hotel",
      meals: "Breakfast",
      imageUrl: ITINERARY_IMAGES.swayambhunath,
    },
    {
      dayNumber: 9,
      title: "Departure",
      description: "Farewell Nepal",
      details:
        "Transfer to the airport for your flight home with memories of temples, Lumbini, lakes, and Himalayan sunrises.",
      destinationName: "Kathmandu",
      distanceKm: 5,
      altitudeMaxM: 1400,
      altitudeMinM: 1400,
      durationHours: 0.5,
      accommodation: "N/A",
      meals: "Breakfast",
    },
  ],
};
