import type { PublicTrip } from "@/types/trip";

const MAP_URL = "https://himalayancircuit.com/images/map/Group%20277.png";
const HERO_URL = "https://himalayancircuit.com/storage/media/annapurna-trek-nepal.webp";

export const FALLBACK_TRIP_EXPLORE_ANNAPURNA_BASE_CAMP_17_DAYS: PublicTrip = {
  id: 11,
  slug: "explore-annapurna-base-camp-in-17-days",
  title: "Explore Annapurna Base Camp in 17 Days",
  summary:
    "Seventeen days from Kathmandu’s UNESCO sites to Pokhara and the Annapurna sanctuary: Gurung villages at Ghandruk, stone steps through Chomrong and Dovan, Machhapuchhre Base Camp, and Annapurna Base Camp at 4,130 m—with city culture, lakeside rest, and the full ABC loop.",
  description:
    "The Annapurna Base Camp trek is one of the best ways to experience both the natural beauty and the unique cultural heritage of Nepal. You travel through landscapes filled with mountains and gentler lowland stretches, showing how diverse the country is. Villages along the route are home to Gurung and Magar communities where you can learn about their daily life. After several days in Kathmandu you drive to Pokhara, the gateway to the trek. From Nayapul a steep trail leads to Ghandruk, then onward through Chomrong, Dovan, and Machhapuchhre Base Camp—where Machhapuchhre Himal rises as a sacred, forbidden peak—before your ultimate goal at Annapurna Base Camp. The journey also weaves in Kathmandu’s rich heritage so you gain a deeper sense of Nepal’s social, economic, and cultural fabric.",
  durationDays: 17,
  tripType: "trekking_hiking",
  budgetLevel: "premium",
  comfortLevel: "basic",
  difficultyLevel: "challenging",
  interestTags: [
    "annapurna",
    "abc",
    "machhapuchhre",
    "ghandruk",
    "pokhara",
    "trekking",
    "gurung",
    "magar",
    "himalaya",
  ],
  priceFrom: { amount: "1769", currency: "USD" },
  imageUrl: HERO_URL,
  startingRegion: { slug: "kathmandu-valley", name: "Kathmandu Valley" },
  totalDistanceKm: 604,
  altitudeMaxM: 4130,
  altitudeMinM: 822,
  routeGrades: ["Grade C (difficult)", "Grade D (quite the challenge)"],
  fitnessNotes: ["Strength", "Stamina"],
  recommendedSeasons: ["Autumn", "Spring"],
  mapImageUrl: MAP_URL,
  galleryImageUrls: [HERO_URL, MAP_URL],
  sourceReferenceUrl: "https://himalayancircuit.com/tour/explore-annapurna-base-camp-in-17-days",
  priceTable: {
    currency: "USD",
    supplementaryChargePercent: 30,
    footnote:
      "Indicative per-person pricing for the services described in this offer. Cost varies with customization. International flights are not included.",
    columns: [
      { key: "2", label: "2 travellers" },
      { key: "4", label: "4 travellers" },
      { key: "8", label: "8 travellers" },
    ],
    rows: [
      {
        label: "Standard",
        prices: { "2": "1990", "4": "1900", "8": "1769" },
      },
      {
        label: "Deluxe",
        prices: { "2": "2290", "4": "2200", "8": "2119" },
      },
    ],
  },
  bookingFeeItems: [
    "T-shirt",
    "Annapurna Conservation Area fee",
    "Trekking permit",
    "Pre-departure guide",
    "Personal assistant",
  ],
  gearChecklist: [
    "Backpack",
    "Hiking boots",
    "Sleeping bag",
    "Lightweight pants",
    "Trekking shorts",
    "T-shirts",
    "Travel towels",
    "Sunglasses / sun hat",
    "Sun block",
    "Insect repellent",
    "Personal medicines",
    "Down jacket",
    "Socks",
    "First-aid kit",
    "Rain jacket",
    "Lip balm",
  ],
  trekkingGradeNotes:
    "Grade C and D on this route mean long days on stone staircases, steady altitude gain toward ABC, and a demanding return descent. Match your fitness and trekking experience to these grades before booking.",
  faq: [
    {
      question: "Is Nepal a safe destination for tourists?",
      answer:
        "Nepal is generally peaceful and welcoming. Like any destination, use normal travel caution—especially in unfamiliar areas—and follow your guide’s advice on trail and weather conditions.",
    },
    {
      question: "What about Nepal visa information?",
      answer:
        "Tribhuvan International Airport in Kathmandu is Nepal’s main international gateway. Many airlines connect Kathmandu with major cities worldwide; visa on arrival is available for most nationalities—confirm requirements for your passport before travel.",
    },
  ],
  reviewSnippets: [
    { name: "Christopher", location: "UK", date: "2026-04-20" },
    { name: "David", location: "Australia", date: "2026-04-09" },
    { name: "Mathis & Ida", location: "Germany", date: "2026-04-06" },
    { name: "Paul & Tim", location: "Germany", date: "2026-03-25" },
    { name: "Claudia", location: "Germany", date: "2026-03-18" },
  ],
  services: {
    included: [
      "Airport pickup and drop",
      "Double-room hotel accommodation with breakfast in Kathmandu and Pokhara",
      "All standard meals during the Annapurna Base Camp trek",
      "Trekking Information Management System (TIMS)",
      "Annapurna Base Camp trekking permit",
      "One porter for every two trekkers",
      "Experienced trekking guide",
      "Guide and porter salary and insurance",
      "All ground transfers by tourist bus and private vehicle",
      "English-speaking city tour guide",
      "Entrance fees to cultural sites listed in the itinerary",
      "All government taxes",
    ],
    excluded: [
      "Bar bills",
      "Client personal insurance and unforeseen personal expenses",
      "Travel / medical insurance",
      "International flights",
      "Nepal visa fees",
      "Lunch and dinner in Kathmandu and Pokhara (except where noted)",
      "Gratuity to staff (often around 5% of total trip price)",
    ],
    optional: [
      "Room upgrade or single supplement",
      "Extra nights in Kathmandu or Pokhara",
      "Private vehicle or itinerary adjustments",
    ],
  },
  days: [
    {
      dayNumber: 1,
      title: "Arrival in Kathmandu and transfer to your hotel",
      description: "Welcome to Nepal",
      details:
        "Upon arrival in Kathmandu our representative meets you at the airport and drives you to your hotel in the city centre. The rest of the day is yours to relax or explore vibrant streets, winding alleys, restaurants, cafés, and shops before settling in after your journey.",
      destinationName: "Kathmandu",
      distanceKm: 5,
      altitudeMaxM: 1400,
      altitudeMinM: 1400,
      durationHours: 0.5,
      accommodation: "Hotel",
      meals: "As arranged",
    },
    {
      dayNumber: 2,
      title: "Kathmandu Durbar Square and Swayambhunath (Monkey Temple)",
      description: "UNESCO heritage in the valley",
      details:
        "Kathmandu Durbar Square was once a royal palace and is now home to the living goddess Kumari. Among the valley’s three durbar squares, this one is a UNESCO-listed site where palaces and pagodas showcase 14th-century woodcraft. Afterwards you visit Swayambhunath—the Monkey Temple—a landmark of harmony between Hinduism and Buddhism.",
      destinationName: "Kathmandu",
      distanceKm: 8,
      altitudeMaxM: 1400,
      altitudeMinM: 1400,
      durationHours: 5,
      accommodation: "Hotel",
      meals: "Breakfast",
    },
    {
      dayNumber: 3,
      title: "Pashupatinath and Boudhanath",
      description: "Sacred Hindu and Buddhist sites",
      details:
        "Today highlights Nepal’s spiritual diversity: Pashupatinath on the banks of the Bagmati River is among the world’s most revered Hindu temples, where cremation rites offer a profound view of life’s cycle. You then continue to Boudhanath, the tallest Buddhist stupa in Nepal, with time for lunch on a rooftop terrace overlooking the mandala.",
      destinationName: "Kathmandu",
      distanceKm: 13,
      altitudeMaxM: 1400,
      altitudeMinM: 1400,
      durationHours: 5,
      accommodation: "Hotel",
      meals: "Breakfast",
    },
    {
      dayNumber: 4,
      title: "Drive from Kathmandu to Pokhara",
      description: "Into the lake city",
      details:
        "A scenic drive of roughly six hours (about 200 km) brings you west to Pokhara, Nepal’s third-largest city and a hub for trekking and adventure. The Pokhara Valley frames the Himalayan range and Phewa Lake; boating, rafting, and paragliding are popular add-ons for anyone extending their stay.",
      destinationName: "Pokhara",
      distanceKm: 200,
      altitudeMaxM: 1400,
      altitudeMinM: 822,
      durationHours: 6,
      accommodation: "Hotel",
      meals: "Breakfast",
    },
    {
      dayNumber: 5,
      title: "Pokhara — Nayapul — trek to Ghandruk",
      description: "Gateway to ABC",
      details:
        "You drive to Nayapul, the traditional trailhead for Annapurna Base Camp, and begin trekking at an easy pace as a warm-up. After about four hours on the trail you reach Ghandruk, a beautiful Gurung village and one of the best introductions to hill culture on the route.",
      destinationName: "Ghandruk",
      distanceKm: 54,
      altitudeMaxM: 1950,
      altitudeMinM: 822,
      durationHours: 7,
      accommodation: "Tea house / mountain lodge",
      meals: "Breakfast, lunch, dinner",
    },
    {
      dayNumber: 6,
      title: "Ghandruk to Chomrong",
      description: "Stone steps and mountain life",
      details:
        "Life is demanding in these hills—supplies and building materials are often carried by mule. Walk carefully over stone stairs and rocky tread; what looks level ahead can still be a long climb. After roughly six hours you reach the Chomrong valley for a well-earned rest.",
      destinationName: "Chomrong",
      distanceKm: 10,
      altitudeMaxM: 2170,
      altitudeMinM: 1950,
      durationHours: 6,
      accommodation: "Tea house / mountain lodge",
      meals: "Breakfast, lunch, dinner",
    },
    {
      dayNumber: 7,
      title: "Chomrong to Dovan",
      description: "Deeper into the Modi Khola",
      details:
        "A nine-kilometre stage of about five hours descends and climbs along the Modi Khola corridor toward Dovan, where the forest thickens and the Annapurna massif begins to dominate the skyline.",
      destinationName: "Dovan",
      distanceKm: 9,
      altitudeMaxM: 2600,
      altitudeMinM: 2170,
      durationHours: 5,
      accommodation: "Tea house / mountain lodge",
      meals: "Breakfast, lunch, dinner",
    },
    {
      dayNumber: 8,
      title: "Dovan to Deurali",
      description: "Rhododendron and bamboo forest",
      details:
        "Steep ups and downs test stamina, but Machhapuchhre (Fishtail) appears through the trees. The path winds through rhododendron and bamboo—a sensory contrast of green gorge and white peaks above.",
      destinationName: "Deurali",
      distanceKm: 6,
      altitudeMaxM: 3200,
      altitudeMinM: 2600,
      durationHours: 3,
      accommodation: "Tea house / mountain lodge",
      meals: "Breakfast, lunch, dinner",
    },
    {
      dayNumber: 9,
      title: "Deurali to Machhapuchhre Base Camp",
      description: "Approach the sanctuary",
      details:
        "A demanding but rewarding day opens views of Machhapuchhre, Hiunchuli, Annapurna South, Annapurna I, Annapurna III, Gandharvachuli, Gangapurna, and countless streams tumbling from the walls of the amphitheatre.",
      destinationName: "Machhapuchhre Base Camp",
      distanceKm: 4,
      altitudeMaxM: 3700,
      altitudeMinM: 3200,
      durationHours: 3,
      accommodation: "Tea house / mountain lodge",
      meals: "Breakfast, lunch, dinner",
    },
    {
      dayNumber: 10,
      title: "Machhapuchhre Base Camp to Annapurna Base Camp",
      description: "Summit of the trek",
      details:
        "This is the goal: a two-hour ascent to Annapurna Base Camp at 4,130 m, surrounded by a ring of giants. Celebrate your arrival—you have earned one of Nepal’s most celebrated viewpoints.",
      destinationName: "Annapurna Base Camp",
      distanceKm: 3,
      altitudeMaxM: 4130,
      altitudeMinM: 3700,
      durationHours: 2,
      accommodation: "Tea house / mountain lodge",
      meals: "Breakfast, lunch, dinner",
    },
    {
      dayNumber: 11,
      title: "Annapurna Base Camp to Dovan",
      description: "Descent from the sanctuary",
      details:
        "After time at base camp the trail drops steeply through bamboo and rhododendron. Weather can turn windy and cold with occasional snow higher up; descending keeps you ahead of sudden changes while you retrace the Modi valley.",
      destinationName: "Dovan",
      distanceKm: 12,
      altitudeMaxM: 4130,
      altitudeMinM: 2600,
      durationHours: 6,
      accommodation: "Tea house / mountain lodge",
      meals: "Breakfast, lunch, dinner",
    },
    {
      dayNumber: 12,
      title: "Dovan to Chomrong",
      description: "Stone staircases again",
      details:
        "Thousands of paved stone steps lead up and down; you cross the Chhomrung Khola on a bridge, pass Sinuwa, and walk orchid- and fern-lined forest before more stair sections through bamboo—eventually climbing back toward Chomrong.",
      destinationName: "Chomrong",
      distanceKm: 10,
      altitudeMaxM: 2600,
      altitudeMinM: 2165,
      durationHours: 5,
      accommodation: "Tea house / mountain lodge",
      meals: "Breakfast, lunch, dinner",
    },
    {
      dayNumber: 13,
      title: "Chomrong to Ghandruk",
      description: "Gurung heritage village",
      details:
        "Returning to Ghandruk you revisit neat stone alleys and wide views toward Dhaulagiri. Many men from the village serve in Gurkha regiments; the hospitality and craftsmanship of Gurung homes make this one of the most photogenic stops on the circuit.",
      destinationName: "Ghandruk",
      distanceKm: 11,
      altitudeMaxM: 2170,
      altitudeMinM: 2012,
      durationHours: 6,
      accommodation: "Tea house / mountain lodge",
      meals: "Breakfast, lunch, dinner",
    },
    {
      dayNumber: 14,
      title: "Ghandruk to Nayapul — drive to Pokhara",
      description: "Last trekking day",
      details:
        "The final walk heads toward Birethanti and Nayapul. A vehicle transfer of about two hours returns you to Pokhara, where the rest of the day is free to enjoy the lakeside.",
      destinationName: "Pokhara",
      distanceKm: 54,
      altitudeMaxM: 1950,
      altitudeMinM: 822,
      durationHours: 5,
      accommodation: "Hotel",
      meals: "Breakfast, lunch, dinner",
    },
    {
      dayNumber: 15,
      title: "Free day in Pokhara",
      description: "Lake city at your pace",
      details:
        "Home to seven lakes, Pokhara balances leisure and adventure. Boating on Phewa, paragliding from Sarangkot, café time on the waterfront—one day is rarely enough, so choose what suits your energy.",
      destinationName: "Pokhara",
      distanceKm: 0,
      altitudeMaxM: 822,
      altitudeMinM: 822,
      durationHours: 0,
      accommodation: "Hotel",
      meals: "Breakfast",
    },
    {
      dayNumber: 16,
      title: "Drive from Pokhara to Kathmandu",
      description: "Return to the capital",
      details:
        "After trekking and lakeside rest, a full breakfast precedes the drive back to Kathmandu. The evening is open in Thamel for favourite foods, souvenirs, or a quiet last night in the valley.",
      destinationName: "Kathmandu",
      distanceKm: 200,
      altitudeMaxM: 1400,
      altitudeMinM: 822,
      durationHours: 7,
      accommodation: "Hotel",
      meals: "Breakfast",
    },
    {
      dayNumber: 17,
      title: "Departure from Kathmandu",
      description: "Farewell to the Himalaya",
      details:
        "We transfer you to the airport for your flight home. Carry memories of forests, peaks, Gurung villages, and the warmth of Nepal’s people until you return.",
      destinationName: "Kathmandu",
      distanceKm: 5,
      altitudeMaxM: 1400,
      altitudeMinM: 1400,
      durationHours: 0.5,
      accommodation: "Hotel",
      meals: "Breakfast",
    },
  ],
};
